const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE12FLOATINGTEXT'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); api.renderRepeatedly(1); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale-.5,y:(y-camera.y)/camera.scale-.5}); return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},inheritedCanvasState:{globalAlpha:1,lineJoin:'bevel',lineCap:'square',lineDash:[2,3],lineDashOffset:4,lineWidth:2,strokeStyle:'#123456',fillStyle:'#654321',font:'9px serif',textAlign:'right',textBaseline:'alphabetic'},floaters:[{source:{name:'small'},...world(300.25,250.5),age:20,text:'+$17',color:'#ffd27a',big:false},{source:{name:'big'},...world(600.5,330.25),age:40,text:'Critical',color:'#ff3344',big:true}]};
}

test('Pixi owns exactly floating text after support and preserves formulas, style, order, and handoff',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','focused E12 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseFloatingTextLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(JSON.stringify(state)).toBe(before); const layer=result.rendering.layers.floatingText; expect(result.checkpoint.tick).toBe(await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().tick)); expect(layer).toMatchObject({owned:true,counts:{total:2,visible:2,culled:0,chars:12},entries:2,textStrategy:'bounded-canvas-raster-sprites-baked-operation-alpha',activeTextObjects:0,textureCount:2,textureRefs:2,canvasState:{globalAlpha:1,lineJoin:'bevel',lineCap:'square',lineDash:[2,3],lineDashOffset:4,lineWidth:3,strokeStyle:'rgba(0,0,0,.6)',fillStyle:'#ff3344',font:'bold 16px "Segoe UI",system-ui,sans-serif',textAlign:'center',textBaseline:'alphabetic'}}); expect(layer.presentation.map(value=>[value.order,value.text,value.color,value.age,value.life,value.alpha])).toEqual([[0,'+$17','#ffd27a',20,40,.5],[1,'Critical','#ff3344',40,80,.5]]); expect(layer.order.at(-1)).toBe('canvas-scorches-sparks-smoke-and-later'); });

test('actual Pixi raster matches direct Canvas at DPR 1, 1.5, and 2 including mid-fade and subpixels',async({page},testInfo)=>{ test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E12 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseFloatingTextLayer(value); return {layer,raster:api.floatingTextRasterEvidence()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable'); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.order).toEqual(['floating-text','floating-text']); expect(result.raster.sprites.map(value=>[value.text,value.age,value.life,value.effectiveAlpha,value.spriteAlpha])).toEqual([['+$17',20,40,.5,1],['Critical',40,80,.5,1]]); expect(result.raster.stageIndices.supportActors).toBeLessThan(result.raster.stageIndices.floatingText); expect(result.raster.parity.expectedPixels).toBeGreaterThan(50); expect(result.raster.parity.actualPixels).toBeGreaterThan(50); expect(result.raster.parity.overlapPixels/Math.max(result.raster.parity.expectedPixels,result.raster.parity.actualPixels)).toBeGreaterThan(.35); expect(result.raster.parity.meanChannelDelta).toBeLessThan(35); });

for(const failure of [{kind:'floating-text-after-raster',reason:'sprite-resource'},{kind:'floating-text-final-append',reason:'container-resource'}]) test(`${failure.kind} withdraws every floater and paints uncapped Canvas`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','transactional E12 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseFloatingTextLayer(state); },{kind:failure.kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,order:['floating-text','floating-text'],laterEffect:{pixels:81,framebuffer:'same-canvas-after-floating-text'}},rendering:{layers:{supportActors:{owned:true},floatingText:{owned:false,entries:0,spritesActive:0,textureCount:0,sourceBytes:0,resourceLimitFallback:{reason:failure.reason}}}}}); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseFloatingTextLayer(value),state); expect(recovered.rendering.layers.floatingText).toMatchObject({owned:true,entries:2,resourceLimitFallback:{reason:null}}); });

for(const failure of [{kind:'floating-text-final-append',fatal:false,reason:'container-resource'},{kind:'floating-text-update',fatal:true,reason:'pixi-world-layer-failed: floating-text-update'},{kind:'final-render',fatal:true,reason:'pixi-render-failed: final-app-render'}]) test(`production renderPass ${failure.kind} keeps support below and Canvas effects above without double-age`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','full-frame E12 evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.productionFloatingTextFailureProbe(kind),failure.kind); expect(result.supportOwned).toBe(true); expect(result.effectsCanvasAbove).toBe(true); expect(result.crop.pixels).toBeGreaterThan(0); expect(result.crop.magenta).toBeGreaterThan(0); expect(result.crop.dark).toBeGreaterThan(0); expect(result.failed.fallbackReason||result.failed.layers.floatingText.resourceLimitFallback.reason).toContain(failure.reason); expect(result.after.tick).toBe(result.before.tick); expect(result.after.callbacks).toBe(result.before.callbacks); expect(result.after.rafPending).toBe(result.before.rafPending); if(failure.fatal){ expect(result.failed.active).toBe('canvas'); expect(result.after.renders).toBe(result.before.renders+1); expect(result.after.age).toBe(result.before.age+1); }else{ expect(result.failed).toMatchObject({active:'pixi-hybrid',layers:{supportActors:{owned:true},floatingText:{owned:false}}}); expect(result.after.renders).toBe(result.before.renders); expect(result.after.age).toBe(result.before.age); } });

for(const cap of [{query:'&pixiFloatingTextEntryCap=1',reason:'entry-cap'},{query:'&pixiFloatingTextLabelCap=1',reason:'label-cap'},{query:'&pixiFloatingTextCharCap=11',reason:'char-cap'},{query:'&pixiFloatingTextContainerCap=1',reason:'container-cap'},{query:'&pixiFloatingTextSpriteCap=1',reason:'sprite-cap'},{query:'&pixiFloatingTextTextureCap=1',reason:'texture-cap'},{query:'&pixiFloatingTextSourceByteCap=1',reason:'source-byte-cap'}]) test(`floating text ${cap.reason} rejects without truncation`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E12 cap evidence runs in primary Chromium'); await start(page,cap.query); const state=await page.evaluate(fixture),failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseFloatingTextLayer(value),state); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{supportActors:{owned:true},floatingText:{owned:false,entries:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.canvasFallback.pixels).toBeGreaterThan(0); });

test('WeakMap occurrence identity survives reorder, removal, text changes, and restore',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E12 identity evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); state.floaters.push(state.floaters[0]); const result=await page.evaluate(value=>window.__STATEFALL_TEST__.floatingTextIdentityChurn(value),state); expect(result.first[0].key.split(':')[1]).toBe(result.first[2].key.split(':')[1]); expect(result.first.filter(value=>value.key.split(':')[1]===result.first[0].key.split(':')[1]).map(value=>value.key.split(':').at(-1))).toEqual(['0','1']); expect(result.restored.map(value=>value.key)).toEqual(result.first.map(value=>value.key)); });

test('real event adapter cash floater is created unchanged and presented by Pixi',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E12 event-path evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.realFloatingTextEventProbe()); expect(result.fixtureKind).toContain('synthetic event delivered through the real'); expect(result.source).toMatchObject({txt:'+$17',age:0,col:'#ffd27a',big:true}); expect(result.layer).toMatchObject({owned:true,counts:{total:1},presentation:[{text:'+$17',color:'#ffd27a',age:0,life:80,alpha:1}]}); });

test('floating text ownership requires support actors and reset recovery is clean',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E12 prerequisite evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseFloatingTextLayer(value),state); expect(failed.rendering.layers.floatingText).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'support-actors-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseFloatingTextLayer(value),state); expect(recovered.rendering.layers).toMatchObject({supportActors:{owned:true},floatingText:{owned:true}}); });

test('1800-frame age/text/color/cull/pan churn plateaus within submission ceilings',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E12 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderFloatingTextChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(result.resources.every(value=>value.textureCount===value.textureRefs)).toBe(true); expect(result.resources.every(value=>value.sourceBytes>0&&value.sourceBytes<=32*1024*1024)).toBe(true); expect(new Set(result.resources.slice(-6).map(value=>value.containersCreated)).size).toBe(1); expect(new Set(result.resources.slice(-6).map(value=>value.spritesCreated)).size).toBe(1); console.log(`pixi E12 floating text churn: mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`); });
