const {test,expect}=require('@playwright/test');

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE17INTERACTION'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); });
}

test('Pixi owns the complete ordered final interaction block without input or authority mutation',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 inventory runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering.order).toEqual(['complete-notification-overlays','pick-label','selection-box','draft-panel-and-label','paused-scrim-and-labels','build-cursor','end-of-frame']); expect(result.rendering.presentation.map(value=>value.semantic)).toEqual(['pick-label','selection-box','draft-panel','draft-label','paused-scrim','paused-title','paused-subtitle','build-cursor']); expect(result.rendering).toMatchObject({owned:true,counts:{entries:8,primitives:4,labels:4,visible:8,culled:0},interactive:false,resourceLimitFallback:{reason:null}}); expect(result.notifications.owned).toBe(true); expect(result.canvas).toMatchObject({mounted:true,pointerEvents:'auto'}); expect(result.pixi.pointerEvents).toBe('none');
});

for(const variant of ['pick','box','dashed','draft','paused','valid','invalid']) test(`E17 ${variant} condition retains exact bounded inventory`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 variants run in primary Chromium'); await start(page); const result=await page.evaluate(value=>window.__STATEFALL_TEST__.renderInteractionInventory(value),variant); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering.counts.visible).toBeGreaterThan(0); if(variant==='dashed'){ const box=result.rendering.presentation.find(value=>value.semantic==='selection-box'); expect(box.primitive.dash).toEqual([7,4]); expect(box.primitive.segments).toBeGreaterThan(4); } if(variant==='valid'||variant==='invalid') expect(result.rendering.presentation[0].primitive.stroke).toBe(variant==='valid'?'#7fffa0':'#ff6b6b');
});

for(const cap of ['Entry','Primitive','Segment','Label','Char','Container','Graphics','Sprite','Texture','SourceByte']) test(`E17 ${cap} cap rejects without truncation and direct Canvas paints`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 cap evidence runs in primary Chromium'); await start(page,`&pixiInteraction${cap}Cap=0`); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); expect(result.after).toEqual(result.before); expect(result.rendering.owned).toBe(false); expect(result.rendering.resourceLimitFallback.reason).toContain('cap'); expect(result.rendering.entries).toBe(0); expect(result.canvasPixels).toBeGreaterThan(0); expect(result.notifications.owned).toBe(true);
});

for(const failure of ['interaction-overlays-source','interaction-overlays-after-paint','interaction-overlays-final-append']) test(`recoverable ${failure} withdraws E17, paints direct Canvas, and recovers cleanly`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>{ const failed=window.__STATEFALL_TEST__.renderInteractionInventory('all',kind),recovered=window.__STATEFALL_TEST__.renderInteractionInventory('all'); return {failed,recovered}; },failure); expect(result.failed.after).toEqual(result.failed.before); expect(result.failed.replayed).toBe(false); expect(result.failed.active).toBe('pixi-hybrid'); expect(result.failed.rendering.owned).toBe(false); expect(result.failed.rendering.entries).toBe(0); expect(result.failed.rendering.textureRefs).toBe(0); expect(result.failed.canvasPixels).toBeGreaterThan(0); expect(result.failed.notifications.owned).toBe(true); expect(result.recovered.rendering.owned).toBe(true); expect(result.recovered.rendering.textureRefs).toBe(result.recovered.rendering.spritesActive);
});

test('fatal final submission performs one nonadvancing full Canvas replay from frozen E17 input',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 fatal evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all','final-render')); expect(result.after).toEqual(result.before); expect(result.replayed).toBe(true); expect(result.active).toBe('canvas'); expect(result.canvasPixels).toBeGreaterThan(0); expect(result.canvas.mounted).toBe(true);
});

test('E17 viewport inventory remains bounded on mobile and reduced motion',async({page},testInfo)=>{
  test.skip(!['chromium-mobile','webkit-mobile','chromium-reduced-motion'].includes(testInfo.project.name),'E17 responsive evidence runs in mobile and reduced motion'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); const viewport=page.viewportSize(); for(const entry of result.rendering.presentation){ expect(entry.bounds.right).toBeGreaterThanOrEqual(0); expect(entry.bounds.bottom).toBeGreaterThanOrEqual(0); expect(entry.bounds.left).toBeLessThanOrEqual(viewport.width); expect(entry.bounds.top).toBeLessThanOrEqual(viewport.height); }
});

test('actual E17 Pixi primitives and labels match same-browser Canvas across DPR and device engines',async({page},testInfo)=>{
  const projects=['chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2','firefox-desktop','chromium-mobile','webkit-mobile']; test.skip(!projects.includes(testInfo.project.name),'E17 pixel evidence runs in selected engine/device projects'); await start(page); const result=await page.evaluate(()=>{ const inventory=window.__STATEFALL_TEST__.renderInteractionInventory('all'); return {dpr:devicePixelRatio,inventory,evidence:window.__STATEFALL_TEST__.interactionRasterEvidence()}; }); test.skip(!result.inventory.rendering.owned,'Pixi WebGL renderer unavailable'); const evidence=result.evidence,chromiumScale=testInfo.project.name.startsWith('chromium-desktop-scale-'); expect(evidence.resolution).toBeCloseTo(Math.min(2,result.dpr),5); expect(evidence.expectedPixels).toBeGreaterThan(100); expect(evidence.actualPixels).toBeGreaterThan(100); expect(evidence.overlapPixels/Math.max(1,evidence.expectedPixels)).toBeGreaterThan(chromiumScale ? .94 : .85); expect(evidence.meanChannelDelta).toBeLessThan(chromiumScale?12:24); expect(evidence.pixelsOverEight/Math.max(1,evidence.comparedPixels)).toBeLessThan(chromiumScale ? .15 : .3); const required=['selection-box','draft-panel','draft-label','paused-scrim','paused-title','paused-subtitle','build-cursor']; expect(evidence.order.filter(value=>required.includes(value))).toEqual(required); if(chromiumScale) expect(evidence.order).toContain('pick-label');
});

test('each E17 visual has independent production-frame raster evidence',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','independent production-frame evidence runs once'); await start(page); const cases={pick:['pick-label'],box:['selection-box'],draft:['draft-panel','draft-label'],paused:['paused-scrim','paused-title','paused-subtitle'],valid:['build-cursor'],invalid:['build-cursor']}; for(const [variant,semantics] of Object.entries(cases)){ const result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,inventory=api.renderInteractionInventory(value); return {inventory,evidence:api.interactionRasterEvidence()}; },variant); expect(result.inventory.rendering.owned,variant).toBe(true); expect(result.inventory.rendering.presentation.map(value=>value.semantic),variant).toEqual(semantics); expect(result.evidence.expectedPixels,variant).toBeGreaterThan(0); expect(result.evidence.actualPixels,variant).toBeGreaterThan(0); expect(result.evidence.overlapPixels,variant).toBeGreaterThan(0); expect(result.evidence.meanChannelDelta,variant).toBeLessThan(40); }
});

test('E17 lighter composite has parity and unsupported composite uses direct Canvas fallback',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused composite evidence runs once'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,lighter=api.renderInteractionInventory('all',null,'lighter'),lighterRaster=api.interactionRasterEvidence(),unsupported=api.renderInteractionInventory('all',null,'multiply'); return {lighter,lighterRaster,unsupported}; }); expect(result.lighter.rendering).toMatchObject({owned:true,blendMode:'add'}); expect(result.lighterRaster.expectedPixels).toBeGreaterThan(100); expect(result.lighterRaster.overlapPixels/Math.max(1,result.lighterRaster.expectedPixels)).toBeGreaterThan(.9); expect(result.unsupported.rendering).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'composite-mode'}}); expect(result.unsupported.canvasPixels).toBeGreaterThan(0);
});

test('E17-active real desktop pointer targeting, pick, drag selection, pan, zoom, resize, and context action stay Canvas-bound',async({page},testInfo)=>{
  test.skip(!['firefox-desktop','webkit-desktop'].includes(testInfo.project.name),'cross-engine E17 input evidence runs in Firefox and WebKit'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('paused')); test.skip(!initial.rendering.owned,'Pixi WebGL renderer unavailable'); expect(initial.canvas.pointerEvents).toBe('auto'); expect(initial.pixi.pointerEvents).toBe('none'); const canvas=page.locator('#map'),box=await canvas.boundingBox(),target=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('owned',4)); expect(await page.evaluate(value=>window.__STATEFALL_TEST__.screenToTile(value.x,value.y),target)).toBe(target.tile); await page.mouse.move(box.x+target.x,box.y+target.y); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.hover)).toBe(target.tile); const commands=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands); await page.mouse.click(box.x+target.x,box.y+target.y); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands)).toBe(commands+1); await page.keyboard.down('Shift'); await page.mouse.move(box.x+80,box.y+80); await page.mouse.down(); await page.mouse.move(box.x+180,box.y+150,{steps:4}); expect(await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().layers.interactionOverlays.owned)).toBe(true); await page.mouse.up(); await page.keyboard.up('Shift'); const buildTarget=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('buildable',4)),beforeBuild=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands); await page.keyboard.press('c'); await page.mouse.click(box.x+buildTarget.x,box.y+buildTarget.y); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands)).toBe(beforeBuild+1); await page.keyboard.press('Escape'); await page.mouse.move(box.x+target.x,box.y+target.y); await page.mouse.down({button:'left'}); await page.mouse.move(box.x+target.x+45,box.y+target.y+30,{steps:4}); await page.mouse.up({button:'left'}); const panned=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().camera); await page.mouse.wheel(0,120); await expect.poll(()=>page.evaluate(value=>window.__STATEFALL_TEST__.snapshot().camera.scale!==value),panned.scale).toBe(true); await page.setViewportSize({width:1100,height:700}); await page.waitForTimeout(100); const resized=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('foreign',4)); expect(await page.evaluate(value=>window.__STATEFALL_TEST__.screenToTile(value.x,value.y),resized)).toBe(resized.tile); const resizedBox=await canvas.boundingBox(); await page.mouse.click(resizedBox.x+resized.x,resizedBox.y+resized.y,{button:'right'}); await expect(page.locator('#ctx')).toBeVisible();
});

test('E17-active touch pointers target, tap, pan, pinch zoom, and remain aligned after mobile resize',async({page},testInfo)=>{
  test.skip(!['chromium-mobile','webkit-mobile'].includes(testInfo.project.name),'real mobile touch evidence runs in Chromium and WebKit'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('paused')); test.skip(!initial.rendering.owned,'Pixi WebGL renderer unavailable'); expect(initial.canvas.pointerEvents).toBe('auto'); expect(initial.pixi.pointerEvents).toBe('none'); const canvas=page.locator('#map'),box=await canvas.boundingBox(),target=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('owned',4)),commands=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands); await page.touchscreen.tap(box.x+target.x,box.y+target.y); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().input.commands)).toBe(commands+1); const before=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().camera); const dispatch=(type,id,x,y)=>canvas.dispatchEvent(type,{pointerId:id,pointerType:'touch',isPrimary:id===1,clientX:box.x+x,clientY:box.y+y,bubbles:true,cancelable:true}); await dispatch('pointerdown',1,target.x,target.y); await dispatch('pointermove',1,target.x+50,target.y+30); await dispatch('pointerup',1,target.x+50,target.y+30); const panned=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().camera); expect([panned.x,panned.y]).not.toEqual([before.x,before.y]); await dispatch('pointerdown',1,120,220); await dispatch('pointerdown',2,220,220); await dispatch('pointermove',2,180,220); await dispatch('pointerup',2,180,220); await dispatch('pointerup',1,120,220); await expect.poll(()=>page.evaluate(value=>window.__STATEFALL_TEST__.snapshot().camera.scale!==value),panned.scale).toBe(true); await page.setViewportSize({width:420,height:760}); await page.waitForTimeout(100); const aligned=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('owned',4)); expect(await page.evaluate(value=>window.__STATEFALL_TEST__.screenToTile(value.x,value.y),aligned)).toBe(aligned.tile);
});

for(const [failure,reason] of [['interaction-overlays-container','container-resource'],['interaction-overlays-graphics','graphics-resource'],['interaction-overlays-sprite','sprite-resource']]) test(`${failure} constructor failure leaves no E17 phantom resources and retries`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 constructor evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>{ const api=window.__STATEFALL_TEST__,failed=api.renderInteractionInventory('all',kind),recovered=api.renderInteractionInventory('all'); return {failed,recovered}; },failure); expect(result.failed.rendering).toMatchObject({owned:false,entries:0,textureRefs:0,resourceLimitFallback:{reason}}); expect(result.failed.canvasPixels).toBeGreaterThan(0); expect(result.recovered.rendering).toMatchObject({owned:true,resourceLimitFallback:{reason:null}});
});

test('fatal E17 update performs one Canvas replay and destroys every active resource',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 fatal update runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all','interaction-overlays-update')); expect(result.after).toEqual(result.before); expect(result.replayed).toBe(true); expect(result.active).toBe('canvas'); expect(result.canvasPixels).toBeGreaterThan(0); expect(result.rendering).toMatchObject({owned:false});
});

test('active E17 resources survive BFCache recreation and DPR resize, then clear on context loss',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 active lifecycle runs in primary Chromium'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); test.skip(!initial.owned,'Pixi WebGL renderer unavailable'); const session=await page.context().newCDPSession(page),size=page.viewportSize(); await session.send('Emulation.setDeviceMetricsOverride',{width:size.width,height:size.height,deviceScaleFactor:2,mobile:false}); await page.evaluate(()=>window.dispatchEvent(new Event('resize'))); await expect.poll(()=>page.evaluate(()=>devicePixelRatio)).toBe(2); const highDpr=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); expect(highDpr.textureAllocations).toBeGreaterThan(initial.textureAllocations); expect(highDpr.textureRefs).toBe(highDpr.spritesActive); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))); await page.locator('.pixi-world').evaluate(element=>element.remove()); await page.setViewportSize({width:1180,height:760}); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(false); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); expect(restored.owned).toBe(true); expect(restored.textureRefs).toBe(restored.spritesActive); expect(restored.textureRefs).toBeGreaterThan(0); expect(restored.textureDestroyCount).toBeGreaterThanOrEqual(highDpr.textureCount); const supported=await page.locator('.pixi-world').evaluate(canvas=>!!(canvas.getContext('webgl2')||canvas.getContext('webgl'))?.getExtension('WEBGL_lose_context')); test.skip(!supported,'WEBGL_lose_context unavailable'); await page.locator('.pixi-world').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).getExtension('WEBGL_lose_context').loseContext()); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().active)).toBe('canvas'); const cleanup=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().fallbackCleanup); expect(cleanup).toMatchObject({contextState:'destroyed',textureCount:0,spriteCount:0,containerCount:0,canvasCount:0,contextListenerCount:0});
});

test('1800-frame pointer, drag, build, pick, pause, and resize-style churn stays bounded',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E17 churn runs in primary Chromium'); test.setTimeout(180_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionChurnFrames(1800)); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(result.resources).toHaveLength(12); for(const value of result.resources){ expect(value.containersLive+value.containersIdle).toBeLessThanOrEqual(16); expect(value.graphicsActive+value.graphicsIdle).toBeLessThanOrEqual(8); expect(value.spritesActive+value.spritesIdle).toBeLessThanOrEqual(8); expect(value.textureCount).toBeLessThanOrEqual(16); expect(value.sourceBytes).toBeLessThanOrEqual(4*1024*1024); } const stable=result.resources.filter(value=>value.frame>1500); expect(stable.at(-1).textureAllocations-stable[0].textureAllocations).toBe(0); expect(stable.at(-1).textureDestroyCount-stable[0].textureDestroyCount).toBe(0);
});

test('reset releases every E17 source and restores normal ownership',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 lifecycle evidence runs in primary Chromium'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); test.skip(!initial.owned,'Pixi WebGL renderer unavailable'); const reset=await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources().layers.interactionOverlays); expect(reset).toMatchObject({owned:false,entries:0,textureCount:0,textureRefs:0,sourceBytes:0}); expect(reset.textureDestroyCount).toBe(reset.textureAllocations); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); expect(restored.owned).toBe(true); expect(restored.textureRefs).toBe(restored.spritesActive);
});
