const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE15WORLDANNOTATIONS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); api.renderRepeatedly(2); });
}

test('production Pixi owns the exact annotation block after nation overlays',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(async()=>{ const api=window.__STATEFALL_TEST__,before=await api.canonicalCheckpoint(); api.renderRepeatedly(3); return {before,after:await api.canonicalCheckpoint(),rendering:api.rendererDiagnostics()}; }); test.skip(result.rendering.active!=='pixi-hybrid','Pixi WebGL renderer unavailable'); expect(result.rendering.layers).toMatchObject({nationOverlays:{owned:true},worldAnnotations:{owned:true,order:['complete-nation-overlays','opening-marker','regions-array-order','SAM-structures-array-order','SAM-ships-array-order','SAM-network-label','canvas-credits-alerts-song-badges-and-later'],resourceLimitFallback:{reason:null}}}); expect(result.after).toEqual(result.before);
});

for(const cap of [{query:'Entry',reason:'entry-cap'},{query:'Member',reason:'member-cap'},{query:'Primitive',reason:'primitive-cap'},{query:'Segment',reason:'segment-cap'},{query:'Label',reason:'label-cap'},{query:'Char',reason:'char-cap'},{query:'Container',reason:'container-cap'},{query:'Graphics',reason:'graphics-cap'},{query:'Sprite',reason:'sprite-cap'},{query:'Texture',reason:'texture-cap'},{query:'SourceByte',reason:'source-byte-cap'}]) test(`world annotation ${cap.reason} rejects without truncation`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 cap evidence runs in primary Chromium'); await start(page,`&pixiWorldAnnotation${cap.query}Cap=0`); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory()),layer=result.rendering; expect(layer).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:cap.reason}}); expect(layer.textureRefs||0).toBe(0);
});

test('recoverable annotation final append withdraws all resources and retries',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure('world-annotations-final-append'); api.renderRepeatedly(1); const failed=api.rendererDiagnostics(); api.renderRepeatedly(1); return {failed,recovered:api.rendererDiagnostics()}; }); const failed=result.failed.layers.worldAnnotations,recovered=result.recovered.layers.worldAnnotations; expect(failed).toMatchObject({owned:false,entries:0,textureRefs:0,activeTextureCount:0,resourceLimitFallback:{reason:'container-resource'}}); expect(result.failed.layers.nationOverlays.owned).toBe(true); expect(recovered).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(recovered.activeTextureCount+recovered.zeroRefTextureCount).toBe(recovered.textureCount); expect(recovered.textureAllocations-recovered.textureDestroyCount).toBe(recovered.textureCount);
});

test('stable frames reuse textures and returning variants stay cached within policy',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 cache evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,first=api.renderWorldAnnotationInventory('all').rendering; for(let frame=0;frame<40;frame++) api.renderWorldAnnotationInventory('all'); const stable=api.rendererDiagnostics().layers.worldAnnotations,enemy=api.renderWorldAnnotationInventory('enemy').rendering,fog=api.renderWorldAnnotationInventory('fog').rendering,returned=api.renderWorldAnnotationInventory('enemy').rendering; return {first,stable,enemy,fog,returned}; }); for(const key of ['rasterUpdates','textureAllocations','textureDestroyCount']) expect(result.stable[key],key).toBe(result.first[key]); expect(result.stable.textureReuses).toBeGreaterThan(result.first.textureReuses); expect(result.returned.textureAllocations).toBe(result.fog.textureAllocations); expect(result.returned.rasterUpdates).toBe(result.fog.rasterUpdates); expect(result.returned.textureReuses).toBeGreaterThan(result.fog.textureReuses); expect(result.returned.zeroRefTextureCount).toBeGreaterThan(0);
});

test('failed post-raster transaction balances references and destroys only new resources',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 rollback evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,before=api.renderWorldAnnotationInventory('regions').rendering; api.injectRendererFailure('world-annotations-after-raster'); const failed=api.renderWorldAnnotationInventory('enemy').rendering,recovered=api.renderWorldAnnotationInventory('enemy').rendering; return {before,failed,recovered}; }); expect(result.failed).toMatchObject({owned:false,entries:0,textureRefs:0,activeTextureCount:0,resourceLimitFallback:{reason:'sprite-resource'}}); expect(result.failed.textureAllocations).toBe(result.before.textureAllocations+1); expect(result.failed.textureDestroyCount).toBe(result.before.textureDestroyCount+1); expect(result.failed.textureAllocations-result.failed.textureDestroyCount).toBe(result.failed.textureCount); expect(result.recovered.owned).toBe(true); expect(result.recovered.textureRefs).toBe(result.recovered.spritesActive); expect(result.recovered.textureAllocations-result.recovered.textureDestroyCount).toBe(result.recovered.textureCount);
});

test('texture cap pressure evicts least-recently-used zero-reference variants',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 pressure evidence runs in primary Chromium'); await start(page,'&pixiWorldAnnotationTextureCap=2'); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,regions=api.renderWorldAnnotationInventory('regions').rendering,opening=api.renderWorldAnnotationInventory('opening').rendering,returned=api.renderWorldAnnotationInventory('regions').rendering; return {regions,opening,returned}; }); for(const value of Object.values(result)){ expect(value.owned).toBe(true); expect(value.textureCount).toBeLessThanOrEqual(2); expect(value.textureAllocations-value.textureDestroyCount).toBe(value.textureCount); expect(value.activeTextureCount+value.zeroRefTextureCount).toBe(value.textureCount); } expect(result.returned.textureEvictions).toBeGreaterThan(result.regions.textureEvictions);
});

test('source-byte pressure evicts zero-reference variants before allocating',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 byte-pressure evidence runs in primary Chromium'); await start(page,'&pixiWorldAnnotationSourceByteCap=32768'); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,regions=api.renderWorldAnnotationInventory('regions').rendering,enemy=api.renderWorldAnnotationInventory('enemy').rendering,opening=api.renderWorldAnnotationInventory('opening').rendering; return {regions,enemy,opening}; }); for(const value of Object.values(result)){ expect(value.owned).toBe(true); expect(value.sourceBytes).toBeLessThanOrEqual(32768); expect(value.textureAllocations-value.textureDestroyCount).toBe(value.textureCount); } expect(result.opening.textureEvictions).toBeGreaterThan(result.regions.textureEvictions);
});

test('DPR changes allocate once and reuse the returning DPR variant',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','dynamic E15 DPR cache evidence runs in primary Chromium'); await start(page); const session=await page.context().newCDPSession(page),size=page.viewportSize(); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory('regions')); await session.send('Emulation.setDeviceMetricsOverride',{width:size.width,height:size.height,deviceScaleFactor:2,mobile:false}); await page.evaluate(()=>window.dispatchEvent(new Event('resize'))); await expect.poll(()=>page.evaluate(()=>window.devicePixelRatio)).toBe(2); const high=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory('regions')); await session.send('Emulation.setDeviceMetricsOverride',{width:size.width,height:size.height,deviceScaleFactor:1,mobile:false}); await page.evaluate(()=>window.dispatchEvent(new Event('resize'))); await expect.poll(()=>page.evaluate(()=>window.devicePixelRatio)).toBe(1); const returned=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory('regions')); expect(initial.evidence.resolution).toBe(1); expect(high.evidence.resolution).toBe(2); expect(returned.evidence.resolution).toBe(1); expect(high.rendering.textureAllocations).toBeGreaterThan(initial.rendering.textureAllocations); expect(returned.rendering.textureAllocations).toBe(high.rendering.textureAllocations); expect(returned.rendering.textureReuses).toBeGreaterThan(high.rendering.textureReuses);
});

test('reset and context teardown destroy every cached annotation texture once',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 lifecycle evidence runs in primary Chromium'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory('all').rendering); test.skip(!initial.owned,'Pixi WebGL renderer unavailable'); const reset=await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources().layers.worldAnnotations); expect(reset).toMatchObject({owned:false,entries:0,textureCount:0,textureRefs:0,sourceBytes:0}); expect(reset.textureDestroyCount).toBe(reset.textureAllocations); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory('all').rendering); expect(restored.owned).toBe(true); const supported=await page.locator('.pixi-world').evaluate(canvas=>!!(canvas.getContext('webgl2')||canvas.getContext('webgl'))?.getExtension('WEBGL_lose_context')); test.skip(!supported,'WEBGL_lose_context unavailable'); await page.locator('.pixi-world').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).getExtension('WEBGL_lose_context').loseContext()); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().active)).toBe('canvas'); const cleanup=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().fallbackCleanup.layers.worldAnnotations); expect(cleanup).toMatchObject({owned:false,entries:0,textureCount:0,textureRefs:0,sourceBytes:0}); expect(cleanup.textureDestroyCount).toBe(cleanup.textureAllocations);
});

test('fatal annotation update performs one nonadvancing full Canvas replay',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E15 fatal evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(async()=>{ const api=window.__STATEFALL_TEST__,before={checkpoint:await api.canonicalCheckpoint(),lifecycle:api.renderingLifecycle()}; api.injectRendererFailure('world-annotations-update'); api.renderRepeatedly(1); return {before,after:{checkpoint:await api.canonicalCheckpoint(),lifecycle:api.renderingLifecycle(),rendering:api.rendererDiagnostics()}}; }); expect(result.after.checkpoint).toEqual(result.before.checkpoint); expect(result.after.lifecycle.rafCallbacks).toBe(result.before.lifecycle.rafCallbacks); expect(result.after.rendering.active).toBe('canvas'); expect(result.after.rendering.fallbackReason).toContain('world-annotations-update');
});

test('opening, regions, owned SAM network, and labels match direct Canvas pixels',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E15 raster evidence runs at DPR 1, 1.5, and 2'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationInventory()); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); const value=result.evidence; expect(value.resolution).toBe(testInfo.project.use.deviceScaleFactor||1); expect(value.order).toEqual(['opening:ring','opening:label','region:10','region:11','sam-site:100','sam-site:101','sam-ship:900','sam-network:label']); expect(value.expectedPixels).toBeGreaterThan(1000); expect(value.actualPixels).toBeGreaterThan(1000); expect(value.overlapPixels/Math.max(value.expectedPixels,value.actualPixels)).toBeGreaterThan(.88); expect(value.meanChannelDelta).toBeLessThanOrEqual(15); expect(value.resources).toHaveLength(8); expect(result.rendering.presentation.map(value=>value.kind)).toEqual(['graphics','label','label','label','graphics','graphics','graphics','label']);
});

test('opening, region, enemy, fog-filtered, no-network, and zoom variants retain actual pixel parity',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E15 variant evidence runs in primary Chromium'); await start(page); const results=await page.evaluate(()=>['opening','regions','enemy','fog','no-network','zoom'].map(variant=>({variant,...window.__STATEFALL_TEST__.renderWorldAnnotationInventory(variant)}))); for(const result of results){ expect(result.owned,result.variant).toBe(true); expect(result.evidence.expectedPixels,result.variant).toBeGreaterThan(0); expect(result.evidence.actualPixels,result.variant).toBeGreaterThan(0); expect(result.evidence.overlapPixels/Math.max(result.evidence.expectedPixels,result.evidence.actualPixels),result.variant).toBeGreaterThan(.75); expect(result.evidence.meanChannelDelta,result.variant).toBeLessThanOrEqual(result.evidence.order.includes('opening:ring')?40:16); } expect(results.find(value=>value.variant==='opening').evidence.order).toEqual(['opening:ring','opening:label']); expect(results.find(value=>value.variant==='regions').evidence.order).toEqual(['region:10','region:11']); expect(results.find(value=>value.variant==='enemy').rendering.presentation.filter(value=>value.kind==='graphics').map(value=>value.style.fill)).toEqual(['rgba(190,229,184,0.14)','rgba(255,120,120,0.07)','rgba(190,229,184,0.07)']); expect(results.find(value=>value.variant==='fog').evidence.order).toEqual(['sam-site:100','sam-network:label']); expect(results.find(value=>value.variant==='no-network').evidence.order).not.toContain('sam-network:label'); expect(results.find(value=>value.variant==='zoom').evidence.order).toEqual(['opening:ring','opening:label']);
});

test('1800-frame stable many-region plateaus and real annotation churn stays bounded',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E15 churn runs in primary Chromium'); test.setTimeout(180_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWorldAnnotationChurnFrames(1800)); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(result.resources).toHaveLength(12); for(const value of result.resources){ expect(value.textureCount).toBeLessThanOrEqual(8192); expect(value.activeTextureCount+value.zeroRefTextureCount).toBe(value.textureCount); expect(value.textureAllocations-value.textureDestroyCount).toBe(value.textureCount); expect(value.sourceBytes).toBeLessThanOrEqual(64*1024*1024); } for(const [first,last] of [[result.resources[0],result.resources[1]],[result.resources[10],result.resources[11]]]) for(const key of ['rasterUpdates','textureAllocations','textureDestroyCount','textureEvictions','containersCreated','graphicsCreated','spritesCreated']) expect(last[key],`${key} stable plateau`).toBe(first[key]); expect(result.resources[0].entries).toBeGreaterThanOrEqual(90); expect(result.resources.at(-1).entries).toBeGreaterThanOrEqual(90); expect(result.resources.at(-1).textureAllocations-result.resources[0].textureAllocations).toBeLessThanOrEqual(1024); expect(Math.max(...result.resources.map(value=>value.containersCreated))).toBeLessThan(120); expect(Math.max(...result.resources.map(value=>value.graphicsCreated))).toBeLessThan(30); expect(Math.max(...result.resources.map(value=>value.spritesCreated))).toBeLessThan(120);
});
