const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

const SUPPORT_PRIMITIVES=['truck:0:0:repair-truck-body:0','truck:0:0:repair-truck-body:1','truck:0:0:repair-truck-body:2','truck:0:0:repair-truck-body:3','truck:0:0:repair-truck-body:4','truck:0:0:repair-truck-body:5','truck:0:0:repair-truck-body:6','truck:0:0:repair-truck-body:7','truck:0:0:repair-truck-body:8','truck:0:0:repair-truck-body:9','truck:0:0:repair-truck-body:10','truck:0:0:repair-truck-body:11','truck:0:0:repair-truck-body:12','truck:0:0:repair-truck-body:13','truck:0:0:repair-truck-body:14','truck:0:0:repair-truck-body:15','truck:0:1:repair-truck-progress:0','plane:0:0:spy-orbit-range:0','plane:0:1:spy-plane-body:0','plane:0:1:spy-plane-body:1','plane:0:1:spy-plane-body:2','plane:0:1:spy-plane-body:3','interceptor:0:0:interceptor-trail:0','interceptor:0:1:interceptor-trail:0','interceptor:0:2:interceptor-body:0','interceptor:0:2:interceptor-body:1','interceptor:0:2:interceptor-body:2','interceptor:0:2:interceptor-body:3'];
const SUPPORT_OPERATIONS=['truck:0:0:repair-truck-body:0:fill','truck:0:0:repair-truck-body:1:fill','truck:0:0:repair-truck-body:2:fill','truck:0:0:repair-truck-body:3:fill','truck:0:0:repair-truck-body:4:fill','truck:0:0:repair-truck-body:5:fill','truck:0:0:repair-truck-body:6:fill','truck:0:0:repair-truck-body:6:stroke','truck:0:0:repair-truck-body:7:fill','truck:0:0:repair-truck-body:8:fill','truck:0:0:repair-truck-body:8:stroke','truck:0:0:repair-truck-body:9:fill','truck:0:0:repair-truck-body:10:fill','truck:0:0:repair-truck-body:11:stroke','truck:0:0:repair-truck-body:12:stroke','truck:0:0:repair-truck-body:13:stroke','truck:0:0:repair-truck-body:14:stroke','truck:0:0:repair-truck-body:15:stroke','truck:0:1:repair-truck-progress:0:stroke','plane:0:0:spy-orbit-range:0:stroke','plane:0:1:spy-plane-body:0:fill','plane:0:1:spy-plane-body:1:fill','plane:0:1:spy-plane-body:1:stroke','plane:0:1:spy-plane-body:2:fill','plane:0:1:spy-plane-body:3:fill','interceptor:0:0:interceptor-trail:0:stroke','interceptor:0:1:interceptor-trail:0:stroke','interceptor:0:2:interceptor-body:0:fill','interceptor:0:2:interceptor-body:1:fill','interceptor:0:2:interceptor-body:2:fill','interceptor:0:2:interceptor-body:3:fill'];
const SUPPORT_STYLES=[
  ['polygon','rgba(2,8,11,.5)',null],['polygon','#182126',null],['polygon','#101a20',null],['polygon','#101a20',null],['polygon','#101a20',null],['polygon','#101a20',null],['polygon','#718086','#929b98'],['polygon','#24343d',null],['polygon','#d9d7c7','#929b98'],['polygon','#6fa6a0',null],['polygon','#c2a66e',null],
  ['line',null,'#182126'],['line',null,'#182126'],['line',null,'#182126'],['line',null,'#182126'],['line',null,'#182126'],['arc',null,'#7fffa0'],['circle',null,'rgba(191,230,255,.5)'],['polygon','rgba(2,8,11,.5)',null],['polygon','#718086','#929b98'],['polygon','#24343d',null],['polygon','#d9485f',null],
  ['line',null,'rgba(216,207,179,0.22666666666666668)'],['line',null,'rgba(216,207,179,0.45333333333333337)'],['polygon','rgba(2,8,11,.5)',null],['polygon','#101a20',null],['polygon','#718086',null],['polygon','#b96558',null]
];

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object');
  await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE11SUPPORT'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); api.renderRepeatedly(1); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),truck=world(300,250),plane=world(600,300),target=world(650,300),interceptor=world(850,350);
  return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},tick:100,repairTicks:80,spyRange:35,inheritedCanvasState:{globalAlpha:1,lineJoin:'bevel',lineCap:'square',lineDash:[],lineDashOffset:4,lineWidth:3,strokeStyle:'#123456',fillStyle:'#654321'},trucks:[{source:{name:'truck'},...truck,heading:.2,state:'work',workAt:140,visible:true}],planes:[{source:{name:'plane'},...plane,targetX:target.x,targetY:target.y,heading:.4,phase:'orbit',color:'#d9485f',owned:true,visible:false}],interceptors:[{source:{name:'interceptor'},...interceptor,visible:true,trail:[[interceptor.x-18,interceptor.y-2],[interceptor.x-10,interceptor.y-1],[interceptor.x-4,interceptor.y]]}]};
}

test('Pixi owns the exact support block after labels and hands state to floating text',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E11 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(JSON.stringify(state)).toBe(before); const layer=result.rendering.layers.supportActors;
  expect(layer).toMatchObject({owned:true,counts:{trucks:{total:1,visible:1,working:1},planes:{total:1,visible:1,orbitRanges:1},interceptors:{total:1,visible:1,trailSegments:2}},trailPointCount:3,entries:3,generatedTextures:{strategy:'vector-primitives',references:0},canvasState:{globalAlpha:1,lineJoin:'bevel',lineCap:'square',lineDash:[],lineDashOffset:4,lineWidth:2,strokeStyle:'rgba(216,207,179,0.45333333333333337)',fillStyle:'#654321'}});
  expect(layer.presentation.map(value=>[value.category,value.order,value.items])).toEqual([['truck',0,['repair-truck-body','repair-truck-progress']],['plane',0,['spy-orbit-range','spy-plane-body']],['interceptor',0,['interceptor-trail','interceptor-trail','interceptor-body']]]);
});

test('real isolated Pixi Graphics paint every support primitive at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E11 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseSupportActorLayer(value),before=api.rendererDiagnostics(),raster=api.supportActorRasterEvidence(); return {layer,before,raster,after:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable');
  expect(result.raster.order).toEqual(['repair-truck-body','repair-truck-progress','spy-orbit-range','spy-plane-body','interceptor-trail','interceptor-trail','interceptor-body']); expect(result.raster.primitiveOrder).toEqual(SUPPORT_PRIMITIVES); expect(result.raster.operationOrder).toEqual(SUPPORT_OPERATIONS); expect(result.raster.primitives.map(value=>value.key)).toEqual(SUPPORT_PRIMITIVES); expect(result.raster.primitives.map(value=>[value.kind,value.fill,value.stroke])).toEqual(SUPPORT_STYLES); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.combined.pixels).toBeGreaterThan(100);
  for(const primitive of result.raster.primitives){ expect(primitive.pixels,`${primitive.key} Pixi pixels`).toBeGreaterThan(0); expect(primitive.bounds,`${primitive.key} Pixi bounds`).not.toBeNull(); expect(primitive.canvas.pixels,`${primitive.key} Canvas pixels`).toBeGreaterThan(0); expect(primitive.canvas.bounds,`${primitive.key} Canvas bounds`).not.toBeNull(); expect(primitive.parity.basis).toContain('edge-AA'); expect(primitive.parity.overlapRatio,`${primitive.key} Pixi/Canvas overlap`).toBeGreaterThan(.15); expect(primitive.parity.areaRatio,`${primitive.key} Pixi/Canvas area`).toBeGreaterThan(.15); expect(primitive.parity.areaRatio,`${primitive.key} Pixi/Canvas area`).toBeLessThan(2.2); expect(primitive.parity.meanChannelDelta,`${primitive.key} Pixi/Canvas opaque-background mean channel delta`).toBeLessThan(55); for(const edge of ['left','top','right','bottom']) expect(Math.abs(primitive.bounds[edge]-primitive.canvas.bounds[edge]),`${primitive.key} ${edge} alignment`).toBeLessThanOrEqual(3/result.raster.resolution+.01); }
  const centers={'truck:0:0:repair-truck-body:0':[300,250],'truck:0:1:repair-truck-progress:0':[300,250],'plane:0:0:spy-orbit-range:0':[650,300],'plane:0:1:spy-plane-body:0':[600,300],'interceptor:0:2:interceptor-body:0':[850,350]}; for(const [key,[x,y]] of Object.entries(centers)){ const bounds=result.raster.primitives[SUPPORT_PRIMITIVES.indexOf(key)].bounds; expect(bounds.left,`${key} left`).toBeLessThan(x); expect(bounds.right,`${key} right`).toBeGreaterThan(x); expect(bounds.top,`${key} top`).toBeLessThan(y); expect(bounds.bottom,`${key} bottom`).toBeGreaterThan(y); }
  expect(result.raster.stageIndices.mapLabels).toBeLessThan(result.raster.stageIndices.supportActors); expect(result.raster.restored).toBe(true); for(const key of ['textureCount','graphicsCount','containerCount']) expect(result.after[key]).toBe(result.before[key]);
});

test('support resource failures withdraw all categories, direct Canvas paint, and recover',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E11 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture);
  for(const [kind,reason] of [['support-actor-graphics-after-paint','graphics-resource'],['support-actor-container-after-append','container-resource'],['support-actor-final-append','container-resource']]){ const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseSupportActorLayer(state); },{kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,laterFloater:{pixels:81,framebuffer:'same-canvas-after-support-actors'}},rendering:{layers:{mapLabels:{owned:true},supportActors:{owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason}}}}}); expect(failed.canvasFallback.order).toEqual(['repair-truck-body','repair-truck-progress','spy-orbit-range','spy-plane-body','interceptor-trail','interceptor-trail','interceptor-body']); for(const value of Object.values(failed.canvasFallback.semanticPixels)) expect(value).toBeGreaterThan(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); expect(recovered.rendering.layers.supportActors).toMatchObject({owned:true,entries:3,resourceLimitFallback:{reason:null}}); }
});

for(const failure of [
  {kind:'support-actor-graphics-after-paint',fatal:false,reason:'graphics-resource'},
  {kind:'support-actor-final-append',fatal:false,reason:'container-resource'},
  {kind:'support-actor-update',fatal:true,reason:'pixi-world-layer-failed: support-actor-update'},
  {kind:'final-render',fatal:true,reason:'pixi-render-failed: final-app-render'}
]) test(`production renderPass ${failure.kind} proves isolated support operations and later floating text`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','full-frame E11 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.productionSupportActorFailureProbe(kind),failure.kind);
  for(const layer of ['preStructures','structures','navalLogistics','warships','projectiles','missiles','aircraft','mapLabels','supportActors']) expect(result.before.diagnostics.layers[layer].owned,`${layer} prerequisite`).toBe(true);
  expect(result.primitiveOrder).toEqual(SUPPORT_OPERATIONS); expect(result.totalDifferentialPixels).toBeGreaterThan(0); expect(result.labels.owned).toBe(true); expect(result.labels.crop.pixels).toBeGreaterThan(0); expect(result.floater).toMatchObject({framebuffer:'actual-floating-text-after-support',crop:{pixels:expect.any(Number),colors:expect.any(Number)}}); expect(result.floater.crop.pixels).toBeGreaterThan(0); for(const category of Object.values(result.support)) expect(category.pixels).toBeGreaterThan(0);
  const overlays=new Set(['truck:0:0:repair-truck-body:6:fill','interceptor:0:2:interceptor-body:1:fill']); for(const key of SUPPORT_OPERATIONS){ const evidence=result.primitiveEvidence[key],overlay=overlays.has(key); expect(evidence.framebuffer).toBe(failure.fatal?'fatal-canvas-replay':'production-renderPass-composited-pixi-then-canvas'); expect(evidence.maskPixels,`${key} mask`).toBeGreaterThan(0); if(overlay) expect(evidence.exclusiveMaskPixels,`${key} overlay mask`).toBe(0); else expect(evidence.exclusiveMaskPixels,`${key} exclusive mask`).toBeGreaterThan(0); if(evidence.sample) expect(evidence.sample.actual,`${key} omission sample`).not.toEqual(evidence.sample.withoutSupport); expect(result.omissionSensitivity[key]).toEqual({withAllMasks:result.totalDifferentialPixels,withoutMask:result.totalDifferentialPixels-evidence.differentialPixels,lostPixels:evidence.differentialPixels}); }
  expect(Object.keys(result.exclusiveMaskOverlaps)).toHaveLength(SUPPORT_OPERATIONS.length*(SUPPORT_OPERATIONS.length-1)/2); expect(Object.values(result.exclusiveMaskOverlaps).every(value=>value===0)).toBe(true);
  if(failure.fatal){ expect(result.labels.domBelowCanvas).toBe(false); expect(result.failed.active).toBe('canvas'); expect(result.failed.fallbackReason).toContain(failure.reason); expect(result.afterFrame.callbacks).toBe(result.before.callbacks); expect(result.afterFrame.renders).toBe(result.before.renders+1); expect(result.afterFrame.rafPending).toBe(result.before.rafPending); expect(result.afterFrame.floaterAge).toBe(result.before.floaterAge+1); expect(result.afterFrame.tick).toBe(result.before.tick); }else{ expect(result.labels.domBelowCanvas).toBe(true); expect(result.failed).toMatchObject({active:'pixi-hybrid',layers:{mapLabels:{owned:true},supportActors:{owned:false,resourceLimitFallback:{reason:failure.reason}}}}); expect(result.afterFrame.floaterAge).toBe(result.before.floaterAge); }
});

test('support container and Graphics constructor failures leave no phantom resources',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E11 constructor evidence runs in primary Chromium'); for(const [kind,reason] of [['support-actor-container','container-resource'],['support-actor-graphics','graphics-resource']]){ await start(page); const state=await page.evaluate(fixture),base=state.trucks[0]; for(let i=0;i<64;i++) state.trucks.push({...base,source:{i},x:base.x+(i%8)*2,y:base.y+Math.floor(i/8)*2,state:'out'}); const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseSupportActorLayer(state); },{kind,state}); expect(failed.rendering.layers.supportActors).toMatchObject({owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason}}); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); expect(recovered.rendering.layers.supportActors).toMatchObject({owned:true,entries:67,resourceLimitFallback:{reason:null}}); } });

for(const cap of [
  {query:'&pixiSupportActorEntryCap=2',reason:'entry-cap'},
  {query:'&pixiSupportActorTrailCap=2',reason:'trail-point-cap'},
  {query:'&pixiSupportActorPrimitiveCap=27',reason:'primitive-cap'},
  {query:'&pixiSupportActorSegmentCap=1',reason:'segment-cap'},
  {query:'&pixiSupportActorContainerCap=2',reason:'container-cap'},
  {query:'&pixiSupportActorGraphicsCap=6',reason:'graphics-cap'}
]) test(`support ${cap.reason} rejects without truncation`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E11 cap evidence runs in primary Chromium'); await start(page,cap.query); const state=await page.evaluate(fixture),failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{mapLabels:{owned:true},supportActors:{owned:false,entries:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.canvasFallback.pixels).toBeGreaterThan(0); });

test('WeakMap occurrence identity survives reorder, removal, and restore',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E11 identity evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); state.trucks.push(state.trucks[0]); const result=await page.evaluate(value=>window.__STATEFALL_TEST__.supportActorIdentityChurn(value),state); expect(result.first.map(value=>value.category)).toEqual(['truck','truck','plane','interceptor']); expect(result.first[0].key.split(':')[1]).toBe(result.first[1].key.split(':')[1]); expect(result.first.slice(0,2).map(value=>value.key.split(':').at(-1))).toEqual(['0','1']); expect(result.reordered.slice(0,2).map(value=>value.key.split(':').at(-1))).toEqual(['0','1']); expect(result.restored.map(value=>value.key)).toEqual(result.first.map(value=>value.key)); });

test('support ownership requires map labels and reset recovery is clean',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E11 prerequisite evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); expect(failed.rendering.layers.supportActors).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'map-labels-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseSupportActorLayer(value),state); expect(recovered.rendering.layers).toMatchObject({mapLabels:{owned:true},supportActors:{owned:true}}); });

test('1800-frame support state/type/color/progress/trail/fog/cull/reorder churn plateaus',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E11 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderSupportActorChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); for(const key of ['containersCreated','graphicsCreated']) expect(new Set(result.resources.slice(-6).map(value=>value[key])).size).toBe(1); expect(result.resources.every(value=>value.textureReferences===0)).toBe(true); console.log(`pixi E11 support churn: mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`); });
