const {test,expect}=require('@playwright/test');

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE16NOTIFICATIONS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); api.renderRepeatedly(2); });
}

test('Pixi owns ordered notification overlays after annotations without authority mutation',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering).toMatchObject({owned:true,order:['complete-world-annotations','credits-exclusive','nuclear-alerts-array-order','song-banner','badges-array-order','canvas-pick-selection-draft-paused-build-and-later'],spritesActive:1,textureCount:1,textureRefs:1,interactive:false,resourceLimitFallback:{reason:null}}); expect(result.rendering.presentation.map(value=>value.kind)).toEqual(['nuclear-alert','song-banner','fallen-badge','unification-badge']); expect(result.rendering.sourceBytes).toBeGreaterThan(0);
});

test('credits use the exclusive E16 viewport layer without advancing authority or audio',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 credits evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderCreditsNotificationInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering.presentation.map(value=>value.kind)).toEqual(['credits-open','credits-star','credits-title','credits-card','credits-end']); expect(result.rendering.bounds).toEqual({left:0,top:0,right:1140,bottom:900});
});

test('notification viewport raster is DPR-aware and exactly source-byte bounded',async({page},testInfo)=>{
  test.skip(!['chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E16 DPR evidence runs at DPR 1, 1.5, and 2'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationInventory('banner')); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); const dpr=testInfo.project.use.deviceScaleFactor||1,bounds=result.rendering.bounds; expect(result.rendering.resolution).toBe(dpr); expect(result.rendering.sourceBytes).toBe(Math.round(bounds.right*dpr)*Math.round(bounds.bottom*dpr)*4);
});

test('actual Pixi notification pixels match direct Canvas at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E16 pixel matrix runs at DPR 1, 1.5, and 2'); await start(page); const cases=[['fallen',{lineCap:'round',lineJoin:'bevel',lineWidth:7,globalAlpha:.82,globalCompositeOperation:'source-over',lineDash:[3,2],lineDashOffset:1.5,font:'13px serif',textAlign:'right',textBaseline:'middle',translateX:2,translateY:1}],['fallen',{lineCap:'butt',lineJoin:'miter',lineWidth:2,globalAlpha:1,globalCompositeOperation:'source-over',lineDash:[],lineDashOffset:0}],['alert',{lineCap:'square',lineJoin:'round',lineWidth:5,globalAlpha:.7,globalCompositeOperation:'source-over',lineDash:[2,4],lineDashOffset:2}],['fade',{lineCap:'round',lineJoin:'round',lineWidth:3,globalAlpha:.65,globalCompositeOperation:'source-over',lineDash:[],lineDashOffset:0}],['all',{lineCap:'butt',lineJoin:'bevel',lineWidth:4,globalAlpha:.9,globalCompositeOperation:'lighter',lineDash:[1,3],lineDashOffset:.5}]]; for(const [variant,state] of cases){ const result=await page.evaluate(([variant_,state_])=>window.__STATEFALL_TEST__.renderNotificationPixelMatrix(variant_,state_),[variant,state]); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); const evidence=result.evidence; expect(evidence.resolution).toBe(testInfo.project.use.deviceScaleFactor||1); expect(evidence.sourceWidth).toBe(evidence.physicalWidth); expect(evidence.sourceHeight).toBe(evidence.physicalHeight); expect(evidence.expectedPixels,variant).toBeGreaterThan(100); expect(evidence.actualPixels,variant).toBeGreaterThan(100); expect(evidence.overlapPixels/Math.max(1,evidence.expectedPixels),variant).toBeGreaterThan(.98); expect(evidence.meanChannelDelta,variant).toBeLessThan(2); expect(evidence.pixelsOverTwo/Math.max(1,evidence.comparedPixels),variant).toBeLessThan(.02); expect(evidence.canvasState.lineCap).toBe(state.lineCap); expect(evidence.canvasState.lineJoin).toBe(state.lineJoin); expect(evidence.canvasState.globalAlpha).toBe(state.globalAlpha); expect(evidence.canvasState.globalCompositeOperation).toBe(state.globalCompositeOperation); expect(evidence.canvasState.lineDash).toEqual(state.lineDash); expect(evidence.canvasState.transform[4]).toBeCloseTo((state.translateX||0)*evidence.resolution,8); expect(evidence.canvasState.transform[5]).toBeCloseTo((state.translateY||0)*evidence.resolution,8); expect(result.handoff).toMatchObject({lineCap:state.lineCap,lineJoin:state.lineJoin,lineWidth:state.lineWidth,globalAlpha:state.globalAlpha,globalCompositeOperation:state.globalCompositeOperation,lineDash:state.lineDash,lineDashOffset:state.lineDashOffset}); expect(result.handoff.transform).toEqual(evidence.canvasState.transform); }
});

for(const failure of [null,'final-render']) test(`credits camera chronology ${failure||'normal'} uses frame-start world camera and one late advancement`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E16 credits chronology and fatal replay run in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.creditsCameraChronologyProbe(kind),failure); expect(result.start).toEqual({x:-137,y:-83,s:.73}); expect(result.worldCamera).toEqual(result.start); expect(result.prepared).not.toEqual(result.start); expect(result.final).toEqual(result.prepared); expect(result.chronology.indexOf('notifications')).toBeGreaterThan(result.chronology.indexOf('world-annotations-painted')); expect(result.next.start).toEqual(result.prepared); expect(result.next.worldCamera).toEqual(result.next.start); expect(result.next.prepared).not.toEqual(result.next.start); expect(result.next.final).toEqual(result.next.prepared); expect(result.next.chronology.indexOf('notifications')).toBeGreaterThan(result.next.chronology.indexOf('world-annotations-painted')); if(failure){ expect(result.replayed).toBe(true); expect(result.rendering.active).toBe('canvas'); expect(result.rendering.fallbackReason).toContain(failure==='final-render'?'final-app-render':'notification-overlays-update'); }else expect(result.replayed).toBe(false);
});

test('default Canvas keeps the same first and subsequent credits camera chronology',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','Canvas credits chronology runs in primary Chromium'); await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); }); await page.goto('/index.html?browserTest=1',{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('E16CANVASCREDITS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); }); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.creditsCameraChronologyProbe()); expect(result.rendering.active).toBe('canvas'); expect(result.worldCamera).toEqual(result.start); expect(result.final).toEqual(result.prepared); expect(result.next.start).toEqual(result.prepared); expect(result.next.worldCamera).toEqual(result.next.start); expect(result.next.final).toEqual(result.next.prepared);
});

test('notification anchoring remains bounded on mobile and under reduced motion',async({page},testInfo)=>{
  test.skip(!['chromium-mobile','webkit-mobile','chromium-reduced-motion'].includes(testInfo.project.name),'E16 responsive/motion evidence runs in mobile and reduced-motion projects'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationInventory('all')); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); const bounds=result.rendering.bounds,viewport=page.viewportSize(); expect(bounds.left).toBe(0); expect(bounds.top).toBe(0); expect(bounds.right).toBeGreaterThan(0); expect(bounds.bottom).toBeGreaterThan(0); expect(bounds.right).toBeLessThanOrEqual(viewport.width); expect(bounds.bottom).toBeLessThanOrEqual(viewport.height);
});

for(const cap of [{query:'Entry',reason:'entry-cap'},{query:'Label',reason:'label-cap'},{query:'Char',reason:'char-cap'},{query:'Primitive',reason:'primitive-cap'},{query:'Segment',reason:'segment-cap'},{query:'Container',reason:'container-cap'},{query:'Graphics',reason:'graphics-cap'},{query:'Sprite',reason:'sprite-cap'},{query:'Texture',reason:'texture-cap'},{query:'SourceByte',reason:'source-byte-cap'}]) test(`notification ${cap.reason} falls back without truncation`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 cap evidence runs in primary Chromium'); await start(page,`&pixiNotification${cap.query}Cap=0`); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationInventory()); expect(result.after).toEqual(result.before); expect(result.rendering).toMatchObject({owned:false,resourceLimitFallback:{reason:cap.reason}}); expect(result.rendering.spritesActive).toBe(0);
});

test('notification final append withdraws E16 and recovers next frame',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure('notification-overlays-final-append'); const failed=api.renderNotificationInventory().rendering,recovered=api.renderNotificationInventory().rendering; return {failed,recovered,annotations:api.rendererDiagnostics().layers.worldAnnotations}; }); expect(result.failed).toMatchObject({owned:false,spritesActive:0,textureCount:0,resourceLimitFallback:{reason:'container-resource'}}); expect(result.annotations.owned).toBe(true); expect(result.recovered).toMatchObject({owned:true,spritesActive:1,textureCount:1,resourceLimitFallback:{reason:null}});
});

test('queued age-zero badge advances, sounds, counts, and displays in the same frame',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 frame-order evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe()); test.skip(result.first.rendering.active!=='pixi-hybrid','Pixi WebGL renderer unavailable'); const first=result.first.rendering.layers.notificationOverlays; expect(result.first).toMatchObject({age:2,present:true,audio:1}); expect(first).toMatchObject({owned:true,counts:{entries:1,visible:1},resourceLimitFallback:{reason:null}}); expect(first.presentation).toHaveLength(1); expect(first.presentation[0]).toMatchObject({kind:'fallen-badge',age:2,alpha:2/12}); expect(result.first.next).toMatchObject({age:3,present:true,audio:1,rendering:{owned:true,counts:{entries:1}}}); expect(result.first.next.rendering.presentation[0]).toMatchObject({age:3,alpha:3/12});
});

test('badge final lifetime frame paints once and is absent from the following inventory',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 lifetime evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe(null,3)); test.skip(result.first.rendering.active!=='pixi-hybrid','Pixi WebGL renderer unavailable'); expect(result.first).toMatchObject({age:2,present:true,audio:1}); expect(result.first.next).toMatchObject({age:3,present:false,audio:1,rendering:{owned:true,counts:{entries:1}}}); expect(result.first.next.rendering.presentation[0]).toMatchObject({age:3,alpha:0}); expect(result.first.following).toMatchObject({age:3,present:false,audio:1,rendering:{owned:true,counts:{entries:0}}});
});

for(const failure of ['final-render']) test(`${failure} replays the prepared badge once without re-age or re-audio`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 fatal replay evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe(kind),failure); expect(result.first).toMatchObject({age:2,present:true,audio:1}); expect(result.first.rendering.active).toBe('canvas'); expect(result.first.rendering.fallbackReason).toContain(failure==='final-render'?'final-app-render':'notification-overlays-update'); expect(result.first.badgePixels).toBeGreaterThan(0); expect(result.first.interactionPixels).toBeGreaterThan(0);
});

test('every E16 offscreen stage fails notification-only, cleans up, and recovers',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 transaction evidence runs in primary Chromium'); await start(page); const cases=[['notification-raster-create-element','create-element'],['notification-raster-context-resource','context-resource'],['notification-raster-dimension-resize','dimension-resize'],['notification-raster-state-apply','state-apply'],['notification-raster-paint-resource','paint-resource'],['notification-raster-final-state-capture','final-state-capture'],['notification-raster-state-handoff','state-handoff'],['notification-overlays-canvas-source','canvas-source-resource'],['notification-overlays-texture','texture-resource'],['notification-overlays-texture-update','source-update-resource'],['notification-overlays-update','update-resource']];
  for(const [failure,reason] of cases){ const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe(kind),failure),layer=result.first.rendering.layers.notificationOverlays; expect(result.first).toMatchObject({age:2,present:true,audio:1}); expect(result.first.rendering.active,failure).toBe('pixi-hybrid'); expect(layer,failure).toMatchObject({owned:false,sourceBytes:0,textureCount:0,spritesActive:0,resourceLimitFallback:{reason}}); expect(result.first.rendering.layers.worldAnnotations.owned,failure).toBe(true); expect(result.first.raster,failure).toMatchObject({width:0,height:0}); expect(result.first.badgePixels,failure).toBeGreaterThan(0); expect(result.first.interactionPixels,failure).toBeGreaterThan(0); expect(result.first.recovered,failure).toMatchObject({owned:true,textureCount:1,spritesActive:1,resourceLimitFallback:{reason:null}}); }
});

test('destination-dependent and unknown composites bypass allocation and preserve direct Canvas results',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 composition fallback runs in primary Chromium'); await start(page); for(const mode of ['destination-out','destination-in','copy','xor','unknown']){ const result=await page.evaluate(value=>window.__STATEFALL_TEST__.renderNotificationCompositeFallback(value),mode); expect(result.failed.layer,mode).toMatchObject({owned:false,sourceBytes:0,textureCount:0,spritesActive:0,resourceLimitFallback:{reason:'composite-mode'}}); expect(result.failed.annotations.owned,mode).toBe(true); expect(result.failed.raster.allocations,mode).toBe(result.before.allocations); expect(result.failed.raster.paints,mode).toBe(result.before.paints); expect(result.failed.raster,mode).toMatchObject({width:0,height:0}); expect(result.failed.different,mode).toBe(0); expect(result.recovered,mode).toMatchObject({owned:true,blendMode:'normal',resourceLimitFallback:{reason:null}}); }
});

for(const cap of ['Entry','Char','Primitive','SourceByte']) test(`notification ${cap} cap preflight leaves the offscreen raster untouched`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E16 preflight evidence runs in primary Chromium'); await start(page,`&pixiNotification${cap}Cap=0`); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe()),reason=`${cap.replace(/[A-Z]/g,(value,index)=>(index?'-':'')+value.toLowerCase())}-cap`; expect(result.first.rendering.layers.notificationOverlays).toMatchObject({owned:false,resourceLimitFallback:{reason}}); expect(result.first.raster).toEqual(result.before.raster); expect(result.first.badgePixels).toBeGreaterThan(0); expect(result.first.interactionPixels).toBeGreaterThan(0);
});

test('default Canvas notification path never allocates the Pixi offscreen raster',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','production/default Canvas evidence runs in primary Chromium'); await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); }); await page.goto('/index.html?browserTest=1',{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('E16CANVASNOOFFSCREEN'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); }); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.notificationBadgeFrameProbe()); expect(result.first.rendering.active).toBe('canvas'); expect(result.first.raster).toEqual(result.before.raster); expect(result.first.badgePixels).toBeGreaterThan(0); expect(result.first.interactionPixels).toBeGreaterThan(0);
});

test('notification viewport source releases on reset and BFCache suspend, then recreates normally',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E16 lifecycle evidence runs in primary Chromium'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationPixelMatrix('all').raster); expect(initial.width).toBeGreaterThan(0); expect(initial.height).toBeGreaterThan(0); const reset=await page.evaluate(()=>{ const rendering=window.__STATEFALL_TEST__.resetRendererResources(); return {rendering,raster:window.__STATEFALL_TEST__.notificationBadgeFrameProbe(null,1).before.raster}; }); expect(reset.rendering.layers.notificationOverlays).toMatchObject({owned:false,sourceBytes:0,textureCount:0,spritesActive:0}); expect(reset.raster).toMatchObject({width:0,height:0}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationPixelMatrix('fallen')); expect(restored.raster.width).toBeGreaterThan(0); expect(restored.rendering.owned).toBe(true); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(true); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(false); const recreated=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationPixelMatrix('alert')); expect(recreated.raster.width).toBeGreaterThan(0); expect(recreated.rendering).toMatchObject({owned:true,sourceBytes:expect.any(Number),textureCount:1,spritesActive:1});
});

test('1800-frame notification churn remains bounded and meets submission ceilings',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E16 churn runs in primary Chromium'); test.setTimeout(180_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNotificationChurnFrames(1800)); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(result.resources).toHaveLength(12); for(const value of result.resources){ expect(value.textureCount).toBeLessThanOrEqual(1); expect(value.sourceBytes).toBeLessThanOrEqual(64*1024*1024); expect(value.containersLive).toBeLessThanOrEqual(1); expect(value.spritesActive).toBeLessThanOrEqual(1); } expect(result.resources.at(-1).textureAllocations-result.resources[0].textureAllocations).toBe(0); expect(result.resources.at(-1).textureDestroyCount-result.resources[0].textureDestroyCount).toBe(0);
});
