const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE10LABELS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); api.renderRepeatedly(1); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),flag={layers:[['h','#ffffff','#d52b1e','#0038a8']]},at=(owner,n,x,y,name,color)=>({owner,n,...world(x,y),player:{name,color,flag}}),area=(id,x,y,troops,tiles)=>{ const point=world(x,y); return {id,cx:point.x,cy:point.y,troops,tiles}; };
  return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},now:20000,draftDoneAt:0,draftActive:false,meId:0,hoverArea:8,garrisonEnabled:true,inheritedCanvasState:{globalAlpha:.8,lineJoin:'miter',lineCap:'round',lineDash:[2,3],lineDashOffset:4,lineWidth:1.5,strokeStyle:'#123456',fillStyle:'#654321',font:'9px serif',textAlign:'right',textBaseline:'alphabetic'},draftPicks:[at(0,1,320,250,'Mine','#d9485f'),at(1,1,520,280,'Other','#33a06f')],areas:[area(7,300,430,999,5),area(8,500,430,1250,20)]};
}

test('Pixi owns only draft and garrison labels with stable order and cached raster sources',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E10 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(JSON.stringify(state)).toBe(before); const layer=result.rendering.layers.mapLabels;
  expect(layer).toMatchObject({owned:true,counts:{draftPicks:2,draftEntries:2,garrisonAreas:2,garrisonEntries:2,labels:8},entries:4,textStrategy:'bounded-canvas-raster-label-sprites',activeTextObjects:0,pixiTextCache:{references:0,textures:0},gpuBytes:{status:'unknown',bytes:null},canvasState:{globalAlpha:1,lineWidth:3,fillStyle:'#fff',font:'bold 12px "Segoe UI",system-ui,sans-serif',textAlign:'center',textBaseline:'alphabetic'}});
  expect(layer.presentation.map(value=>[value.key,value.category,value.items.map(item=>item.kind)])).toEqual([['draft:0:1','draft',['draft-flag','draft-pick','draft-owner']],['draft:1:1','draft',['draft-flag','draft-pick','draft-owner']],['garrison:0:7','garrison',['garrison-count']],['garrison:0:8','garrison',['garrison-count']]]); expect(layer.resources.map(value=>value.key)).toEqual(['draft:0:1','draft:1:1','garrison:0:7','garrison:0:8']); expect(layer.textureRefs).toBe(layer.spritesActive); expect(layer.sourceBytes).toBeGreaterThan(0); expect(layer.sourceBytes).toBeLessThanOrEqual(layer.sourceByteMaximum);
  const changed=structuredClone(state); changed.draftPicks[1].player.name='Changed'; changed.areas[1].troops=9876; const next=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),changed); expect(next.rendering.layers.mapLabels).toMatchObject({owned:true,entries:4}); expect(next.rendering.layers.mapLabels.presentation.flatMap(value=>value.items).map(value=>value.text).filter(Boolean)).toEqual(expect.arrayContaining(['Changed','9.9k ⚑'])); expect(next.rendering.layers.mapLabels.textureCount).toBeLessThanOrEqual(next.rendering.layers.mapLabels.textureMaximum);
});

test('actual isolated label sprites rasterize at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E10 DPR evidence runs in Chromium projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseMapLabelLayer(value),before=api.rendererDiagnostics(),composite=api.mapLabelCompositeEvidence(),raster=api.mapLabelRasterEvidence([{x:320,y:250}]); return {layer,before,composite,raster,after:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable'); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.order).toEqual(['draft-flag','draft-pick','draft-owner','draft-flag','draft-pick','draft-owner','garrison-count','garrison-count']); expect(result.raster.combined.pixels).toBeGreaterThan(0); for(const label of result.raster.labels){ expect(label.pixels,label.key).toBeGreaterThan(0); expect(label.bounds,label.key).not.toBeNull(); expect(label.sourceWidth,label.key).toBeGreaterThanOrEqual(Math.floor((label.bounds.right-label.bounds.left)*result.raster.resolution)); }
  const composite=result.composite; expect(composite.stageIndices.aircraft).toBeLessThan(composite.stageIndices.mapLabels); expect(composite.sprites.every(value=>value.spriteAlpha===1)).toBe(true); expect(composite.sprites.filter(value=>value.kind.startsWith('draft-')).every(value=>value.effectiveAlpha===5/7)).toBe(true); expect(composite.comparisons.map(value=>value.kind)).toEqual(['combined','draft-flag','draft-pick','draft-owner','garrison-count']); for(const comparison of composite.comparisons){ expect(comparison.expectedPixels,`${comparison.kind} Canvas reference`).toBeGreaterThan(0); expect(comparison.overlapPixels/comparison.expectedPixels,`${comparison.kind} aligned pixel coverage`).toBeGreaterThanOrEqual(.95); expect(comparison.actualPixels/comparison.expectedPixels,`${comparison.kind} raster area ratio`).toBeGreaterThanOrEqual(.9); expect(comparison.actualPixels/comparison.expectedPixels,`${comparison.kind} raster area ratio`).toBeLessThanOrEqual(1.1); expect(comparison.meanChannelDelta,`${comparison.kind} mean RGBA delta`).toBeLessThanOrEqual(8); expect(comparison.pixelsOverTwo/comparison.comparedPixels,`${comparison.kind} antialiased-edge delta fraction`).toBeLessThanOrEqual(.35); }
  expect(result.raster.restored).toBe(true); expect(result.after.layers.mapLabels.sourceBytes).toBe(result.before.layers.mapLabels.sourceBytes); expect(result.after.layers.mapLabels.textureRefs).toBe(result.before.layers.mapLabels.textureRefs);
});

test('map-label failures withdraw the whole block, paint direct Canvas, and recover',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E10 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); for(const [kind,reason] of [['map-label-after-raster','label-resource'],['map-label-after-append','container-resource'],['map-label-final-append','container-resource'],['map-label-source','source-resource'],['map-label-font','font-resource'],['map-label-sprite','sprite-resource'],['map-label-container','container-resource']]){ const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseMapLabelLayer(state); },{kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,laterRepairTruck:{pixels:81,framebuffer:'same-canvas-after-map-labels'}},rendering:{active:'pixi-hybrid',layers:{aircraft:{owned:true},mapLabels:{owned:false,entries:0,spritesActive:0,textureRefs:0,resourceLimitFallback:{reason}}}}}); expect(failed.canvasFallback.order).toEqual(['draft-flag','draft-pick','draft-owner','draft-flag','draft-pick','draft-owner','garrison-count','garrison-count']); for(const value of Object.values(failed.canvasFallback.semanticPixels)) expect(value).toBeGreaterThan(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); expect(recovered.rendering.layers.mapLabels).toMatchObject({owned:true,entries:4,resourceLimitFallback:{reason:null}}); }
});

test('production renderPass label failure composites real Canvas labels and support actor above retained Pixi aircraft',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','production E10 fallback evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.productionMapLabelFailureProbe()); expect(result.failed).toMatchObject({active:'pixi-hybrid',layers:{aircraft:{owned:true},mapLabels:{owned:false,entries:0,spritesActive:0,resourceLimitFallback:{reason:'container-resource'}}}}); expect(result.recovered).toMatchObject({active:'pixi-hybrid',layers:{aircraft:{owned:true},mapLabels:{owned:true,resourceLimitFallback:{reason:null}}}}); expect(result.framebuffer).toBe('production-renderPass-composited-pixi-then-canvas'); expect(result.stackedBelow).toBe(true); expect(result.pixiIndices.aircraft).toBeLessThan(result.pixiIndices.mapLabels); expect(result.stageIndices.pixi).toBeLessThan(result.stageIndices.canvas); expect(result.canvasDraft.painted).toBeGreaterThan(100); expect(result.canvasGarrison.painted).toBeGreaterThan(20); expect(result.canvasRepairTruck.painted).toBeGreaterThan(20); expect(result.aircraft.painted).toBeGreaterThan(20); expect(result.repairTruck.painted).toBeGreaterThan(result.canvasRepairTruck.painted);
});

for(const cap of [
  {name:'entry',query:'&pixiMapLabelEntryCap=3',reason:'entry-cap'},
  {name:'label',query:'&pixiMapLabelLabelCap=7',reason:'label-cap'},
  {name:'char',query:'&pixiMapLabelCharCap=1',reason:'char-cap'},
  {name:'container',query:'&pixiMapLabelContainerCap=3',reason:'container-cap'},
  {name:'sprite',query:'&pixiMapLabelSpriteCap=7',reason:'sprite-cap'},
  {name:'texture',query:'&pixiMapLabelTextureCap=1',reason:'texture-cap'},
  {name:'source-byte',query:'&pixiMapLabelSourceByteCap=0',reason:'source-byte-cap'}
]) test(`map-label ${cap.name} cap rejects without truncation and uses uncapped Canvas`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E10 cap evidence runs in primary Chromium'); await start(page,cap.query); const state=await page.evaluate(fixture),failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{aircraft:{owned:true},mapLabels:{owned:false,entries:0,spritesActive:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.canvasFallback.pixels).toBeGreaterThan(0); expect(failed.canvasFallback.laterRepairTruck.pixels).toBe(81);
});

test('stable semantic keys survive reorder/remove and prerequisites recover',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E10 identity and prerequisite evidence run in primary Chromium'); await start(page); const state=await page.evaluate(fixture),churn=await page.evaluate(value=>window.__STATEFALL_TEST__.mapLabelIdentityChurn(value),state); expect(churn.first.slice(0,2).map(value=>value.key)).toEqual(['draft:0:1','draft:1:1']); expect(churn.reordered.slice(0,2).map(value=>value.key)).toEqual(['draft:1:1','draft:0:1']); expect(churn.restored.slice(0,2).map(value=>value.key)).toEqual(['draft:0:1','draft:1:1']); const duplicate=structuredClone(state); duplicate.draftPicks.push({...duplicate.draftPicks[0]}); const rejected=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),duplicate); expect(rejected.rendering.layers.mapLabels).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'invalid-key'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const prerequisite=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); expect(prerequisite.rendering.layers.mapLabels).toMatchObject({owned:false,resourceLimitFallback:{reason:'aircraft-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); expect(recovered.rendering.layers.mapLabels.owned).toBe(true);
});

test('text changes evict only zero-reference cached textures and reset/BFCache recreate cleanly',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E10 cache and lifecycle evidence run in primary Chromium'); await start(page,'&pixiMapLabelTextureCap=1'); const state=await page.evaluate(fixture); state.draftPicks=[]; state.areas[1].tiles=1; let previousDestroy=0; for(const troops of [1000,2500,5000,7500]){ state.areas[0].troops=troops; const result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state),layer=result.rendering.layers.mapLabels; expect(layer).toMatchObject({owned:true,entries:1,spritesActive:1,textureCount:1,textureRefs:1}); expect(layer.textureDestroyCount).toBeGreaterThanOrEqual(previousDestroy); previousDestroy=layer.textureDestroyCount; } expect(previousDestroy).toBeGreaterThan(0);
  await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))); await page.locator('.pixi-world').evaluate(element=>element.remove()); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(false); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recreated=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value),state); expect(recreated.rendering.layers.mapLabels).toMatchObject({owned:true,entries:1,spritesActive:1,textureCount:1,textureRefs:1}); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); expect(await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().layers.mapLabels)).toMatchObject({owned:false,entries:0,spritesActive:0,textureCount:0,sourceBytes:0,textureRefs:0});
});

test('continuous draft fade replaces old alpha rasters while stable garrison textures are reused',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E10 fade cache evidence runs in primary Chromium'); await start(page,'&pixiMapLabelTextureCap=3'); const state=await page.evaluate(fixture),stable=structuredClone(state); state.draftPicks=state.draftPicks.slice(0,1); state.garrisonEnabled=false; state.areas=[]; let prior=null; for(const now of [18000,18500,19000,19500,20000]){ state.now=now; const result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseMapLabelLayer(value),raster=api.mapLabelRasterEvidence(); return {layer:layer.rendering.layers.mapLabels,raster}; },state),alpha=Math.max(0,1-(now-18000)/7000); expect(result.layer).toMatchObject({owned:true,textureCount:3,textureRefs:3,spritesActive:3}); expect(result.raster.labels.every(value=>value.spriteAlpha===1&&value.effectiveAlpha===alpha)).toBe(true); if(prior){ expect(result.layer.textureAllocations-prior.textureAllocations).toBe(3); expect(result.layer.textureDestroyCount-prior.textureDestroyCount).toBe(3); } prior=result.layer; }
  stable.draftPicks=[]; const first=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value).rendering.layers.mapLabels,stable),second=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMapLabelLayer(value).rendering.layers.mapLabels,stable); expect(second.textureAllocations).toBe(first.textureAllocations); expect(second.textureDestroyCount).toBe(first.textureDestroyCount);
});

test('1800-frame text/owner/count/draft/cull/pan/DPR-stable churn stays bounded',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E10 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderMapLabelChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); for(const sample of result.resources){ expect(sample.textureCount).toBeLessThanOrEqual(4096); expect(sample.sourceBytes).toBeLessThanOrEqual(64*1024*1024); expect(sample.textureRefs).toBeGreaterThanOrEqual(0); } expect(result.resources.at(-1).containersCreated).toBeLessThanOrEqual(32); expect(result.resources.at(-1).spritesCreated).toBeLessThanOrEqual(80); expect(result.heapAssertion).toContain('advisory-only'); expect(result.gpuAssertion).toContain('unknown'); console.log(`pixi E10 labels churn: mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`);
});
