const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

const AIRCRAFT_SEMANTICS=['aircraft-patrol-ring','aircraft-silhouette','aircraft-hp','aircraft-silhouette','aircraft-silhouette'];
const AIRCRAFT_PRIMITIVES=['0:aircraft-patrol-ring:0','0:aircraft-silhouette:0','0:aircraft-silhouette:1','0:aircraft-silhouette:2','0:aircraft-silhouette:3','0:aircraft-silhouette:4','0:aircraft-silhouette:5','0:aircraft-hp:0','0:aircraft-hp:1','1:aircraft-silhouette:0','1:aircraft-silhouette:1','1:aircraft-silhouette:2','1:aircraft-silhouette:3','1:aircraft-silhouette:4','1:aircraft-silhouette:5','2:aircraft-silhouette:0','2:aircraft-silhouette:1','2:aircraft-silhouette:2','2:aircraft-silhouette:3','2:aircraft-silhouette:4','2:aircraft-silhouette:5','2:aircraft-silhouette:6','2:aircraft-silhouette:7','2:aircraft-silhouette:8','2:aircraft-silhouette:9','2:aircraft-silhouette:10','2:aircraft-silhouette:11'];
const AIRCRAFT_OPERATIONS=['0:aircraft-patrol-ring:0:stroke','0:aircraft-silhouette:0:fill','0:aircraft-silhouette:1:fill','0:aircraft-silhouette:1:stroke','0:aircraft-silhouette:2:fill','0:aircraft-silhouette:3:fill','0:aircraft-silhouette:4:fill','0:aircraft-silhouette:5:fill','0:aircraft-hp:0:fill','0:aircraft-hp:1:fill','1:aircraft-silhouette:0:fill','1:aircraft-silhouette:1:fill','1:aircraft-silhouette:1:stroke','1:aircraft-silhouette:2:fill','1:aircraft-silhouette:3:fill','1:aircraft-silhouette:4:fill','1:aircraft-silhouette:5:fill','2:aircraft-silhouette:0:fill','2:aircraft-silhouette:1:fill','2:aircraft-silhouette:2:fill','2:aircraft-silhouette:3:fill','2:aircraft-silhouette:3:stroke','2:aircraft-silhouette:4:fill','2:aircraft-silhouette:5:fill','2:aircraft-silhouette:5:stroke','2:aircraft-silhouette:6:fill','2:aircraft-silhouette:7:fill','2:aircraft-silhouette:7:stroke','2:aircraft-silhouette:8:fill','2:aircraft-silhouette:9:fill','2:aircraft-silhouette:10:fill','2:aircraft-silhouette:11:fill'];

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object');
  await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE9AIRCRAFT'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),at=(id,type,state,x,y,extra={})=>({id,type,state,...world(x,y),targetX:world(x+25,y).x,targetY:world(x,y).y,heading:extra.heading??0,hp:extra.hp??1,color:extra.color||'#d9485f',owned:!!extra.owned,visible:extra.visible!==false,hovered:!!extra.hovered,pull:extra.pull||0});
  return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},fighterPatrol:25,fighterHp:5,inheritedCanvasState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[2,3],lineDashOffset:4,lineWidth:1.5,strokeStyle:'#123456',fillStyle:'#654321'},aircraft:[
    at(9101,'fighter','patrol',320,260,{owned:true,visible:false,hovered:true,hp:2,heading:.2,color:'#d9485f'}),
    at(9102,'bomber','return',560,300,{pull:1,heading:1.1,color:'#33a06f'}),
    at(9103,'carrier','out',800,340,{heading:2.2,color:'#3f7bd9'}),
    at(9104,'fighter','return',1000,380,{visible:false,hp:5,color:'#d98b36'}),
    at(9105,'fighter','hangar',1100,420,{owned:true,hp:5,color:'#d9485f'})
  ]};
}

test('Pixi owns the exact aircraft block with interpolation-ready coordinates and Canvas handoff',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E9 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(JSON.stringify(state)).toBe(before); const layer=result.rendering.layers.aircraft;
  expect(layer).toMatchObject({owned:true,counts:{total:5,visible:3,hidden:1,skipped:1,fighter:1,bomber:1,carrier:1,patrolRings:1,hpPips:2},generatedTextures:{strategy:'vector-primitives',references:0,textures:0},canvasState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:4,lineWidth:2,strokeStyle:'rgba(191,230,255,.95)',fillStyle:'#ff9a9a'}});
  expect(layer.presentation.map(value=>[value.id,value.type,value.items])).toEqual([[9101,'fighter',['aircraft-patrol-ring','aircraft-silhouette','aircraft-hp']],[9102,'bomber',['aircraft-silhouette']],[9103,'carrier',['aircraft-silhouette']]]); expect(layer.presentation.map(value=>value.order)).toEqual([0,1,2]); expect(layer.presentation[1].pullScale).toBe(1.25); expect(layer.presentation[2].primitiveCounts).toEqual([{semantic:'aircraft-silhouette',count:12}]); expect(layer.presentation[0].screen).toEqual({x:320,y:260});
});

test('synthetic malformed stepped bomber rejects Pixi but direct Canvas fallback remains legacy-safe',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 malformed synthetic fallback runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.advance(1); let error=null; try{ api.renderRepeatedly(1); }catch(value){ error=String(value); } return {error,sources:api.aircraftSourceDiagnostics(),layer:api.rendererDiagnostics().layers.aircraft}; }); if(result.error) throw new Error(`${result.error}: ${JSON.stringify(result.sources)}`); expect(result.sources.some(value=>value.type==='bomber'&&Number.isNaN(value.x)&&Number.isNaN(value.y))).toBe(true); expect(result.layer).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'invalid-source'}});
});

test('isolated real Pixi Graphics rasterize every aircraft primitive at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'focused E9 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseAircraftLayer(value),before=api.rendererDiagnostics(),raster=api.aircraftRasterEvidence(); return {layer,before,raster,after:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable');
  expect(result.raster.order).toEqual(AIRCRAFT_SEMANTICS); expect(result.raster.primitiveOrder).toEqual(AIRCRAFT_PRIMITIVES); expect(result.raster.operationOrder).toEqual(AIRCRAFT_OPERATIONS); expect(result.raster.primitives.map(value=>value.key)).toEqual(AIRCRAFT_PRIMITIVES); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.combined.pixels).toBeGreaterThan(0); expect(result.raster.combined.colors).toBeGreaterThan(4);
  const byKey=Object.fromEntries(result.raster.primitives.map(value=>[value.key,value])); for(const key of AIRCRAFT_PRIMITIVES){ const primitive=byKey[key]; expect(primitive.pixels,`${key} pixels`).toBeGreaterThan(0); expect(primitive.bounds,`${key} bounds`).not.toBeNull(); }
  const contains=(key,x,y)=>{ const bounds=byKey[key].bounds; expect(bounds.left,`${key} left of ${x}`).toBeLessThan(x); expect(bounds.right,`${key} right of ${x}`).toBeGreaterThan(x); expect(bounds.top,`${key} above ${y}`).toBeLessThan(y); expect(bounds.bottom,`${key} below ${y}`).toBeGreaterThan(y); };
  contains('0:aircraft-silhouette:0',320,260); contains('1:aircraft-silhouette:0',560,300); contains('2:aircraft-silhouette:0',800,340); for(const key of AIRCRAFT_PRIMITIVES.filter(value=>value.startsWith('2:aircraft-silhouette:')&&value!=='2:aircraft-silhouette:0')){ const bounds=byKey[key].bounds; expect(bounds.left,`${key} near carrier`).toBeGreaterThan(770); expect(bounds.right,`${key} near carrier`).toBeLessThan(830); expect(bounds.top,`${key} near carrier`).toBeGreaterThan(310); expect(bounds.bottom,`${key} near carrier`).toBeLessThan(370); }
  expect(byKey['0:aircraft-patrol-ring:0'].bounds).toMatchObject({left:expect.any(Number),top:expect.any(Number),right:expect.any(Number),bottom:expect.any(Number)}); expect(byKey['0:aircraft-patrol-ring:0'].bounds.left).toBeLessThan(230); expect(byKey['0:aircraft-patrol-ring:0'].bounds.right).toBeGreaterThan(460);
  const expectedRgb={'0:aircraft-patrol-ring:0':[191,230,255],'0:aircraft-silhouette:1':[113,128,134],'0:aircraft-silhouette:2':[36,52,61],'0:aircraft-silhouette:4':[16,26,32],'0:aircraft-silhouette:5':[217,72,95],'0:aircraft-hp:0':[255,154,154],'0:aircraft-hp:1':[255,154,154],'1:aircraft-silhouette:1':[113,128,134],'1:aircraft-silhouette:2':[36,52,61],'1:aircraft-silhouette:4':[16,26,32],'1:aircraft-silhouette:5':[51,160,111],'2:aircraft-silhouette:3':[113,128,134],'2:aircraft-silhouette:4':[36,52,61],'2:aircraft-silhouette:5':[113,128,134],'2:aircraft-silhouette:6':[36,52,61],'2:aircraft-silhouette:7':[113,128,134],'2:aircraft-silhouette:8':[36,52,61],'2:aircraft-silhouette:10':[16,26,32],'2:aircraft-silhouette:11':[63,123,217]}; for(const [key,rgb] of Object.entries(expectedRgb)){ const colors=byKey[key].opaqueRgb.map(value=>value.split(',').map(Number)); expect(colors.some(value=>value.every((channel,index)=>Math.abs(channel-rgb[index])<=3)),`${key} distinctive color`).toBe(true); }
  expect(result.raster.restored).toBe(true); for(const key of ['textureCount','graphicsCount','containerCount']) expect(result.after[key],`${key} restored`).toBe(result.before[key]);
});

test('aircraft stays above missiles and real Air-list hover drives the patrol highlight',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 overlap and input alignment run in primary Chromium'); await start(page); const overlap=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; return fixtureForOverlap(); function fixtureForOverlap(){ const base=({camera:api.snapshot().camera}),x=(520-base.camera.x)/base.camera.scale,y=(300-base.camera.y)/base.camera.scale,tx=Math.floor(x)+.5,ty=Math.floor(y)+.5,tile=Math.floor(ty)*720+Math.floor(tx),common={camera:{x:base.camera.x,y:base.camera.y,scale:base.camera.scale},viewport:{width:innerWidth,height:innerHeight}},cx=common.camera.x+tx*common.camera.scale,cy=common.camera.y+ty*common.camera.scale,samples=[]; for(let dy=-4;dy<=4;dy++) for(let dx=-8;dx<=8;dx++) samples.push({x:cx+dx,y:cy+dy}); api.exerciseMissileLayer({...common,mapWidth:720,nukeRadius:4,cruiseRadius:3,now:0,reducedMotion:false,inheritedStrokeState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0},missiles:[{source:{},owner:0,owned:true,visible:true,from:tile,t:tile,age:2,flight:20,cruise:true}]}); const missile=api.missileRasterEvidence(samples); api.exerciseAircraftLayer({...common,fighterPatrol:25,fighterHp:5,inheritedCanvasState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0,lineWidth:1,strokeStyle:'#fff',fillStyle:'#fff'},aircraft:[{id:9901,type:'fighter',state:'return',x:tx,y:ty,heading:0,hp:5,color:'#00ff66',owned:true,visible:true,hovered:false}]}); return {missile,aircraft:api.aircraftRasterEvidence(samples)}; } }); const index=overlap.missile.combined.samples.findIndex((sample,i)=>sample.rgba[3]>0&&overlap.aircraft.combined.samples[i].rgba[3]>0); expect(index).toBeGreaterThanOrEqual(0); expect(overlap.aircraft.stacked.samples[index].rgba).toEqual(overlap.aircraft.combined.samples[index].rgba);
  await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const rows=page.locator('#airList [data-air]'); let aligned=false; for(let i=0;i<await rows.count();i++){ await rows.nth(i).hover(); await page.evaluate(()=>window.__STATEFALL_TEST__.renderRepeatedly(1)); const status=await page.evaluate(()=>window.__STATEFALL_TEST__.aircraftHoverStatus()),entry=status.renderer.presentation.find(value=>value.id===status.id&&value.items.includes('aircraft-patrol-ring')); if(entry){ const ring=entry.styles.find(value=>value.stroke==='rgba(191,230,255,.95)'); if(ring?.width===2){ aligned=true; break; } } } expect(aligned).toBe(true); await page.locator('#airList').hover({position:{x:2,y:2}});
});

test('aircraft resource failures withdraw all aircraft, directly Canvas-paint, and retry cleanly',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E9 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture);
  for(const [kind,reason] of [['aircraft-graphics-after-paint','graphics-resource'],['aircraft-container-after-append','container-resource']]){ const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseAircraftLayer(state); },{kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,laterDraft:{pixels:81,framebuffer:'same-canvas-after-aircraft'}},rendering:{layers:{missiles:{owned:true},aircraft:{owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason}}}}}); for(const value of Object.values(failed.canvasFallback.semanticPixels)) expect(value).toBeGreaterThan(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(recovered.rendering.layers.aircraft).toMatchObject({owned:true,entries:3,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.aircraft.resources.every(value=>value.childCount===value.children.length)).toBe(true); }
});

for(const cap of [
  {name:'entry',query:'&pixiAircraftEntryCap=4',reason:'entry-cap',recover:state=>{ state.aircraft=state.aircraft.slice(0,4); },entries:3},
  {name:'primitive',query:'&pixiAircraftPrimitiveCap=6',reason:'primitive-cap',recover:state=>{ state.aircraft=[state.aircraft[1]]; },entries:1},
  {name:'segment',query:'&pixiAircraftSegmentCap=6',reason:'segment-cap',recover:state=>{ state.aircraft=[state.aircraft[1]]; },entries:1},
  {name:'container',query:'&pixiAircraftContainerCap=2',reason:'container-cap',recover:state=>{ state.aircraft=state.aircraft.slice(0,2); },entries:2},
  {name:'Graphics',query:'&pixiAircraftGraphicsCap=4',reason:'graphics-cap',recover:state=>{ state.aircraft=[state.aircraft[0],state.aircraft[2]]; },entries:2}
]) test(`aircraft ${cap.name} cap rejects without truncation, uses uncapped Canvas, and recovers`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E9 cap evidence runs in primary Chromium'); await start(page,cap.query); const state=await page.evaluate(fixture),failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{missiles:{owned:true},aircraft:{owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.canvasFallback.order).toEqual(AIRCRAFT_SEMANTICS); expect(failed.canvasFallback.pixels).toBeGreaterThan(0); for(const semantic of ['aircraft-patrol-ring','aircraft-silhouette','aircraft-hp']) expect(failed.canvasFallback.semanticPixels[semantic],semantic).toBeGreaterThan(0); expect(failed.canvasFallback.laterDraft.pixels).toBeGreaterThan(0);
  cap.recover(state); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(recovered.rendering.layers.aircraft).toMatchObject({owned:true,entries:cap.entries,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.aircraft.resources.every(value=>value.childCount===value.children.length)).toBe(true);
});

test('stable positive aircraft IDs survive reorder/remove/re-add and reject duplicate or missing IDs',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 identity evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),churn=await page.evaluate(value=>window.__STATEFALL_TEST__.aircraftIdentityChurn(value),state); expect(JSON.stringify(state)).toBe(before); expect(churn.first.map(value=>value.id)).toEqual([9101,9102,9103]); expect(churn.reordered.map(value=>value.id)).toEqual([9103,9102,9101]); expect(churn.restored.map(value=>value.id)).toEqual([9101,9102,9103]); for(const mutate of [value=>value.aircraft.push({...value.aircraft[0]}),value=>{ value.aircraft[0].id=0; }]){ const copy=structuredClone(state); mutate(copy); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),copy); expect(failed.rendering.layers.aircraft).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'invalid-id'}}); }
});

test('aircraft ownership requires every prerequisite through missiles',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 prerequisite evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(failed.rendering.layers.aircraft).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'structures-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(recovered.rendering.layers).toMatchObject({missiles:{owned:true},aircraft:{owned:true}});
});

test('aircraft container and Graphics constructor failures leave no phantom resources',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 constructor evidence runs in primary Chromium'); for(const [kind,reason] of [['aircraft-container','container-resource'],['aircraft-graphics','graphics-resource']]){ await start(page); const state=await page.evaluate(fixture); for(let i=0;i<8;i++) state.aircraft.push({...state.aircraft[1],id:9200+i,x:state.aircraft[1].x+i*8}); const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseAircraftLayer(state); },{kind,state}); expect(failed.rendering.layers.aircraft).toMatchObject({owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason}}); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); expect(recovered.rendering.layers.aircraft).toMatchObject({owned:true,entries:11,resourceLimitFallback:{reason:null}}); }
});

test('fatal final submission replays aircraft once with omission-sensitive primitives',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','same-frame E9 replay evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.finalSubmissionFailureProbe()),fullyOverlapped=new Set(['0:aircraft-silhouette:1:fill','0:aircraft-silhouette:2:fill','0:aircraft-silhouette:3:fill','0:aircraft-silhouette:5:fill','1:aircraft-silhouette:1:fill','1:aircraft-silhouette:2:fill','1:aircraft-silhouette:5:fill','2:aircraft-silhouette:2:fill','2:aircraft-silhouette:3:fill','2:aircraft-silhouette:4:fill','2:aircraft-silhouette:5:fill','2:aircraft-silhouette:6:fill','2:aircraft-silhouette:7:fill','2:aircraft-silhouette:8:fill','2:aircraft-silhouette:9:fill','2:aircraft-silhouette:10:fill','2:aircraft-silhouette:11:fill']),covered=new Set([...fullyOverlapped,'0:aircraft-silhouette:4:fill','2:aircraft-silhouette:0:fill','2:aircraft-silhouette:1:fill']); expect(result.rendering).toMatchObject({active:'canvas',fallbackCleanup:{contextState:'destroyed',layers:{missiles:{owned:false},aircraft:{owned:false,entries:0}}}}); expect(result.rendering.fallbackReason).toContain('pixi-render-failed: final-app-render'); expect(result.aircraftReplay.primitiveOrder).toEqual(AIRCRAFT_OPERATIONS); expect(result.aircraftReplay.totalDifferentialPixels).toBeGreaterThan(0); for(const key of AIRCRAFT_OPERATIONS){ const evidence=result.aircraftReplay.primitiveEvidence[key],overlap=fullyOverlapped.has(key),hidden=covered.has(key); expect(evidence.framebuffer).toBe('fatal-canvas-replay'); expect(evidence.maskPixels,`${key} mask`).toBeGreaterThan(0); if(overlap) expect(evidence.exclusiveMaskPixels,`${key} overlap`).toBe(0); else expect(evidence.exclusiveMaskPixels,`${key} exclusive`).toBeGreaterThan(0); if(hidden) expect(evidence.differentialPixels,`${key} covered differential`).toBe(0); else { expect(evidence.differentialPixels,`${key} differential`).toBeGreaterThan(0); expect(evidence.colors.length,`${key} colors`).toBeGreaterThan(0); expect(evidence.sample.actual,`${key} framebuffer differential`).not.toEqual(evidence.sample.withoutAircraft); } expect(Object.keys(evidence.crossSatisfiedBy)).toHaveLength(AIRCRAFT_OPERATIONS.length-1); expect(result.aircraftReplay.omissionSensitivity[key].lostPixels).toBe(evidence.differentialPixels); expect(result.aircraftReplay.omissionSensitivity[key].withoutMask).toBe(result.aircraftReplay.totalDifferentialPixels-evidence.differentialPixels); } expect(Object.keys(result.aircraftReplay.exclusiveMaskOverlaps)).toHaveLength(AIRCRAFT_OPERATIONS.length*(AIRCRAFT_OPERATIONS.length-1)/2); expect(result.after.lifecycle.callbacks).toBe(result.before.lifecycle.callbacks); expect(result.after.lifecycle.renders).toBe(result.before.lifecycle.renders+1); expect(result.visualShots).toEqual({age:1,count:1,pruned:true});
});

test('active aircraft resources recreate after BFCache loss and clean up on context loss',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E9 lifecycle evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),owned=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseAircraftLayer(value),state); test.skip(!owned.owned,'Pixi WebGL renderer unavailable'); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))); await page.locator('.pixi-world').evaluate(element=>element.remove()); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(false); await page.evaluate(()=>window.__STATEFALL_TEST__.renderRepeatedly(1)); expect(await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics())).toMatchObject({active:'pixi-hybrid',layers:{aircraft:{owned:true}}}); const supported=await page.locator('.pixi-world').evaluate(canvas=>!!(canvas.getContext('webgl2')||canvas.getContext('webgl'))?.getExtension('WEBGL_lose_context')); test.skip(!supported,'WEBGL_lose_context unavailable'); await page.locator('.pixi-world').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).getExtension('WEBGL_lose_context').loseContext()); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().active)).toBe('canvas'); expect(await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics())).toMatchObject({fallbackCleanup:{layers:{aircraft:{owned:false,entries:0}}}});
});

test('1800-frame type/state/color/HP/heading/pull/patrol/fog/cull/reorder churn plateaus',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E9 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderAircraftChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); for(const key of ['containersCreated','graphicsCreated']) expect(new Set(result.resources.slice(-6).map(value=>value[key])).size,`${key} plateaus`).toBe(1); expect(result.resources.every(value=>value.textureReferences===0)).toBe(true); expect(result.heapAssertion).toContain('advisory-only'); expect(result.gpuAssertion).toContain('unknown'); console.log(`pixi E9 aircraft churn: mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`);
});
