const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto('/index.html?browserTest=1&renderer=pixi',{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object');
  await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE7PROJECTILES'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),at=(x,y)=>{ const p=world(x,y); return [p.x,p.y]; },p=(x,y)=>world(x,y),tor=p(220,260),aam=p(400,260),barrage=p(580,260),artillery=p(760,260),ordinary=p(940,260);
  return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},inheritedStrokeState:{lineJoin:'miter',lineCap:'butt'},shells:[
    {...tor,torpedo:true,trail:[at(180,260),at(195,260),at(210,260)]},
    {...aam,kind:'aam',trail:[at(360,260),at(380,260)]},
    {...barrage,tx:barrage.x+10,ty:barrage.y,arc:true,missile:true,tot:30,rise:17,delay:2,trail:[[...at(520,280),0],[...at(545,275),4],[...at(565,268),7]]},
    {...artillery,tx:artillery.x+10,ty:artillery.y,arc:true,tot:30,rise:14,delay:0,trail:[[...at(720,270),0],[...at(745,265),4]]},
    {...ordinary,kind:'gun',trail:[at(900,260),at(920,260)]}
  ],visualShots:[{source:{name:'shot'},...Object.fromEntries([['x0',at(212,260)[0]],['y0',at(212,260)[1]],['x1',at(228,260)[0]],['y1',at(228,260)[1]]]),col:'#ff00ff',age:1,alpha:5/6,lifetime:6}]};
}

function expectSingleReplay(result){
  expect(result.after.checkpoint).toEqual(result.before.checkpoint); expect(result.after.ships).toEqual(result.before.ships); expect(result.after.shells).toEqual(result.before.shells); expect(result.visualShots).toEqual({age:1,count:1,pruned:true});
  expect(result.replay.synchronous).toBe(true); expect(result.after.lifecycle.callbacks).toBe(result.before.lifecycle.callbacks); expect(result.after.lifecycle.renders).toBe(result.before.lifecycle.renders+1); expect(result.after.lifecycle.rafPending).toBe(result.before.lifecycle.rafPending);
  for(const name of ['flashes','floaters','sparks','puffs','wrecks','frags','tracers','scorches']){ expect(result.after.effects[name]).toHaveLength(1); expect(result.after.effects[name][0].age,`${name} age`).toBe(result.before.effects[name][0].age+1); }
  expect(result.after.effects.puffs[0]).toMatchObject({x:result.before.effects.puffs[0].x+.1,y:result.before.effects.puffs[0].y-.05,r:result.before.effects.puffs[0].r+.06}); expect(result.after.effects.nukeAlerts[0].age).toBe(result.before.effects.nukeAlerts[0].age+1); expect(result.after.effects.badges).toEqual(result.before.effects.badges);
  expect(result.after.labels).toEqual(result.before.labels); expect(result.after.banner.age).toBe(result.before.banner.age+1); expect(result.after.credits).toEqual(result.before.credits); expect(result.after.audio).toEqual(result.before.audio); expect(result.after.input).toEqual(result.before.input); expect(result.after.interpolation).toEqual(result.before.interpolation);
  const expected=['torpedo-foam-trail:0:stroke','torpedo-foam-trail:1:stroke','torpedo-foam-trail:2:stroke','torpedo-foam-trail:3:stroke','torpedo-foam-points:0:fill','torpedo-body:0:fill','torpedo-body:0:stroke','aam-trail:0:stroke','aam-body:0:fill','aam-body:1:fill','barrage-trail:0:stroke','barrage-rocket:0:fill','barrage-rocket:1:fill','barrage-rocket:2:fill','artillery-shell:0:fill','artillery-ground-tether:0:stroke','gun-shell-trail:0:stroke','gun-shell-body:0:fill','visual-gun-line:0:stroke']; expect(result.replay.primitiveOrder).toEqual(expected); expect(expected.filter(key=>key.startsWith('torpedo-foam-points:'))).toHaveLength(1);
  for(const key of expected){ const evidence=result.replay.primitiveEvidence[key]; expect(evidence.framebuffer,`${key} source`).toBe('fatal-canvas-replay'); expect(evidence.maskPixels,`${key} mask pixels`).toBeGreaterThan(0); expect(evidence.exclusiveMaskPixels,`${key} exclusive mask pixels`).toBeGreaterThan(0); expect(evidence.differentialPixels,`${key} fatal replay differential pixels`).toBeGreaterThan(0); expect(evidence.colors.length,`${key} differential colors`).toBeGreaterThan(0); expect(evidence.sample,`${key} exclusive pixel location`).toMatchObject({x:expect.any(Number),y:expect.any(Number),actual:expect.any(Array),withoutProjectiles:expect.any(Array)}); expect(evidence.sample.actual,`${key} changes the full replay framebuffer`).not.toEqual(evidence.sample.withoutProjectiles); expect(Object.keys(evidence.crossSatisfiedBy),`${key} checked against every other primitive`).toHaveLength(expected.length-1); expect(Object.values(evidence.crossSatisfiedBy).every(value=>value===0),`${key} cannot cross-satisfy another exclusive mask`).toBe(true); expect(result.replay.omissionSensitivity[key].lostPixels,`${key} mask-removal sensitivity`).toBe(evidence.differentialPixels); expect(result.replay.omissionSensitivity[key].withoutMask,`${key} removal recomputes total evidence`).toBe(result.replay.totalDifferentialPixels-evidence.differentialPixels); }
  expect(Object.keys(result.replay.exclusiveMaskOverlaps)).toHaveLength(expected.length*(expected.length-1)/2); expect(Object.values(result.replay.exclusiveMaskOverlaps).every(value=>value===0),'all pairwise exclusive-mask cross-satisfaction is zero').toBe(true);
  for(const name of ['missile','aircraft']){ expect(result.replay.later[name],`${name} retained`).not.toBeNull(); expect(result.replay.later[name].pixels,`${name} pixels`).toBeGreaterThan(0); expect(result.replay.later[name].colors,`${name} colors`).toBeGreaterThan(1); expect(result.replay.later[name].changed,`${name} unchanged from no-projectile baseline`).toBe(0); }
}

test('Pixi owns every E7 variant in exact category and primitive order',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E7 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseProjectileLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); const layer=result.rendering.layers.projectiles;
  expect(layer).toMatchObject({owned:true,counts:{shells:{total:5,visible:5,hidden:0},visualShots:{total:1,visible:1}},canvasStrokeState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0}});
  expect(layer.presentation.map(value=>value.variant)).toEqual(['torpedo','aam','barrage','artillery','ordinary','visual-shot']); expect(layer.presentation.map(value=>value.items)).toEqual([['torpedo-foam-trail','torpedo-foam-points','torpedo-body'],['aam-trail','aam-body'],['barrage-trail','barrage-rocket'],['artillery-shell','artillery-ground-tether'],['gun-shell-trail','gun-shell-body'],['visual-gun-line']]); expect(layer.resources.map(value=>value.variant)).toEqual(layer.presentation.map(value=>value.variant)); expect(layer.presentation[3].styles.find(value=>value.dash)).toMatchObject({dash:[2,4],cap:'round',join:'miter'});
});

test('isolated Pixi Graphics rasterize every E7 primitive and preserve the separate intentional overlap order fixture',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'focused E7 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture); const result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseProjectileLayer(value),before=api.rendererDiagnostics(),raster=api.projectileRasterEvidence([{x:220,y:260}]); return {layer,before,raster,diagnostics:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable');
  const expected=['torpedo-foam-trail','torpedo-foam-points','torpedo-body','aam-trail','aam-body','barrage-trail','barrage-rocket','artillery-shell','artillery-ground-tether','gun-shell-trail','gun-shell-body','visual-gun-line']; expect(result.raster.order).toEqual(expected); expect(result.raster.resolution).toBe(page.viewportSize()?await page.evaluate(()=>devicePixelRatio):result.raster.resolution); expect(result.raster.combined.pixels).toBeGreaterThan(0); expect(result.raster.combined.colors).toBeGreaterThan(8);
  for(const semantic of expected){ const evidence=result.raster.semantics[semantic]; expect(evidence,`${semantic} extracted`).toBeTruthy(); expect(evidence.pixels,`${semantic} raster pixels`).toBeGreaterThan(0); expect(evidence.colors,`${semantic} distinctive pixels`).toBeGreaterThan(0); }
  const centers={torpedo:[220,260],aam:[400,260],barrage:[580,216],artillery:[760,224],ordinary:[940,260]}; for(const [variant,[x,y]] of Object.entries(centers)){ const semantics={torpedo:'torpedo-body',aam:'aam-body',barrage:'barrage-rocket',artillery:'artillery-shell',ordinary:'gun-shell-body'},bounds=result.raster.semantics[semantics[variant]].bounds; expect(bounds.left,`${variant} left`).toBeLessThan(x+8); expect(bounds.right,`${variant} right`).toBeGreaterThan(x-8); expect(bounds.top,`${variant} top`).toBeLessThan(y+8); expect(bounds.bottom,`${variant} bottom`).toBeGreaterThan(y-8); }
  const tether=result.raster.semantics['artillery-ground-tether'].bounds; expect(tether.bottom-tether.top).toBeGreaterThan(2); expect(result.raster.restored).toBe(true); expect(result.diagnostics.layers.projectiles.owned).toBe(true); for(const key of ['textureCount','graphicsCount','containerCount']) expect(result.diagnostics[key],`${key} unchanged by extraction`).toBe(result.before[key]);
  const overlap=result.raster.combined.samples[0].rgba; expect(overlap[0]).toBeGreaterThan(200); expect(overlap[1]).toBeLessThan(40); expect(overlap[2]).toBeGreaterThan(200); expect(overlap[3]).toBeGreaterThan(150);
});

test('projectile failures withdraw the complete layer and recover without live-slot ghosts',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E7 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture);
  for(const failure of [{kind:'projectile-graphics-after-paint',reason:'graphics-resource'},{kind:'projectile-container-after-append',reason:'container-resource'}]){ const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseProjectileLayer(state); },{kind:failure.kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,state:{globalAlpha:1,lineJoin:'miter',lineCap:'round',lineDash:[],lineDashOffset:0}},rendering:{layers:{warships:{owned:true},projectiles:{owned:false,entries:0,resourceLimitFallback:{reason:failure.reason}}}}}); expect(failed.canvasFallback.order).toEqual(['torpedo-foam-trail','torpedo-foam-points','torpedo-body','aam-trail','aam-body','barrage-trail','barrage-rocket','artillery-shell','artillery-ground-tether','gun-shell-trail','gun-shell-body','visual-gun-line']); expect(failed.canvasFallback.semanticPixels).toHaveProperty('artillery-ground-tether'); for(const [semantic,pixels] of Object.entries(failed.canvasFallback.semanticPixels)) if(semantic!=='artillery-ground-tether') expect(pixels,`${semantic} Canvas pixels`).toBeGreaterThan(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseProjectileLayer(value),state); expect(recovered.rendering.layers.projectiles).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.projectiles.resources.every(value=>value.childCount===value.children.length)).toBe(true); }
});

test('fatal final submission replays the complete frame on Canvas without another RAF or presentation advance',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','same-frame submission failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.finalSubmissionFailureProbe());
  expect(result.rendering).toMatchObject({active:'canvas',fallbackCleanup:{contextState:'destroyed',layers:{structures:{owned:false},navalLogistics:{owned:false},warships:{owned:false},projectiles:{owned:false}}}}); expect(result.rendering.fallbackReason).toContain('pixi-render-failed: final-app-render'); expect(result.rendering.fallbackReason.length).toBeLessThanOrEqual(160);
  expectSingleReplay(result);
  const continued=await page.evaluate(()=>{ window.__STATEFALL_TEST__.renderRepeatedly(2); return window.__STATEFALL_TEST__.rendererDiagnostics(); }); expect(continued.active).toBe('canvas'); expect(continued.fallbackReason).toContain('final-app-render');
});

test('fatal world-layer update failure uses the same bounded full-frame Canvas replay',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','same-frame update failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.finalSubmissionFailureProbe('world-layer-update'));
  expect(result.rendering).toMatchObject({active:'canvas',fallbackCleanup:{contextState:'destroyed'}}); expect(result.rendering.fallbackReason).toContain('pixi-world-layer-failed: world-layer-update'); expectSingleReplay(result);
});

test('visual-shot presentation ages exactly once and expires on the sixth displayed frame',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','presentation cadence evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__,source={x0:1,y0:2,x1:3,y1:4,col:'#fff',age:4},first=api.visualShotPresentationFrames([source],1),second=api.visualShotPresentationFrames(first.current,1); return {source,first,second}; }); expect(result.source.age).toBe(4); expect(result.first.descriptors[0]).toMatchObject({age:5,lifetime:6}); expect(result.first.current).toHaveLength(1); expect(result.second.descriptors[0]).toMatchObject({age:6,alpha:0,lifetime:6}); expect(result.second.current).toHaveLength(0);
});

test('Pixi failure falls back without double-aging visual shots',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','fallback cadence evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.projectileFallbackVisualShotProbe()); expect(result).toMatchObject({age:1,count:1,layer:{owned:false,entries:0,resourceLimitFallback:{reason:'graphics-resource'}}});
});

test('projectile ownership requires the complete E4-E6 prerequisite chain',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','dependency evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseProjectileLayer(value),state); expect(failed.rendering.layers.projectiles).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'structures-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseProjectileLayer(value),state); expect(recovered.rendering.layers).toMatchObject({structures:{owned:true},navalLogistics:{owned:true},warships:{owned:true},projectiles:{owned:true}});
});

test('projectile fixture remains CSS-pixel aligned at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!testInfo.project.name.startsWith('chromium-desktop-scale-'),'E7 DPR evidence runs in desktop-scale projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseProjectileLayer(value); return {layer,raster:api.projectileRasterEvidence()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable'); expect(result.layer.rendering.layers.projectiles).toMatchObject({owned:true,counts:{shells:{visible:5},visualShots:{visible:1}}}); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.semantics['torpedo-body'].bounds).toMatchObject({left:expect.any(Number),right:expect.any(Number)}); expect(result.raster.semantics['visual-gun-line'].pixels).toBeGreaterThan(0);
});

test('1800-frame variant, trail, fog, cull, reorder, and create-remove churn plateaus',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E7 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderProjectileChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); for(const key of ['containersCreated','graphicsCreated']) expect(new Set(result.resources.slice(-6).map(value=>value[key])).size,`${key} plateaus`).toBe(1); expect(result.heapAssertion).toContain('advisory-only'); expect(result.gpuAssertion).toContain('unknown'); console.log(`pixi E7 projectile churn (${result.measurement}): mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms; heap ${result.heapAssertion}; GPU ${result.gpuAssertion}`);
});
