const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

const SHIP_INVENTORY=[['warship',['fs','f','f','s','f','s'],['polygon','polygon','polygon','line','polygon','circle']],['privateer',['fs','f','f','s'],['polygon','polygon','polygon','circle']],['sub',['fs','f','s'],['polygon','polygon','circle']],['hunter',['fs','f','s','s'],['polygon','polygon','polyline','circle']],['rship',['fs','f','s','s','s'],['polygon','polygon','polyline','line','circle']],['scout',['fs','f','s'],['polygon','polygon','circle']],['cruiser',['fs','f','f','f','f','f','s','s','s'],['polygon','polygon','polygon','polygon','polygon','polygon','line','line','circle']],['battleship',['fs','f','f','f','f','s','s','s','s','s'],['polygon','polygon','polygon','polygon','polygon','line','line','line','line','circle']],['trader',['fs','f','f','s'],['polygon','polygon','polygon','circle']],['transport',['fs','f','f','s'],['polygon','polygon','polygon','circle']]];
const EFFECT_INVENTORY=[['scorches',0,'scorch',['f'],['circle']],['sparks',0,'spark',['f'],['rect']],['puffs',0,'puff',['f'],['circle']],['fragments',0,'fragment',['s'],['line']],['fragments',1,'bomb',['f'],['circle']],['tracers',0,'tracer',['s'],['line']],...SHIP_INVENTORY.map(([cls,operations,kinds],order)=>['wrecks',order,'ship-wreck',operations,kinds,cls]),['wrecks',10,'air-wreck',['f'],['polygon'],'fighter'],['wrecks',11,'air-wreck',['f'],['polygon'],'bomber'],['wrecks',12,'air-wreck',['f'],['polygon'],'carrier'],['wrecks',13,'dome-wreck',['s'],['circle'],null],['flashes',0,'flash',['f'],['circle']]];
const GLOBAL_EFFECT_PRIMITIVES=EFFECT_INVENTORY.flatMap(([category,order,semantic,operations])=>operations.map((_,index)=>`${category}:${order}:0:${semantic}:${index}`));
const GLOBAL_EFFECT_OPERATIONS=EFFECT_INVENTORY.flatMap(([category,order,semantic,operations])=>operations.flatMap((marks,index)=>[...marks].map(mark=>`${category}:${order}:0:${semantic}:${index}:${mark==='f'?'fill':'stroke'}`)));
const GLOBAL_EFFECT_KINDS=EFFECT_INVENTORY.flatMap(value=>value[4]);
const GLOBAL_EFFECT_PRESENTATION=EFFECT_INVENTORY.map(([category,,variant,,,cls])=>[category,variant,cls??null]);
const RING='rgba(230,240,255,0.44999999999999996)',SHIP_STYLE_INVENTORY={
  warship:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],['#e8ecef',null,.75],[null,'#e8ecef',.75],['#0f1a26',null,.75],[null,RING,1]],
  privateer:[['#3a2f2a','#3f7bd9',.75],['#e8ecef',null,.75],['#111',null,.75],[null,RING,1]],
  sub:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],[null,RING,1]],hunter:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],[null,'#e8ecef',.75],[null,RING,1]],
  rship:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],[null,'#e8ecef',.75],[null,'#e8ecef',.75],[null,RING,1]],scout:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],[null,RING,1]],
  cruiser:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],['#0f1a26',null,.75],['#0f1a26',null,.75],['#0f1a26',null,.75],['#0f1a26',null,.75],[null,'#e8ecef',.75],[null,'#e8ecef',.75],[null,RING,1]],
  battleship:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],['#e8ecef',null,.75],['#0f1a26',null,.75],['#0f1a26',null,.75],[null,'#e8ecef',.75],[null,'#e8ecef',.75],[null,'#e8ecef',.75],[null,'#e8ecef',.75],[null,RING,1]],
  trader:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],['#e8ecef',null,.75],[null,RING,1]],transport:[['#3f7bd9','#fff',.75],['#e8ecef',null,.75],['#e8ecef',null,.75],[null,RING,1]]
};
const GLOBAL_EFFECT_STYLES=[['rgba(10,8,6,0.225)',null,1],['#fff',null,.5],['rgba(70,70,70,0.3)',null,1],[null,'#ffd27a',.5],['#ffffff',null,.5],[null,'rgba(255,240,200,0.3888888888888889)',1],...SHIP_INVENTORY.flatMap(([cls])=>SHIP_STYLE_INVENTORY[cls]),['#d9485f',null,.6],['#d9485f',null,.6],['#d9485f',null,.6],[null,'rgba(150,220,255,0.48)',1],['#ff3344',null,.6]];

async function start(page,extra='',fog=false){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE13GLOBALEFFECTS'); await page.locator('#countrySel').selectOption('0'); if(fog) await page.locator('#fogOn').check(); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); api.renderRepeatedly(1); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),source=()=>({}),ships=['warship','privateer','sub','hunter','rship','scout','cruiser','battleship','trader','transport'],air=['fighter','bomber','carrier']; return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},inheritedCanvasState:{globalAlpha:1,lineJoin:'bevel',lineCap:'square',lineDash:[],lineDashOffset:0,lineWidth:3,strokeStyle:'rgba(0,0,0,.6)',fillStyle:'#ff3344',font:'bold 16px "Segoe UI",system-ui,sans-serif',textAlign:'center',textBaseline:'alphabetic'},scorches:[{source:source(),...world(80,100),r:5,age:900,visible:true}],sparks:[{source:source(),...world(150,100),age:3}],puffs:[{source:source(),...world(220,100),r:5,age:10,life:25,color:'70,70,70',visible:true}],fragments:[{source:source(),...world(290,100),vx:2,vy:1,age:10,life:20,color:'#ffd27a',dud:false,bomb:false},{source:source(),...world(360,100),vx:0,vy:0,age:10,life:20,color:'#ffffff',dud:false,bomb:true}],tracers:[{source:source(),x0:world(420,100).x,y0:world(420,100).y,x1:world(470,100).x,y1:world(470,100).y,age:4,color:'255,240,200'}],wrecks:[...ships.map((cls,index)=>({source:source(),kind:'ship',...world(100+(index%5)*210,230+Math.floor(index/5)*130),age:10,cls,heading:.17+index*.03,spin:.02,color:'#3f7bd9',visible:true})),...air.map((cls,index)=>({source:source(),kind:'air',...world(250+index*220,500),age:12,cls,heading:.35+index*.1,spin:0,color:'#d9485f',visible:true})),{source:source(),kind:'dome',...world(910,500),r:12,age:10,heading:0,spin:0,color:'#fff',visible:true}],flashes:[{source:source(),...world(1050,100),r:9,age:10,color:'#ff3344'}]};
}

test('Pixi owns the exact independently inventoried seven-category block and all legacy wreck classes',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','focused E13 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseGlobalEffectsLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(JSON.stringify(state)).toBe(before); const layer=result.rendering.layers.globalEffects; expect(layer).toMatchObject({owned:true,counts:{scorches:1,sparks:1,puffs:1,fragments:2,tracers:1,wrecks:14,flashes:1,total:21},primitiveCount:63,quality:{requested:'high',effective:'high'},reducedMotion:false,generatedTextures:{strategy:'vector-primitives',references:0,textures:0},canvasState:{globalAlpha:1,fillStyle:'#ff3344'}}); expect(layer.presentation.map(value=>[value.category,value.variant,value.cls])).toEqual(GLOBAL_EFFECT_PRESENTATION); expect(layer.presentation.flatMap(value=>value.primitiveCounts.map(item=>item.count))).toEqual(EFFECT_INVENTORY.map(value=>value[3].length)); expect(layer.order.at(-1)).toBe('canvas-nation-labels-and-later'); expect(result.checkpoint.tick).toBe(await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().tick)); });

test('every production drawPrimitive matches direct Canvas at DPR 1, 1.5, and 2',async({page},testInfo)=>{ test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E13 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseGlobalEffectsLayer(value),before=api.rendererDiagnostics(),raster=api.globalEffectsRasterEvidence(); return {layer,before,raster,after:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable'); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.primitiveOrder).toEqual(GLOBAL_EFFECT_PRIMITIVES); expect(result.raster.operationOrder).toEqual(GLOBAL_EFFECT_OPERATIONS); expect(result.raster.primitives.map(value=>value.key)).toEqual(GLOBAL_EFFECT_PRIMITIVES); expect(result.raster.primitives.map(value=>value.kind)).toEqual(GLOBAL_EFFECT_KINDS); expect(result.raster.primitives.map(value=>[value.fill,value.stroke,value.alpha])).toEqual(GLOBAL_EFFECT_STYLES); expect(result.raster.primitives).toHaveLength(63); expect(result.raster.exclusiveMaskPixels).toBeGreaterThan(0); expect(result.raster.stageIndices.floatingText).toBeLessThan(result.raster.stageIndices.globalEffects); for(const primitive of result.raster.primitives){ expect(primitive.pixels,`${primitive.key} Pixi pixels`).toBeGreaterThan(0); expect(primitive.exclusivePixels,`${primitive.key} exclusive pixels`).toBeGreaterThan(0); expect(primitive.canvas.pixels,`${primitive.key} Canvas pixels`).toBeGreaterThan(0); expect(primitive.bounds).not.toBeNull(); expect(primitive.canvas.bounds).not.toBeNull(); if(primitive.stroke) expect(primitive.width,`${primitive.key} stroke width`).toBeGreaterThan(0); expect(primitive.parity.basis).toContain('production drawPrimitive'); expect(primitive.parity.overlapRatio,primitive.key).toBeGreaterThan(.15); expect(primitive.parity.areaRatio,primitive.key).toBeGreaterThan(.15); expect(primitive.parity.areaRatio,primitive.key).toBeLessThan(2.2); expect(primitive.parity.meanChannelDelta,primitive.key).toBeLessThan(55); for(const edge of ['left','top','right','bottom']) expect(Math.abs(primitive.bounds[edge]-primitive.canvas.bounds[edge]),`${primitive.key} ${edge}`).toBeLessThanOrEqual(3/result.raster.resolution+.01); } expect(result.raster.restored).toBe(true); for(const key of ['textureCount','graphicsCount','containerCount']) expect(result.after[key]).toBe(result.before[key]); });

for(const cap of [{query:'&pixiGlobalEffectsCategoryCap=0',reason:'category-cap'},{query:'&pixiGlobalEffectsEntryCap=0',reason:'entry-cap'},{query:'&pixiGlobalEffectsTrailCap=0',reason:'trail-point-cap'},{query:'&pixiGlobalEffectsPrimitiveCap=0',reason:'primitive-cap'},{query:'&pixiGlobalEffectsSegmentCap=0',reason:'segment-cap'},{query:'&pixiGlobalEffectsContainerCap=0',reason:'container-cap'},{query:'&pixiGlobalEffectsGraphicsCap=0',reason:'graphics-cap'}]) test(`global effects ${cap.reason} rejects the complete block without truncation`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E13 cap evidence runs in primary Chromium'); await start(page,cap.query); const state=await page.evaluate(fixture),failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseGlobalEffectsLayer(value),state); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{laterNationLabel:{pixels:81}},rendering:{layers:{floatingText:{owned:true},globalEffects:{owned:false,entries:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.canvasFallback.order).toEqual(GLOBAL_EFFECT_PRESENTATION.map(value=>value[1])); });

for(const failure of [{kind:'global-effects-graphics-after-paint',reason:'graphics-resource'},{kind:'global-effects-final-append',reason:'container-resource'}]) test(`${failure.kind} withdraws every category and recovers`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','transactional E13 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),failed=await page.evaluate(({state,kind})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseGlobalEffectsLayer(state); },{state,kind:failure.kind}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{globalEffects:{owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason:failure.reason}}}}}); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseGlobalEffectsLayer(value),state); expect(recovered.rendering.layers.globalEffects).toMatchObject({owned:true,entries:21,resourceLimitFallback:{reason:null}}); });

for(const failure of [{kind:'global-effects-final-append',fatal:false,reason:'container-resource'},{kind:'global-effects-update',fatal:true,reason:'pixi-world-layer-failed: global-effects-update'},{kind:'final-render',fatal:true,reason:'pixi-render-failed: final-app-render'}]) test(`production renderPass ${failure.kind} keeps floaters below and nation labels above without double age`,async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','full-frame E13 evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.productionGlobalEffectsFailureProbe(kind),failure.kind); expect(result.floatingTextBelow).toBe(true); expect(result.nationLabelsAbove).toBe(true); expect(result.crop.pixels).toBeGreaterThan(0); expect(result.crop.magenta).toBeGreaterThan(0); expect(result.crop.white).toBeGreaterThan(0); expect(result.nationCrop.white).toBeGreaterThan(0); expect(result.omissionSensitivity.framebufferPixels).toBeGreaterThan(0); expect(result.omissionSensitivity.withoutGlobalEffectsPixels).toBe(0); expect(result.failed.fallbackReason||result.failed.layers.globalEffects?.resourceLimitFallback.reason).toContain(failure.reason); expect(result.after.tick).toBe(result.before.tick); expect(result.after.rng).toBe(result.before.rng); expect(result.after.callbacks).toBe(result.before.callbacks); expect(result.after.rafPending).toBe(result.before.rafPending); if(failure.fatal){ expect(result.failed.active).toBe('canvas'); expect(result.after.renders).toBe(result.before.renders+1); expect(result.after.smoke).toBe(result.before.smoke+1); for(const category of Object.keys(result.before.ages)) expect(result.after.ages[category]).toBe(result.before.ages[category]+1); }else{ expect(result.failed).toMatchObject({active:'pixi-hybrid',layers:{floatingText:{owned:true},globalEffects:{owned:false}}}); expect(result.after.renders).toBe(result.before.renders); expect(result.after.smoke).toBe(result.before.smoke); expect(result.after.ages).toEqual(result.before.ages); } });

test('WeakMap occurrence identity survives reorder, removal, and restore',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E13 identity evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); state.sparks.push(state.sparks[0]); const result=await page.evaluate(value=>window.__STATEFALL_TEST__.globalEffectsIdentityChurn(value),state),sparks=result.first.filter(value=>value.category==='sparks'); expect(sparks[0].key.split(':')[1]).toBe(sparks[1].key.split(':')[1]); expect(sparks.map(value=>value.key.split(':').at(-1))).toEqual(['0','1']); expect(result.restored.map(value=>value.key)).toEqual(result.first.map(value=>value.key)); });

test('production renderPass retains one legacy fog decision for air-wreck smoke and replay',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E13 fog/replay evidence runs in primary Chromium'); await start(page,'',true); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.globalEffectsVisibilityProbe()); expect(result.hiddenThreshold).toEqual({age:3,wrecks:1,puffs:0}); expect(result.revealedAfterThreshold).toEqual({age:4,wrecks:1,puffs:0}); expect(result.hiddenExpiry).toEqual({age:30,wrecks:0,puffs:0}); expect(result.visibleThreshold).toEqual({age:3,wrecks:1,puffs:1}); expect(result.sameFrameReplay).toEqual({age:3,wrecks:1,puffs:1,descriptorVisible:true,descriptorX:result.points.visible.x}); });

test('real effect adapters feed all feasible categories without simulation mutation',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E13 event-path evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.realGlobalEffectsProbe()); expect(result.fixtureKind).toContain('real fxSpark/fxScorch/fxTracer'); expect(result.sources).toMatchObject({scorches:[{age:0}],sparks:[{age:0}],puffs:[{age:0}],fragments:[{age:0}],tracers:[{age:0}],wrecks:[{age:0}],flashes:[{age:0}]}); expect(result.layer).toMatchObject({owned:true,counts:{scorches:1,sparks:1,puffs:1,fragments:1,tracers:1,wrecks:1,flashes:1,total:7}}); });

test('global effects ownership requires floating text and reset recovery is clean',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','E13 prerequisite evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseGlobalEffectsLayer(value),state); expect(failed.rendering.layers.globalEffects).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'floating-text-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseGlobalEffectsLayer(value),state); expect(recovered.rendering.layers).toMatchObject({floatingText:{owned:true},globalEffects:{owned:true}}); });

test('1800-frame all-category color/cull/pan/quality/motion churn plateaus within submission ceilings',async({page},testInfo)=>{ test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E13 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderGlobalEffectsChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(new Set(result.resources.slice(-6).map(value=>value.containersCreated)).size).toBe(1); expect(new Set(result.resources.slice(-6).map(value=>value.graphicsCreated)).size).toBe(1); console.log(`pixi E13 global effects churn: mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`); });
