const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE14NATIONOVERLAYS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); api.renderRepeatedly(2); });
}

test('production Pixi owns nation overlays after effects and leaves marker layers on Canvas',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E14 evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(async()=>{ const api=window.__STATEFALL_TEST__,checkpoint=await api.canonicalCheckpoint(),before=api.rendererDiagnostics(); api.renderRepeatedly(5); return {checkpoint,before,after:await api.canonicalCheckpoint(),rendering:api.rendererDiagnostics()}; }); test.skip(result.rendering.active!=='pixi-hybrid','Pixi WebGL renderer unavailable');
  expect(result.rendering.layers).toMatchObject({globalEffects:{owned:true},nationOverlays:{owned:true,order:['complete-global-effects','players-array-order','canvas-opening-region-network-markers-and-later'],textStrategy:'bounded-canvas-raster-player-group-sprites-current-browser-baseline',resourceLimitFallback:{reason:null}}}); expect(result.rendering.layers.nationOverlays.entries).toBeGreaterThan(0); expect(result.rendering.layers.nationOverlays.textureRefs).toBe(result.rendering.layers.nationOverlays.entries); expect(result.rendering.layers.nationOverlays.textureCount).toBe(result.rendering.layers.nationOverlays.entries); expect(result.after).toEqual(result.checkpoint); expect(result.rendering.layers.nationOverlays.textureAllocations-result.before.layers.nationOverlays.textureAllocations).toBeLessThanOrEqual(1);
});

for(const cap of [{query:'&pixiNationOverlayEntryCap=0',reason:'entry-cap'},{query:'&pixiNationOverlayLabelCap=0',reason:'label-cap'},{query:'&pixiNationOverlayCharCap=0',reason:'char-cap'},{query:'&pixiNationOverlayPrimitiveCap=0',reason:'primitive-cap'},{query:'&pixiNationOverlayContainerCap=0',reason:'container-cap'},{query:'&pixiNationOverlaySpriteCap=0',reason:'sprite-cap'},{query:'&pixiNationOverlayTextureCap=0',reason:'texture-cap'},{query:'&pixiNationOverlaySourceByteCap=0',reason:'source-byte-cap'}]) test(`nation overlay ${cap.reason} rejects the whole layer`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E14 cap evidence runs in primary Chromium'); await start(page,cap.query); const layer=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().layers.nationOverlays); expect(layer).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:cap.reason}}); expect(layer.textureRefs||0).toBe(0);
});

test('nation overlay segment cap rejects geometry inventory',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E14 cap evidence runs in primary Chromium'); await start(page,'&pixiNationOverlaySegmentCap=0'); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNationOverlayInventory()); expect(result.owned).toBe(false); expect(result.rendering).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'segment-cap'}});
});

test('recoverable final append withdraws all overlays and recovers without stale textures',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E14 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure('nation-overlays-final-append'); api.renderRepeatedly(1); const failed=api.rendererDiagnostics(); api.renderRepeatedly(1); return {failed,recovered:api.rendererDiagnostics()}; }); expect(result.failed.layers.nationOverlays).toMatchObject({owned:false,entries:0,textureRefs:0,resourceLimitFallback:{reason:'container-resource'}}); expect(result.recovered.layers.nationOverlays).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(result.recovered.layers.nationOverlays.textureRefs).toBe(result.recovered.layers.nationOverlays.entries);
});

test('fatal nation update falls back with one nonadvancing Canvas replay',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E14 fatal replay evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(async()=>{ const api=window.__STATEFALL_TEST__,before={checkpoint:await api.canonicalCheckpoint(),lifecycle:api.renderingLifecycle()}; api.injectRendererFailure('nation-overlays-update'); api.renderRepeatedly(1); return {before,after:{checkpoint:await api.canonicalCheckpoint(),lifecycle:api.renderingLifecycle(),rendering:api.rendererDiagnostics()}}; }); expect(result.after.checkpoint).toEqual(result.before.checkpoint); expect(result.after.lifecycle.rafCallbacks).toBe(result.before.lifecycle.rafCallbacks); expect(result.after.rendering.active).toBe('canvas'); expect(result.after.rendering.fallbackReason).toContain('pixi-world-layer-failed: nation-overlays-update');
});

for(const kind of ['nation-overlays-final-append','nation-overlays-update','final-render']) test(`production ${kind} keeps effects below, labels exclusive, and opening marker above`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused production failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>window.__STATEFALL_TEST__.nationOverlayProductionFailureProbe(kind),kind); expect(result.differentialPixels).toBeGreaterThan(0); expect(result.labelMasks.length).toBeGreaterThan(0); for(const mask of result.labelMasks) expect(mask.differentialPixels).toBeGreaterThan(0); expect(result.omissionSensitivity.withoutNationOverlayPixels).toBe(result.differentialPixels); expect(result.effectBelow.pixels).toBeGreaterThan(0); expect(result.openingMarkerAbove.light).toBeGreaterThan(0); expect(result.stageIndices.pixi).toBeLessThan(result.stageIndices.canvas); expect(result.after.lifecycle.tick).toBe(result.before.lifecycle.tick); expect(result.after.rng).toBe(result.before.rng); expect(result.after.lifecycle.callbacks).toBe(result.before.lifecycle.callbacks); expect(result.after.lifecycle.rafPending).toBe(result.before.lifecycle.rafPending); if(kind==='nation-overlays-final-append') expect(result.failed.layers.nationOverlays.owned).toBe(false); else expect(result.failed.active).toBe('canvas');
});

test('independent inventory matches direct legacy Canvas pixels without clipped icon sources',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E14 pixel evidence runs in Chromium at DPR 1, 1.5, and 2'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNationOverlayInventory()); test.skip(!result.owned,'Pixi WebGL renderer unavailable');
  const value=result.evidence; console.log(`E14 DPR ${value.resolution} parity`,JSON.stringify({expected:value.expectedPixels,actual:value.actualPixels,overlap:value.overlapPixels,mean:value.meanChannelDelta,max:value.maxDelta,overTwo:value.pixelsOverTwo,edges:value.sprites.map(sprite=>[sprite.edgePixels,sprite.edgeMaxAlpha])})); expect(value.resolution).toBe(testInfo.project.use.deviceScaleFactor||1); expect(value.order).toHaveLength(11); expect(value.expectedPixels).toBeGreaterThan(1000); expect(value.actualPixels).toBeGreaterThan(1000); expect(value.overlapPixels/Math.max(value.expectedPixels,value.actualPixels)).toBeGreaterThan(.95); expect(value.meanChannelDelta).toBeLessThanOrEqual(7); expect(value.fontCaveat).toContain('current-browser'); expect(value.sprites).toHaveLength(11); for(const sprite of value.sprites){ expect(sprite.edgeMaxAlpha).toBeLessThanOrEqual(32); expect(sprite.spriteAlpha).toBe(1); expect(sprite.sourceWidth).toBeGreaterThan(0); expect(sprite.sourceHeight).toBeGreaterThan(0); }
  expect(result.rendering.presentation.map(value=>[value.name,value.relation,value.handshake,value.heart,value.team])).toEqual([['Neutral','none',false,false,false],['Ordinary','none',false,false,false],['Mine','none',false,false,false],['Team Ally','ally',true,false,true],['Ally','ally',true,false,false],['Pact','pact',false,false,false],['Pulse','ally',true,false,false],['Heart','none',false,true,false],['Small','none',false,false,false],['Large','none',false,false,false],['Maximum','none',false,false,false]]);
});

test('1800 changing frames churn all visual inputs while pools and source cache stay bounded',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E14 changing-state soak runs in primary Chromium'); test.setTimeout(180_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderNationOverlayChurnFrames(1800)); expect(result.measurement).toContain('timing is advisory'); expect(result.resources).toHaveLength(12); const firstMax=Math.max(...result.resources.slice(0,6).map(value=>value.sourceBytes)),lastMax=Math.max(...result.resources.slice(6).map(value=>value.sourceBytes)); expect(lastMax).toBeLessThanOrEqual(firstMax+16384); expect(Math.max(...result.resources.map(value=>value.containersCreated))-result.resourceBefore.containersCreated).toBeLessThanOrEqual(12); expect(Math.max(...result.resources.map(value=>value.spritesCreated))-result.resourceBefore.spritesCreated).toBeLessThanOrEqual(12); for(const value of result.resources){ expect(value.textureRefs).toBe(value.textureCount); expect(value.textureAllocations-value.textureDestroyCount).toBe(value.textureCount); expect(value.sourceBytes).toBeLessThanOrEqual(64*1024*1024); } console.log(`pixi E14 changing churn advisory timing: p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms`);
});
