const {test,expect}=require('@playwright/test');
const {createCanvas,loadImage}=require('canvas');

test.describe.configure({mode:'serial'});

async function start(page,query=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${query}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object');
  await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE6WARSHIPS'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click();
  await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ window.__STATEFALL_TEST__.pause(); window.__STATEFALL_TEST__.installLateGameScene(); window.__STATEFALL_TEST__.freezePresentation(); });
}

function fixtureInPage(){
  const api=window.__STATEFALL_TEST__,camera=api.snapshot().camera,viewport={width:innerWidth,height:innerHeight},world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),classes=['sub','hunter','rship','privateer','scout','warship','cruiser','battleship'];
  const hp={sub:3,hunter:3,rship:3,privateer:4,scout:2,warship:5,cruiser:6,battleship:12},gun={sub:0,hunter:0,rship:0,privateer:0,scout:12,warship:26,cruiser:22,battleship:32},warships=classes.map((cls,index)=>{ const screenX=220+index*125,screenY=300+(index%2)*100,p=world(screenX,screenY),sub=cls==='sub'||cls==='hunter',barrage=cls==='cruiser'?{range:30}:cls==='battleship'?{range:36}:null; return {id:700+index,cls,...p,heading:index*.12,lean:(index-3)/24,recoil:index===5||index===7,fireAngle:0,hp:hp[cls]-.4,hpMax:hp[cls],gun:gun[cls],barrage,sub,speed:cls==='scout'?3.2:1.4,wake:sub?[]:[[p.x-8,p.y],[p.x-4,p.y],[p.x-1,p.y]],color:['#d9485f','#33a06f','#3f7bd9','#d98b36'][index%4],owned:true,selected:index===6,destination:index===6?{x:screenX+90,y:screenY+30}:null,visible:true,refitFraction:index===7 ? .4 : null,cruise:index===7,cooldownFraction:barrage ? .5 : null}; });
  return {camera,viewport,inheritedStrokeState:{lineJoin:'miter',lineCap:'butt'},warships};
}

async function pixels(locator){ const image=await loadImage(await locator.screenshot()),canvas=createCanvas(image.width,image.height),context=canvas.getContext('2d'); context.drawImage(image,0,0); return {width:image.width,height:image.height,data:context.getImageData(0,0,image.width,image.height).data}; }
function matches(image,x,y,r,predicate){ let count=0; for(let py=Math.max(0,y-r);py<=Math.min(image.height-1,y+r);py++) for(let px=Math.max(0,x-r);px<=Math.min(image.width-1,x+r);px++){ const i=(py*image.width+px)*4; if(predicate(...image.data.slice(i,i+4))) count++; } return count; }

test('Pixi owns every warship class and attached status visual in exact entry order',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E6 evidence runs in primary Chromium'); await start(page); const fixture=await page.evaluate(fixtureInPage),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); test.skip(!result.owned,'Pixi WebGL renderer unavailable');
  const layer=result.rendering.layers.warships; expect(layer).toMatchObject({owned:true,counts:{total:8,visible:8,hidden:0},labelCount:1,canvasStrokeState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0},generatedHullTextures:{strategy:'vector-primitives',references:0,textures:0}});
  expect(layer.presentation.map(value=>value.cls)).toEqual(['sub','hunter','rship','privateer','scout','warship','cruiser','battleship']);
  expect(layer.presentation[6].items).toEqual(['gun-range','barrage-range','selected-ring','destination-line','wake','hull-details-hp','cm-badge','barrage-cooldown'].filter(value=>value!=='cm-badge'));
  expect(layer.presentation[7].items).toEqual(['gun-range','barrage-range','wake','hull-details-hp','muzzle-flash','refit-arc','cm-badge','barrage-cooldown']);
  expect(layer.resources.map(value=>value.id)).toEqual(fixture.warships.map(value=>value.id));
  const image=await pixels(page.locator('.pixi-world')); expect(matches(image,220,300,18,(r,g,b,a)=>b>80&&a>0),'submarine hull remains translucent but painted').toBeGreaterThan(0); expect(matches(image,1095,400,30,(r,g,b,a)=>r>150&&g>120&&a>0),'battleship status and hull pixels render').toBeGreaterThan(0);
});

test('warship caps advance chronologically through visible array order',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused cap chronology runs in primary Chromium'); await start(page); const fixture=await page.evaluate(fixtureInPage);
  const evidence=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,cruiser={...value.warships.find(ship=>ship.cls==='cruiser'),id:810,heading:0,lean:0,recoil:false,selected:true,refitFraction:.25,cruise:true,cooldownFraction:.5},surface={...value.warships.find(ship=>ship.cls==='warship'),id:811,heading:0,lean:0},sub={...value.warships.find(ship=>ship.cls==='sub'),id:812,heading:0,lean:0,wake:[]},run=(warships,lineCap='butt')=>api.exerciseWarshipLayer({...value,inheritedStrokeState:{lineJoin:'miter',lineCap},warships}).rendering.layers.warships; return {first:run([cruiser]),prior:run([surface,sub]),none:run([{...surface,wake:[]},sub]),round:run([{...cruiser,wake:[]}],'round'),culled:run([{...surface,x:100000,y:100000,wake:[[99998,100000],[99999,100000]]}]),hidden:run([{...surface,visible:false}])}; },fixture);
  const first=evidence.first.presentation[0],caps=Object.fromEntries(first.itemCaps.map(value=>[value.semantic,value.lineCap]));
  expect(first).toMatchObject({cls:'cruiser',incomingLineCap:'butt',outgoingLineCap:'round'}); expect(caps).toMatchObject({'gun-range':'butt','barrage-range':'butt','selected-ring':'butt','destination-line':'butt',wake:'round','hull-details-hp':'round','refit-arc':'round','cm-badge':'round','barrage-cooldown':'round'});
  expect(first.styles.filter(value=>value.stroke==='#d9d7c7')).toEqual(expect.arrayContaining([expect.objectContaining({kind:'line',cap:'round',join:'round'})]));
  expect(evidence.first.strokeTimeline).toEqual([{id:810,order:0,cls:'cruiser',incomingLineCap:'butt',outgoingLineCap:'round',wakeTransition:true}]);
  expect(evidence.prior.strokeTimeline.map(value=>[value.cls,value.incomingLineCap,value.outgoingLineCap])).toEqual([['warship','butt','round'],['sub','round','round']]); expect(evidence.prior.presentation[1].itemCaps.find(value=>value.semantic==='hull-details-hp').lineCap).toBe('round');
  expect(evidence.none.canvasStrokeState.lineCap).toBe('butt'); expect(evidence.none.strokeTimeline.every(value=>value.incomingLineCap==='butt'&&value.outgoingLineCap==='butt')).toBe(true);
  expect(evidence.round.presentation[0].itemCaps.every(value=>value.lineCap==='round')).toBe(true);
  expect(evidence.culled).toMatchObject({entries:0,canvasStrokeState:{lineCap:'round'},strokeTimeline:[{incomingLineCap:'butt',outgoingLineCap:'round',wakeTransition:true}]});
  expect(evidence.hidden).toMatchObject({entries:0,canvasStrokeState:{lineCap:'butt'},strokeTimeline:[]});
});

test('duplicate IDs and injected resource failures withdraw all warships but preserve naval ownership and recover',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E6 evidence runs in primary Chromium'); await start(page); const fixture=await page.evaluate(fixtureInPage),duplicate=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer({...value,warships:[value.warships[0],{...value.warships[1],id:value.warships[0].id}]}),fixture);
  expect(duplicate.rendering.layers).toMatchObject({navalLogistics:{owned:true},warships:{owned:false,entries:0,resourceLimitFallback:{reason:'invalid-id'}}});
  for(const failure of [{kind:'warship-graphics-after-append',reason:'graphics-resource'},{kind:'warship-label-after-paint',reason:'label-resource'},{kind:'warship-container-after-append',reason:'container-resource'}]){ await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); const failed=await page.evaluate(({kind,value})=>{ window.__STATEFALL_TEST__.injectRendererFailure(kind); return window.__STATEFALL_TEST__.exerciseWarshipLayer(value); },{kind:failure.kind,value:fixture}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,rendering:{layers:{navalLogistics:{owned:true},warships:{owned:false,entries:0,resourceLimitFallback:{reason:failure.reason}}}}}); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); expect(recovered.rendering.layers.warships).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.warships.resources.every(value=>value.childCount===value.children.length)).toBe(true); }
});

test('constructor failures leave no phantom warship slots and stable IDs survive reorder, remove, and re-add',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E6 constructor and identity evidence runs in primary Chromium'); await start(page); const fixture=await page.evaluate(fixtureInPage);
  for(const failure of [{kind:'warship-container',reason:'container-resource',created:'containersCreated'},{kind:'warship-graphics',reason:'graphics-resource',created:'graphicsCreated'},{kind:'warship-label',reason:'label-resource',created:'labelCreated'}]){
    await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.resetRendererResources(); api.exerciseStructureLayer([],{preStructures:[]}); api.exerciseNavalLogistics({transports:[],merchants:[],boarding:[]}); });
    const baseline=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().layers.warships),value=failure.kind==='warship-label'?{...fixture,warships:[fixture.warships[7]]}:{...fixture,warships:[fixture.warships[5]]};
    const failed=await page.evaluate(({kind,value})=>{ window.__STATEFALL_TEST__.injectRendererFailure(kind); return window.__STATEFALL_TEST__.exerciseWarshipLayer(value); },{kind:failure.kind,value}); expect(failed.rendering.layers.warships).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:failure.reason}}); expect(failed.rendering.layers.warships[failure.created]).toBe(baseline[failure.created]);
    const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),value); expect(recovered.rendering.layers.warships).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.warships[failure.created]).toBeGreaterThan(baseline[failure.created]);
  }
  await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources());
  const ids=value=>value.rendering.layers.warships.resources.map(item=>item.id),first=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture),reordered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer({...value,warships:value.warships.slice().reverse()}),fixture),removed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer({...value,warships:value.warships.slice(1)}),fixture),readded=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture);
  expect(new Set(ids(reordered))).toEqual(new Set(ids(first))); expect(ids(removed)).not.toContain(fixture.warships[0].id); expect(ids(readded)).toEqual(fixture.warships.map(value=>value.id));
});

test('warship ownership requires complete structures and naval logistics',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','dependency evidence runs in primary Chromium'); await start(page); const fixture=await page.evaluate(fixtureInPage); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); expect(failed.rendering.layers.warships).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'structures-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); expect(recovered.rendering.layers).toMatchObject({structures:{owned:true},navalLogistics:{owned:true},warships:{owned:true}});
});

test('warship fixture remains CSS-pixel aligned at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!testInfo.project.name.startsWith('chromium-desktop-scale-'),'DPR evidence runs in desktop-scale projects'); await start(page); const fixture=await page.evaluate(fixtureInPage),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),fixture); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); const image=await pixels(page.locator('.pixi-world')),dpr=await page.evaluate(()=>devicePixelRatio); expect(matches(image,Math.round(845*dpr),Math.round(400*dpr),Math.ceil(22*dpr),(r,g,b,a)=>r+g+b>150&&a>0)).toBeGreaterThan(0); expect(result.rendering.layers.warships).toMatchObject({owned:true,counts:{visible:8},labelCount:1});
});

test('damaged leaned recoil HP pips match the legacy Canvas footprint at every DPR',async({page},testInfo)=>{
  test.skip(!testInfo.project.name.startsWith('chromium-desktop-scale-'),'warship HP parity runs in desktop-scale projects'); await start(page);
  const state=await page.evaluate(()=>{ const camera={x:0,y:0,scale:10},ship={id:920,cls:'cruiser',x:72,y:45,heading:.7,lean:.2,recoil:true,fireAngle:.4,hp:2.2,hpMax:6,gun:0,barrage:null,sub:false,speed:1.4,wake:[],color:'#d9485f',owned:false,selected:false,destination:null,visible:true,refitFraction:null,cruise:false,cooldownFraction:null}; return {camera,viewport:{width:innerWidth,height:innerHeight},inheritedStrokeState:{lineJoin:'miter',lineCap:'butt'},warships:[ship]}; }),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable');
  const pixi=await pixels(page.locator('.pixi-world')); await page.evaluate(value=>{ window.__STATEFALL_TEST__.injectRendererFailure('warship-graphics-after-append'); return window.__STATEFALL_TEST__.exerciseWarshipLayer(value); },state); const canvas=await pixels(page.locator('#map')),dpr=await page.evaluate(()=>devicePixelRatio),region={left:665,top:394,right:714,bottom:406},mask=image=>{ const points=new Set(); for(let y=Math.floor(region.top*dpr);y<=Math.ceil(region.bottom*dpr);y++) for(let x=Math.floor(region.left*dpr);x<=Math.ceil(region.right*dpr);x++){ const i=(y*image.width+x)*4;if(image.data[i]>190&&image.data[i+1]>190&&image.data[i+2]>190&&image.data[i+3]>100) points.add(`${x},${y}`); } return points; },a=mask(pixi),b=mask(canvas),intersection=new Set([...a].filter(value=>b.has(value)));
  expect(a.size,`Pixi HP pixels at DPR ${dpr}`).toBeGreaterThan(0); expect(b.size,`Canvas HP pixels at DPR ${dpr}`).toBeGreaterThan(0); expect(intersection.size/Math.max(a.size,b.size),`leaned recoil HP pixel overlap at DPR ${dpr}`).toBeGreaterThan(.55);
});

test('distinguishes inherited butt and round dash and cruiser-detail endpoints at every DPR',async({page},testInfo)=>{
  test.skip(!testInfo.project.name.startsWith('chromium-desktop-scale-'),'warship endpoint evidence runs in desktop-scale projects'); await start(page);
  const states=await page.evaluate(()=>{ const ship={id:900,cls:'cruiser',x:72,y:45,heading:0,lean:0,recoil:false,fireAngle:0,hp:5.6,hpMax:6,gun:22,barrage:{range:30},sub:false,speed:1.4,wake:[],color:'#d9485f',owned:true,selected:true,destination:null,visible:true,refitFraction:.4,cruise:false,cooldownFraction:.5},base={camera:{x:0,y:0,scale:10},viewport:{width:1440,height:900},warships:[ship]},api=window.__STATEFALL_TEST__; return {butt:api.exerciseWarshipLayer({...base,inheritedStrokeState:{lineJoin:'miter',lineCap:'butt'}}),roundState:{...base,inheritedStrokeState:{lineJoin:'miter',lineCap:'round'}}}; });
  test.skip(!states.butt.owned,'Pixi WebGL renderer unavailable'); const butt=await pixels(page.locator('.pixi-world')),roundResult=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseWarshipLayer(value),states.roundState),round=await pixels(page.locator('.pixi-world')),dpr=Math.min(testInfo.project.use.deviceScaleFactor,2);
  expect(states.butt.rendering.layers.warships).toMatchObject({canvasStrokeState:{lineCap:'butt'},presentation:[{incomingLineCap:'butt',outgoingLineCap:'butt'}]}); expect(roundResult.rendering.layers.warships).toMatchObject({canvasStrokeState:{lineCap:'round'},presentation:[{incomingLineCap:'round',outgoingLineCap:'round'}]});
  const white=(image,left,top,right,bottom)=>{ let count=0; for(let y=Math.floor(top*dpr);y<=Math.ceil(bottom*dpr);y++) for(let x=Math.floor(left*dpr);x<=Math.ceil(right*dpr);x++){ const i=(y*image.width+x)*4,r=image.data[i],g=image.data[i+1],b=image.data[i+2],a=image.data[i+3]; if(a>0&&r>180&&g>180&&b>180) count++; } return count; };
  const buttMast=white(butt,725.2,431.7,727,435.3),roundMast=white(round,725.2,431.7,727,435.3); expect(roundMast,`round cruiser mast/detail endpoint pixels at DPR ${dpr}`).toBeGreaterThan(buttMast);
  const endpoint={x:720+Math.cos(60/62.7)*62.7,y:450+Math.sin(60/62.7)*62.7},roundOnly=(left,top,right,bottom)=>{ let count=0; for(let y=Math.floor(top*dpr);y<=Math.ceil(bottom*dpr);y++) for(let x=Math.floor(left*dpr);x<=Math.ceil(right*dpr);x++){ const i=(y*round.width+x)*4,buttLight=butt.data[i]+butt.data[i+1]+butt.data[i+2],roundLight=round.data[i]+round.data[i+1]+round.data[i+2]; if(round.data[i+3]>=butt.data[i+3]&&roundLight>buttLight+24) count++; } return count; };
  expect(roundOnly(endpoint.x-3,endpoint.y-3,endpoint.x+3,endpoint.y+3),`round selected-ring dash endpoint pixels at DPR ${dpr}`).toBeGreaterThan(0);
});

test('1800-frame class, color, state, selection, fire, HP, wake, cull, and reorder churn plateaus',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E6 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderWarshipChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(new Set(result.resources.map(value=>value.visibility))).toEqual(new Set(['visible','hidden'])); for(const key of ['containersCreated','graphicsCreated','labelCreated','labelTextures']) expect(new Set(result.resources.slice(-6).map(value=>value[key])).size,`${key} plateaus`).toBe(1); expect(result.resources.every(value=>value.hullTextureRefs===0)).toBe(true); expect(result.heapAssertion).toContain('advisory-only'); expect(result.gpuAssertion).toContain('unknown'); console.log(`pixi E6 warship churn (${result.measurement}): mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms; heap ${result.heapAssertion}; GPU ${result.gpuAssertion}`);
});
