const {test,expect}=require('@playwright/test');

test.describe.configure({mode:'serial'});

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object');
  await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE8MISSILES'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.installLateGameScene(); api.freezePresentation(); });
}

function fixture(){
  const camera=window.__STATEFALL_TEST__.snapshot().camera,mapWidth=720,world=(x,y)=>({x:(x-camera.x)/camera.scale,y:(y-camera.y)/camera.scale}),tile=(x,y)=>{ const p=world(x,y); return Math.max(0,Math.floor(p.y))*mapWidth+Math.max(0,Math.floor(p.x)); };
  return {camera:{x:camera.x,y:camera.y,scale:camera.scale},viewport:{width:innerWidth,height:innerHeight},mapWidth,nukeRadius:4,cruiseRadius:3,now:450,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches,inheritedStrokeState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0},missiles:[
    {source:{name:'normal'},owner:1,owned:false,visible:true,from:tile(180,420),t:tile(500,420),age:28,flight:55,cruise:false},
    {source:{name:'cruise'},owner:0,owned:true,visible:false,from:tile(680,520),t:tile(980,520),age:22,flight:40,cruise:true}
  ]};
}

test('Pixi owns normal and cruise missiles in exact array and primitive order',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E8 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); const layer=result.rendering.layers.missiles;
  expect(layer).toMatchObject({owned:true,counts:{total:2,visible:2,hidden:0,normal:1,cruise:1},canvasStrokeState:{lineJoin:'miter',lineCap:'round',globalAlpha:1,lineDash:[],lineDashOffset:0}});
  expect(layer.presentation.map(value=>value.variant)).toEqual(['normal','cruise']); expect(layer.presentation.map(value=>value.items)).toEqual([['missile-trail','missile-body','missile-target-warning'],['missile-trail','missile-body','missile-target-warning']]); expect(layer.presentation.map(value=>value.bodyScale)).toEqual([1,.65]); expect(layer.presentation.map(value=>value.warningRadius)).toEqual([4,3]); expect(layer.presentation[0].trailSamples.map(value=>value.age)).toEqual(Array.from({length:15},(_,i)=>i*2)); expect(layer.presentation[1].trailN).toBe(11); expect(layer.presentation[1].heading).not.toBeNaN(); expect(layer.presentation[0].warningAlpha).toBe(.35+.35*Math.sin(3));
});

test('isolated real Pixi Graphics rasterize every E8 semantic at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop','chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'focused E8 raster evidence runs in Chromium DPR projects'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,layer=api.exerciseMissileLayer(value),before=api.rendererDiagnostics(),raster=api.missileRasterEvidence(); return {layer,before,raster,after:api.rendererDiagnostics()}; },state); test.skip(!result.layer.owned,'Pixi WebGL renderer unavailable');
  expect(result.raster.order).toEqual(['missile-trail','missile-body','missile-target-warning','missile-trail','missile-body','missile-target-warning']); expect(result.raster.resolution).toBe(await page.evaluate(()=>devicePixelRatio)); expect(result.raster.combined.pixels).toBeGreaterThan(0); expect(result.raster.combined.colors).toBeGreaterThan(5); expect(result.raster.primitives).toHaveLength(6); for(const evidence of result.raster.primitives){ expect(evidence.pixels,`${evidence.key} pixels`).toBeGreaterThan(0); expect(evidence.bounds,`${evidence.key} bounds`).toMatchObject({left:expect.any(Number),top:expect.any(Number),right:expect.any(Number),bottom:expect.any(Number)}); } expect(result.raster.restored).toBe(true); for(const key of ['textureCount','graphicsCount','containerCount']) expect(result.after[key],`${key} unchanged by extraction`).toBe(result.before[key]);
});

test('an intentional overlap keeps a real projectile pixel below the later missile body',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','ordered overlap evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),result=await page.evaluate(value=>{ const api=window.__STATEFALL_TEST__,first=api.exerciseMissileLayer(value),entry=first.rendering.layers.missiles.presentation[0],camera=value.camera,x=camera.x+entry.current.x*camera.scale,y=camera.y+entry.current.y*camera.scale,worldX=entry.current.x,worldY=entry.current.y,projectile={camera:value.camera,viewport:value.viewport,inheritedStrokeState:{lineJoin:'miter',lineCap:'butt'},shells:[],visualShots:[{source:{name:'overlap'},x0:worldX-4/camera.scale,y0:worldY,x1:worldX+4/camera.scale,y1:worldY,col:'#ff00ff',age:1,alpha:1,lifetime:6}]}; api.exerciseProjectileLayer(projectile); api.exerciseMissileLayer(value); return {missile:api.missileRasterEvidence([{x,y}]),projectile:api.projectileRasterEvidence([{x,y}])}; },state); const missilePixel=result.missile.combined.samples[0].rgba,stackedPixel=result.missile.stacked.samples[0].rgba,projectilePixel=result.projectile.combined.samples[0].rgba; expect(projectilePixel[0]).toBeGreaterThan(200); expect(projectilePixel[2]).toBeGreaterThan(200); expect(projectilePixel[1]).toBeLessThan(80); expect(stackedPixel).toEqual(missilePixel); expect(stackedPixel).not.toEqual(projectilePixel);
});

test('missile failures withdraw the whole layer, Canvas-paint it, and recover without ghosts',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','transactional E8 evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture);
  for(const failure of [{kind:'missile-graphics-after-paint',reason:'graphics-resource'},{kind:'missile-container-after-append',reason:'container-resource'}]){ const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseMissileLayer(state); },{kind:failure.kind,state}); expect(failed).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,state:{globalAlpha:1,lineJoin:'miter',lineCap:'round',lineDash:[],lineDashOffset:0}},rendering:{layers:{projectiles:{owned:true},missiles:{owned:false,entries:0,resourceLimitFallback:{reason:failure.reason}}}}}); expect(failed.canvasFallback.order).toEqual(['missile-trail','missile-body','missile-target-warning','missile-trail','missile-body','missile-target-warning']); for(const pixels of Object.values(failed.canvasFallback.semanticPixels)) expect(pixels).toBeGreaterThan(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); expect(recovered.rendering.layers.missiles).toMatchObject({owned:true,resourceLimitFallback:{reason:null}}); expect(recovered.rendering.layers.missiles.resources.every(value=>value.childCount===value.children.length)).toBe(true); }
});

for(const cap of [
  {name:'entry',query:'',reason:'entry-cap',fail(state){ const hidden={...state.missiles[0],source:null,visible:false,owned:false,age:0}; state.missiles=Array.from({length:8193},(_,index)=>index===8192?state.missiles[0]:{...hidden,source:{index}}); }},
  {name:'trail',query:'&pixiMissileTrailCap=3',reason:'trail-cap',fail(state){ state.missiles=[{...state.missiles[0],age:8}]; },recover(state){ state.missiles=[{...state.missiles[0],age:0}]; }},
  {name:'primitive',query:'&pixiMissilePrimitiveCap=7',reason:'primitive-cap',fail(state){ state.missiles=[state.missiles[0],{...state.missiles[0],source:{name:'primitive-cap'},from:state.missiles[0].from+1,t:state.missiles[0].t+1}]; },recover(state){ state.missiles=[{...state.missiles[0],age:0}]; }},
  {name:'segment',query:'&pixiMissileSegmentCap=20',reason:'segment-cap',fail(state){ state.missiles=[{...state.missiles[0],age:100,flight:120}]; },recover(state){ state.missiles=[{...state.missiles[0],age:0}]; }}
]) test(`missile ${cap.name} cap falls back to complete uncapped Canvas and recovers`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E8 cap fallback evidence runs in primary Chromium'); test.setTimeout(60_000); await start(page,cap.query); const state=await page.evaluate(fixture); cap.fail(state); const failed=await page.evaluate(value=>{ const before=JSON.stringify(value),result=window.__STATEFALL_TEST__.exerciseMissileLayer(value); return {before,after:JSON.stringify(value),result}; },state);
  expect(failed.after).toBe(failed.before); expect(failed.result).toMatchObject({owned:false,fallbackPainted:true,canvasFallback:{painted:true,state:{globalAlpha:1,lineJoin:'miter',lineCap:'round',lineDash:[],lineDashOffset:0}},rendering:{layers:{projectiles:{owned:true},missiles:{owned:false,entries:0,graphicsActive:0,resourceLimitFallback:{reason:cap.reason}}}}}); expect(failed.result.canvasFallback.order).toEqual(Array.from({length:cap.name==='primitive'?2:1},()=>['missile-trail','missile-body','missile-target-warning']).flat()); expect(failed.result.canvasFallback.pixels).toBeGreaterThan(0); for(const semantic of ['missile-trail','missile-body','missile-target-warning']) expect(failed.result.canvasFallback.semanticPixels[semantic],semantic).toBeGreaterThan(0);
  expect(failed.result.canvasFallback.laterAircraft).toMatchObject({pixels:expect.any(Number),framebuffer:'same-canvas-after-missiles'}); expect(failed.result.canvasFallback.laterAircraft.pixels).toBeGreaterThan(0); const recovery=await page.evaluate(fixture); if(cap.recover) cap.recover(recovery); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),recovery); expect(recovered.rendering.layers.missiles).toMatchObject({owned:true,resourceLimitFallback:{reason:null}});
});

test('missile container and Graphics constructor failures leave no phantom slots and retry',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','constructor E8 evidence runs in primary Chromium'); for(const [kind,reason] of [['missile-container','container-resource'],['missile-graphics','graphics-resource']]){ await start(page); const state=await page.evaluate(fixture); state.missiles.push({...state.missiles[0],source:{name:'constructor-extra'},from:state.missiles[0].from+2,t:state.missiles[0].t+2}); const failed=await page.evaluate(({kind,state})=>{ const api=window.__STATEFALL_TEST__; api.injectRendererFailure(kind); return api.exerciseMissileLayer(state); },{kind,state}); expect(failed.rendering.layers).toMatchObject({projectiles:{owned:true},missiles:{owned:false,entries:0,resourceLimitFallback:{reason}}}); expect(failed.rendering.layers.missiles.graphicsActive).toBe(0); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); expect(recovered.rendering.layers.missiles).toMatchObject({owned:true,entries:3,resourceLimitFallback:{reason:null}}); }
});

test('missile ownership requires the complete E4-E7 prerequisite chain',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','dependency evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture); await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources()); const failed=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); expect(failed.rendering.layers.missiles).toMatchObject({owned:false,entries:0,resourceLimitFallback:{reason:'structures-unowned'}}); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const recovered=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); expect(recovered.rendering.layers).toMatchObject({structures:{owned:true},navalLogistics:{owned:true},warships:{owned:true},projectiles:{owned:true},missiles:{owned:true}});
});

test('fatal final submit replays missiles once on Canvas with omission-sensitive primitive evidence',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','same-frame E8 replay evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.finalSubmissionFailureProbe()),overlays=new Set(['0:missile-body:2:fill']); expect(result.rendering).toMatchObject({active:'canvas',fallbackCleanup:{contextState:'destroyed',layers:{projectiles:{owned:false},missiles:{owned:false}}}}); expect(result.rendering.fallbackReason).toContain('pixi-render-failed: final-app-render'); expect(result.missileReplay.primitiveOrder.length).toBeGreaterThan(5); expect(result.missileReplay.totalDifferentialPixels).toBeGreaterThan(0); for(const key of result.missileReplay.primitiveOrder){ const evidence=result.missileReplay.primitiveEvidence[key],overlay=overlays.has(key); expect(evidence.framebuffer).toBe('fatal-canvas-replay'); expect(evidence.maskPixels,`${key} mask`).toBeGreaterThan(0); if(overlay){ expect(evidence.exclusiveMaskPixels,`${key} overlay`).toBe(0); expect(evidence.differentialPixels,`${key} overlay differential`).toBe(0); }else{ expect(evidence.exclusiveMaskPixels,`${key} exclusive`).toBeGreaterThan(0); expect(evidence.differentialPixels,`${key} differential`).toBeGreaterThan(0); } expect(result.missileReplay.omissionSensitivity[key].lostPixels).toBe(evidence.differentialPixels); } expect(result.missileReplay.later.aircraft).toMatchObject({pixels:expect.any(Number),colors:expect.any(Number),changed:0}); expect(result.missileReplay.later.aircraft.pixels).toBeGreaterThan(0); expect(result.after.lifecycle.callbacks).toBe(result.before.lifecycle.callbacks); expect(result.after.lifecycle.renders).toBe(result.before.lifecycle.renders+1); expect(result.visualShots).toEqual({age:1,count:1,pruned:true});
});

test('reduced motion keeps the legacy missile warning pulse on the supplied frame timestamp',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-reduced-motion','E8 reduced-motion semantics run in the reduced-motion project'); await start(page); const state=await page.evaluate(fixture); state.now=450; const result=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); test.skip(!result.owned,'Pixi WebGL renderer unavailable'); expect(result.rendering.reducedMotion).toBe(true); expect(result.rendering.layers.missiles.presentation[0].warningAlpha).toBe(.35+.35*Math.sin(3)); expect(result.rendering.layers.missiles.pulseTime).toBe(450);
});

test('WeakMap identities survive reorder and removal without changing source state',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','identity evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),before=JSON.stringify(state),result=await page.evaluate(value=>({result:window.__STATEFALL_TEST__.missileIdentityChurn(value),after:JSON.stringify(value)}),state); expect(result.after).toBe(before); expect(result.result.first[0].key).toBe(result.result.reordered[1].key); expect(result.result.first[1].key).toBe(result.result.reordered[0].key); expect(result.result.restored.map(value=>value.key).sort()).toEqual(result.result.first.map(value=>value.key).sort());
});

test('active missile resources recreate after BFCache loss and clean up on context loss',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','E8 lifecycle evidence runs in primary Chromium'); await start(page); const state=await page.evaluate(fixture),owned=await page.evaluate(value=>window.__STATEFALL_TEST__.exerciseMissileLayer(value),state); test.skip(!owned.owned,'Pixi WebGL renderer unavailable'); expect(owned.rendering.layers.missiles.entries).toBe(2); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}))); await page.locator('.pixi-world').evaluate(element=>element.remove()); await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}))); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.renderingLifecycle().suspended)).toBe(false); await page.evaluate(()=>window.__STATEFALL_TEST__.renderRepeatedly(1)); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics()); expect(restored).toMatchObject({active:'pixi-hybrid',layers:{missiles:{owned:true}}}); const supported=await page.locator('.pixi-world').evaluate(canvas=>!!(canvas.getContext('webgl2')||canvas.getContext('webgl'))?.getExtension('WEBGL_lose_context')); test.skip(!supported,'WEBGL_lose_context unavailable'); await page.locator('.pixi-world').evaluate(canvas=>(canvas.getContext('webgl2')||canvas.getContext('webgl')).getExtension('WEBGL_lose_context').loseContext()); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics().active)).toBe('canvas'); const failed=await page.evaluate(()=>window.__STATEFALL_TEST__.rendererDiagnostics()); expect(failed).toMatchObject({fallbackCleanup:{contextState:'destroyed',layers:{missiles:{owned:false,entries:0}}}});
});

test('1800-frame age, type, owner, fog, cull, reorder, and create-remove churn plateaus',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long synthetic E8 soak runs in primary Chromium'); test.setTimeout(120_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderMissileChurnFrames(1800)); expect(result.measurement).toContain('local synchronous CPU/render-submission'); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); for(const key of ['containersCreated','graphicsCreated']) expect(new Set(result.resources.slice(-6).map(value=>value[key])).size,`${key} plateaus`).toBe(1); expect(result.heapAssertion).toContain('advisory-only'); expect(result.gpuAssertion).toContain('unknown'); console.log(`pixi E8 missile churn (${result.measurement}): mean ${result.mean.toFixed(3)} ms, p95 ${result.p95.toFixed(3)} ms, p99 ${result.p99.toFixed(3)} ms, max ${result.max.toFixed(3)} ms; heap ${result.heapAssertion}; GPU ${result.gpuAssertion}`);
});
