const {test,expect}=require('@playwright/test');

async function start(page,extra=''){
  await page.addInitScript(()=>{ window.__STATEFALL_TEST_MODE__=true; localStorage.setItem('statefall-audio',JSON.stringify({master:0,sfx:0,alert:0,amb:0,music:0})); });
  await page.goto(`/index.html?browserTest=1&renderer=pixi${extra}`,{waitUntil:'load'}); await expect.poll(()=>page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('object'); await page.evaluate(()=>window.__STATEFALL_TEST__.prepareControlledStart()); await page.locator('#maps button[data-m="random"]').click(); await page.locator('#seedIn').fill('PHASEE17INTERACTION'); await page.locator('#countrySel').selectOption('0'); await page.locator('#startBtn').click(); await expect.poll(()=>page.evaluate(()=>window.__STATEFALL_TEST__.status().ready)).toBe(true); await page.evaluate(()=>{ const api=window.__STATEFALL_TEST__; api.pause(); api.freezePresentation(); });
}

test('Pixi owns the complete ordered final interaction block without input or authority mutation',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 inventory runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering.order).toEqual(['complete-notification-overlays','pick-label','selection-box','draft-panel-and-label','paused-scrim-and-labels','build-cursor','end-of-frame']); expect(result.rendering.presentation.map(value=>value.semantic)).toEqual(['pick-label','selection-box','draft-panel','draft-label','paused-scrim','paused-title','paused-subtitle','build-cursor']); expect(result.rendering).toMatchObject({owned:true,counts:{entries:8,primitives:4,labels:4,visible:8,culled:0},interactive:false,resourceLimitFallback:{reason:null}}); expect(result.notifications.owned).toBe(true); expect(result.canvas).toMatchObject({mounted:true,pointerEvents:'auto'}); expect(result.pixi.pointerEvents).toBe('none');
});

for(const variant of ['pick','box','dashed','draft','paused','valid','invalid']) test(`E17 ${variant} condition retains exact bounded inventory`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 variants run in primary Chromium'); await start(page); const result=await page.evaluate(value=>window.__STATEFALL_TEST__.renderInteractionInventory(value),variant); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.rendering.counts.visible).toBeGreaterThan(0); if(variant==='dashed'){ const box=result.rendering.presentation.find(value=>value.semantic==='selection-box'); expect(box.primitive.dash).toEqual([7,4]); expect(box.primitive.segments).toBeGreaterThan(4); } if(variant==='valid'||variant==='invalid') expect(result.rendering.presentation[0].primitive.stroke).toBe(variant==='valid'?'#7fffa0':'#ff6b6b');
});

for(const cap of ['Entry','Primitive','Segment','Label','Char','Container','Graphics','Sprite','Texture','SourceByte']) test(`E17 ${cap} cap rejects without truncation and direct Canvas paints`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 cap evidence runs in primary Chromium'); await start(page,`&pixiInteraction${cap}Cap=0`); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); expect(result.after).toEqual(result.before); expect(result.rendering.owned).toBe(false); expect(result.rendering.resourceLimitFallback.reason).toContain('cap'); expect(result.rendering.entries).toBe(0); expect(result.canvasPixels).toBeGreaterThan(0); expect(result.notifications.owned).toBe(true);
});

for(const failure of ['interaction-overlays-source','interaction-overlays-after-paint','interaction-overlays-final-append']) test(`recoverable ${failure} withdraws E17, paints direct Canvas, and recovers cleanly`,async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 failure evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(kind=>{ const failed=window.__STATEFALL_TEST__.renderInteractionInventory('all',kind),recovered=window.__STATEFALL_TEST__.renderInteractionInventory('all'); return {failed,recovered}; },failure); expect(result.failed.after).toEqual(result.failed.before); expect(result.failed.replayed).toBe(false); expect(result.failed.active).toBe('pixi-hybrid'); expect(result.failed.rendering.owned).toBe(false); expect(result.failed.rendering.entries).toBe(0); expect(result.failed.rendering.textureRefs).toBe(0); expect(result.failed.canvasPixels).toBeGreaterThan(0); expect(result.failed.notifications.owned).toBe(true); expect(result.recovered.rendering.owned).toBe(true); expect(result.recovered.rendering.textureRefs).toBe(result.recovered.rendering.spritesActive);
});

test('fatal final submission performs one nonadvancing full Canvas replay from frozen E17 input',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 fatal evidence runs in primary Chromium'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all','final-render')); expect(result.after).toEqual(result.before); expect(result.replayed).toBe(true); expect(result.active).toBe('canvas'); expect(result.canvasPixels).toBeGreaterThan(0); expect(result.canvas.mounted).toBe(true);
});

test('E17 viewport inventory remains bounded on mobile and reduced motion',async({page},testInfo)=>{
  test.skip(!['chromium-mobile','webkit-mobile','chromium-reduced-motion'].includes(testInfo.project.name),'E17 responsive evidence runs in mobile and reduced motion'); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory()); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); const viewport=page.viewportSize(); for(const entry of result.rendering.presentation){ expect(entry.bounds.right).toBeGreaterThanOrEqual(0); expect(entry.bounds.bottom).toBeGreaterThanOrEqual(0); expect(entry.bounds.left).toBeLessThanOrEqual(viewport.width); expect(entry.bounds.top).toBeLessThanOrEqual(viewport.height); }
});

test('actual E17 Pixi primitives and labels match direct Canvas at DPR 1, 1.5, and 2',async({page},testInfo)=>{
  test.skip(!['chromium-desktop-scale-1','chromium-desktop-scale-1.5','chromium-desktop-scale-2'].includes(testInfo.project.name),'E17 pixel evidence runs at desktop DPR 1, 1.5, and 2'); await start(page); const result=await page.evaluate(()=>{ const inventory=window.__STATEFALL_TEST__.renderInteractionInventory('all'); return {inventory,evidence:window.__STATEFALL_TEST__.interactionRasterEvidence()}; }); test.skip(!result.inventory.rendering.owned,'Pixi WebGL renderer unavailable'); const evidence=result.evidence; expect(evidence.resolution).toBe(testInfo.project.use.deviceScaleFactor||1); expect(evidence.expectedPixels).toBeGreaterThan(100); expect(evidence.actualPixels).toBeGreaterThan(100); expect(evidence.overlapPixels/Math.max(1,evidence.expectedPixels)).toBeGreaterThan(.94); expect(evidence.meanChannelDelta).toBeLessThan(12); expect(evidence.pixelsOverEight/Math.max(1,evidence.comparedPixels)).toBeLessThan(.15); expect(evidence.order).toEqual(['pick-label','selection-box','draft-panel','draft-label','paused-scrim','paused-title','paused-subtitle','build-cursor']);
});

test('1800-frame pointer, drag, build, pick, pause, and resize-style churn stays bounded',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','long E17 churn runs in primary Chromium'); test.setTimeout(180_000); await start(page); const result=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionChurnFrames(1800)); test.skip(!result.rendering.owned,'Pixi WebGL renderer unavailable'); expect(result.after).toEqual(result.before); expect(result.p95).toBeLessThanOrEqual(16.7); expect(result.p99).toBeLessThanOrEqual(33); expect(result.resources).toHaveLength(12); for(const value of result.resources){ expect(value.containersLive+value.containersIdle).toBeLessThanOrEqual(16); expect(value.graphicsActive+value.graphicsIdle).toBeLessThanOrEqual(8); expect(value.spritesActive+value.spritesIdle).toBeLessThanOrEqual(8); expect(value.textureCount).toBeLessThanOrEqual(16); expect(value.sourceBytes).toBeLessThanOrEqual(4*1024*1024); } const stable=result.resources.filter(value=>value.frame>1500); expect(stable.at(-1).textureAllocations-stable[0].textureAllocations).toBe(0); expect(stable.at(-1).textureDestroyCount-stable[0].textureDestroyCount).toBe(0);
});

test('reset releases every E17 source and restores normal ownership',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='chromium-desktop','focused E17 lifecycle evidence runs in primary Chromium'); await start(page); const initial=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); test.skip(!initial.owned,'Pixi WebGL renderer unavailable'); const reset=await page.evaluate(()=>window.__STATEFALL_TEST__.resetRendererResources().layers.interactionOverlays); expect(reset).toMatchObject({owned:false,entries:0,textureCount:0,textureRefs:0,sourceBytes:0}); expect(reset.textureDestroyCount).toBe(reset.textureAllocations); await page.evaluate(()=>window.__STATEFALL_TEST__.restoreRendererResources()); const restored=await page.evaluate(()=>window.__STATEFALL_TEST__.renderInteractionInventory('all').rendering); expect(restored.owned).toBe(true); expect(restored.textureRefs).toBe(restored.spritesActive);
});
