const {test,expect}=require('@playwright/test');
test('packaged tutorial runs from introduction through conquest without test hooks or account writes',async({page},info)=>{
 test.skip(info.project.name!=='chromium-desktop','Exact production package flow is covered once on Chromium; source tutorial covers all desktop engines.');test.setTimeout(120000);
 const errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET'&&r.method()!=='HEAD')writes.push(r.url());});
 await page.addInitScript(()=>{localStorage.setItem('statefall-audio',JSON.stringify({master:0,music:0}));});
 await page.goto('http://127.0.0.1:4174/');await page.locator('.learnChoice').click();await expect(page.locator('#tutorialIntro')).toBeVisible();await expect(page.locator('#training')).toHaveCount(0);await page.locator('#tutorialIntroStart').click();await expect(page.locator('#trainingTitle')).toHaveText('Your starting country');
 expect(await page.evaluate(()=>typeof window.__STATEFALL_TEST__)).toBe('undefined');
 const next=async()=>{await expect(page.locator('#trainingNext')).toBeEnabled();await page.locator('#trainingNext').click();};
 const center=async()=>{const b=await page.locator('#map').boundingBox();return {x:b.width/2,y:b.height/2};};
 await next();let b=await page.locator('#map').boundingBox();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.35);await page.mouse.wheel(0,1500);await next();await page.mouse.down();await page.mouse.move(b.x+b.width*.6+100,b.y+b.height*.35+50,{steps:8});await page.mouse.up();await next();await page.mouse.wheel(0,-1500);await next();await next();await next();await next();await page.locator('#focus').press('Home');await next();await page.locator('#ratio').press('Home');for(let n=0;n<30;n++)await page.locator('#ratio').press('ArrowRight');await next();
 await page.locator('#pauseBtn').click();await page.waitForTimeout(350);await page.locator('#pauseBtn').click();await next();await page.locator('#map').click({position:await center(),button:'right'});await next();await page.locator('#ctx [data-type=city]').click();await next();await page.keyboard.press('f');await next();await page.locator('#map').click({position:await center()});await page.keyboard.press('Escape');await next();await page.locator('#trainingNext').click();await expect(page.locator('#trainingFeedback')).toContainText('Construction finished',{timeout:25000});await next();await next();await expect(page.locator('#trainingTitle')).toHaveText('Attack a neighboring country');await page.locator('#map').click({position:await center()});await next();await page.locator('#trainingNext').click();await expect(page.locator('#trainingFeedback')).toContainText('Territory captured',{timeout:45000});await next();await next();await next();await expect(page.locator('#trainingCopy')).toContainText('gold in plunder');await expect(page.locator('#trainingCopy')).not.toContainText('awarded 0 gold');await next();await next();await next();await page.locator('#trainingGuide').click();await page.locator('#helpClose').click();await expect(page.locator('#trainingTitle')).toHaveText('Opening lesson complete');await page.locator('#trainingExit').click();await page.locator('#tutorialMenu').click();await expect(page.locator('.learnChoice')).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('statefall-board'))).toBe(null);expect(writes).toEqual([]);expect(errors).toEqual([]);
});
