"""Field test 7: the ten remaining revisions after Ken's second listening pass."""
prior_revised=revised.copy()
revised=set()
drill=excerpt('drill',0,1.06,110,6500,.008,.12)
workbed=excerpt('worksite',48.5,51.6,170,4800,.1,.5)
work=mix([(pan(drill,-.12),0,.85),(workbed,.1,.17),(pan(stretch_pitch(drill,.94),.14),1.55,.7)])
candidate('construction-start',fade(work,.015,.55),'Two clear cordless-drill bursts over quiet, irregular construction work.',['drill','worksite'])
descriptions['construction-start']=('Construction: work begins',descriptions['construction-start'][1],descriptions['construction-start'][2])
crowd=excerpt('stadium',.5,3.4,100,7800,.08,.65)
candidate('construction-city',crowd,'A broad sports-crowd cheer, replacing the small group yelling.',['stadium'])
drive=excerpt('liftservo',11,14.4,65,4500,.1,.25)
small_drive=excerpt('liftservo',16,17.3,130,5800,.06,.22)
candidate('construction-battery',fade(stretch_pitch(drive,.85),.12,.45),'A sustained loaded gear drive for a large gun rotating into position.',['liftservo'])
candidate('construction-shore',mix([(small_drive,0,.9),(fade(mechanical,.01,.15),1.13,.1)]),'A compact powered traverse ending in a light mechanical stop.',['liftservo','impacts'])
candidate('construction-sam',mix([(fade(stretch_pitch(small_drive,1.15),.03,.2),0,.75),(fade(filt(contactor[:int(.22*SR)],160,3200),.003,.12),1.01,.16)]),'A brisk launcher elevation movement and one restrained locking contact.',['liftservo','contactor'])
candidate('construction-silo',fade(natural['construction-silo'],.08,1.05),'Pressure venting with a full one-second fade into silence.',['steam'])
pilot=excerpt('pilotvoice',3.5,5.9,380,2300,.04,.28)
candidate('construction-flightops',mix([(radio[:int(.13*SR)],0,.08),(pilot,.11,.85)]),'A different performer: muffled pilot radio speech with a brief key-in.',['pilotvoice','radio'])
boots_real=excerpt('marching',.35,3.25,65,7000,.025,.35)
candidate('construction-troopcmd',boots_real,'Continuous marching foley with foot scuffs and overlapping steps; no repeated impact hits.',['marching'])
radar_ping=fade(filt(stretch_pitch(ping,.92),300,3300)[:int(1.35*SR)],.008,.6)
candidate('construction-radar',radar_ping,'A softer single sweep ping with a shorter, smoothly falling tail.',['ping'])
deep_ping=fade(filt(stretch_pitch(ping,.7),160,2600)[:int(1.65*SR)],.008,.7)
candidate('construction-lradar',mix([(deep_ping,0,.85),(fade(deep_ping[:int(.8*SR)],.008,.35),1.05,.32)]),'A low double return: distinct from the standard radar single ping.',['ping'])
revised3=revised.copy()
revised=prior_revised
