import {HELP_ART} from './help-art.mjs';
import {renderHelpRoster} from './help-roster.mjs';
import {HELP_REFERENCE} from './help-reference.mjs';
import {HELP_RELEASE} from './help-release.mjs';
import {GAME_VERSION,GAME_BUILD} from './config/build.js';
import {DIFFS} from './sim/rules.mjs';

const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const HELP_GUIDE_CSS=`
.sf-guide{color:#e8eef4;background:#101e2a;font:16px/1.65 "Segoe UI",system-ui,sans-serif;padding:clamp(18px,4vw,38px);border-radius:14px;max-width:1100px;margin:auto;text-align:left;overflow-wrap:anywhere;box-sizing:border-box}
.sf-guide *{box-sizing:border-box}.sf-guide p{margin:0 0 16px;color:#becdda}.sf-guide a{color:#a7ceff;text-decoration:underline}.sf-guide a:focus-visible,.sf-guide summary:focus-visible{outline:3px solid #ffd27a;outline-offset:4px}
.sf-guide .sf-kicker{display:block;color:#ffd27a;text-transform:uppercase;font-size:11px;font-weight:750;letter-spacing:2px;margin-bottom:12px}
.sf-guide .sf-lead{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);align-items:center;gap:24px;border-bottom:1px solid #35495b;padding-bottom:26px;margin-bottom:30px}
.sf-guide .sf-lead h2{font-size:clamp(27px,4vw,43px);line-height:1.1;letter-spacing:-1px;color:#fff;margin:0 0 18px;font-weight:800;text-transform:none}
.sf-guide .sf-lead p{font-size:17px;max-width:52ch;margin:0}.sf-guide .sf-lead figure{margin:0;background:radial-gradient(ellipse,#3c5265,#152837 70%);border-radius:50%;min-width:0}
.sf-guide .sf-lead img{display:block;width:100%;height:230px;object-fit:contain;filter:drop-shadow(0 12px 10px #0008)}
.sf-guide h3,#help .sf-guide h3{font-size:23px;line-height:1.25;color:#fff;margin:30px 0 16px;letter-spacing:-.3px;text-transform:none}
.sf-guide h4{color:#fff;font-size:17px;line-height:1.3;margin:0 0 9px}.sf-guide .sf-facts{display:flex;flex-wrap:wrap;gap:18px 32px;margin:0 0 30px;padding:0 0 22px;border-bottom:1px solid #35495b}.sf-guide .sf-facts div{flex:1;min-width:115px}.sf-guide .sf-facts strong{display:block;font-size:27px;line-height:1.3;color:#ffd27a}.sf-guide .sf-facts span{font-size:12px;color:#becdda}
.sf-guide .sf-steps{list-style:none;padding:0;margin:0;counter-reset:move}.sf-guide .sf-steps li{counter-increment:move;position:relative;padding:0 0 22px 53px;margin:0}.sf-guide .sf-steps li:before{content:counter(move,decimal-leading-zero);position:absolute;left:0;top:0;color:#ffd27a;font-size:22px;font-weight:750}.sf-guide .sf-steps p{margin:0}.sf-guide .sf-steps li+li{border-top:1px solid #263b4b;padding-top:18px}.sf-guide .sf-steps li+li:before{top:18px}
.sf-guide .sf-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px;margin:20px 0}.sf-guide .sf-note{border-left:3px solid #7fb3ff;padding:5px 0 5px 18px}.sf-guide .sf-note p:last-child{margin-bottom:0}
.sf-guide .sf-tactic{display:grid;grid-template-columns:130px minmax(0,1fr);gap:22px;align-items:center;padding:22px 0;border-top:1px solid #35495b}.sf-guide .sf-tactic img{width:130px;height:110px;object-fit:contain}.sf-guide .sf-tactic h3{margin:0 0 8px;font-size:22px}.sf-guide .sf-tactic p{margin:0}
.sf-guide details{border-top:1px solid #35495b;padding:0;margin:0}.sf-guide details:last-child{border-bottom:1px solid #35495b}.sf-guide summary{padding:16px 8px;cursor:pointer;color:#e8eef4;font-weight:650;font-size:15px}.sf-guide details[open] summary{color:#ffd27a}.sf-guide details>div{padding:0 10px 18px;max-width:78ch;font-size:15px}.sf-guide details p:last-child{margin-bottom:0}.sf-guide kbd{border:1px solid #526778;border-radius:4px;padding:1px 5px;color:#fff;background:#213445;font:inherit;font-size:12px}.sf-guide .sf-release{background:#203447;border-radius:10px;padding:24px;margin:24px 0}.sf-guide .sf-release h3{margin:0 0 16px}.sf-guide .sf-release ul{padding-left:20px;margin:0}.sf-guide .sf-release li{margin:12px 0}.sf-guide .sf-meta{font-size:12px;color:#90a6ba}.sf-guide .sf-nav{display:flex;flex-wrap:wrap;gap:8px 18px;margin-bottom:25px;font-size:14px}.sf-guide .sf-nav a[aria-current]{color:#ffd27a}
@media(max-width:600px){.sf-guide{padding:20px 16px}.sf-guide .sf-lead{grid-template-columns:1fr;gap:8px}.sf-guide .sf-lead figure{order:-1;background:none}.sf-guide .sf-lead img{height:160px}.sf-guide .sf-columns{grid-template-columns:1fr}.sf-guide .sf-tactic{grid-template-columns:1fr;gap:12px}.sf-guide .sf-tactic img{width:150px;height:105px;margin:auto}.sf-guide .sf-lead h2{font-size:32px}}
`;
const steps=items=>`<ol class="sf-steps">${items.map(([title,body])=>`<li><h4>${title}</h4><p>${body}</p></li>`).join('')}</ol>`;
const note=(title,body)=>`<section class="sf-note"><h4>${title}</h4><p>${body}</p></section>`;
const details=(title,body)=>`<details><summary>${title}</summary><div>${body}</div></details>`;
const reference=tab=>`<h3>Keep this handy</h3><p>Open a topic for controls, timings and the detailed rules.</p>${(HELP_REFERENCE[tab]||[]).map(r=>details(r.title,`<p>${r.body}</p>`)).join('')}`;
const leads={
 basics:['Your first campaign','Build a nation. Hold the world.','Start with one small country. Grow through nearby neutrals, build an economy, then use land, sea and air power to hold 72% of the map.','city'],
 build:['Construction field guide','Build for your next move.','An economy funds the war. Defenses buy time. Command buildings handle routine orders so you can watch the front.','factory'],
 ships:['Naval field guide','Control the crossing.','Your fleet protects trade, carries the fight to new shores and opens defended beaches. Choose ships for the threat on the route.','battleship'],
 air:['Air power field guide','Win the sky before the strike.','Fighters make space for bombers and troop transports. Scout the route, protect your airfields and keep an eye on enemy patrols.','fighter'],
 systems:['Combined arms','Make the pieces work together.','A strong unit helps. A protected economy, safe supply route and well-timed attack win campaigns.','shield'],
 garrisons:['A different kind of war','Your troops have a home.','With Garrisons enabled, each connected area has its own army. A huge reserve across the sea cannot defend a thin beachhead until it gets there.','heavytransport'],
 modes:['Choose your campaign','Change the opening. Change the war.','Start gently, jump into a developed world or add fog and local armies. Each combination has its own leaderboard class.','radar'],
 about:['Statefall · Real-time strategy','Small nation. Big ambitions.','A browser strategy game about expansion, timing and the decisions between battles. Build your country, outmaneuver nine rivals and make the map your own.','cruiser']
};
export function renderHelpGuide(tab,{resolveImage=key=>HELP_ART[key],loading='eager',nav=''}={}){
 const data=leads[tab];if(!data)throw new Error('Unknown help tab: '+tab);
 const art=(key,alt)=>`<img src="${esc(resolveImage(key))}" width="480" height="360" alt="${esc(alt)} — in-game artwork">`;
 const tactic=(key,title,body)=>`<section class="sf-tactic">${art(key,title)}<div><h3>${title}</h3><p>${body}</p></div></section>`;
 let content='';
 if(tab==='basics')content=`<div class="sf-facts"><div><strong>72%</strong><span>Land to win</span></div><div><strong>9</strong><span>Rival nations</span></div><div><strong>15–25 min</strong><span>Typical match</span></div></div><h3>Your opening, in five moves</h3>${steps([
 ['Read the neighborhood','Zoom in. Look for weak neutral neighbors and a route to the coast. Compare troop density, not just country size.'],
 ['Expand without emptying your army','Set <b>Send into attack</b>, then left-click a bordering country. Keep a reserve: a thin army makes you an inviting target.'],
 ['Turn land into income','Right-click your land to build cities and factories. Place them close enough to connect supply lines; build a port when the sea becomes your next front.'],
 ['Protect the next crossing','Scout the coast and escort transports. A fleet or bomber strike can weaken defenses before your troops arrive.'],
 ['Consolidate, then push again','Hold connected territory, repair key defenses and finish a landmass for its bonus. Watch your borders while you work toward 72%.']
 ])}<h3>The controls you will use most</h3><div class="sf-columns">${note('Left-click · attack','Click a bordering country. The attack uses the share selected by your attack slider. Click again to reinforce.')}${note('Right-click · give an order','Your land opens construction. Foreign land opens attacks and diplomacy. Water opens naval orders.')}${note('Scroll & drag · explore','Scroll to zoom and drag to pan. Zoom closer to read terrain and pick your landing.')}${note('Space · pause','Pause without covering the battlefield: pan, zoom and inspect. Space or Esc resumes. Enable Paused orders before a match to build and give orders while time is stopped. Opening this guide pauses a running single-player match; closing it restores your previous state.')}</div>${reference(tab)}`;
 if(['build','ships','air'].includes(tab))content=renderHelpRoster(tab,resolveImage,loading)+reference(tab);
 if(tab==='systems')content=tactic('factory','Fund the next offensive','Connect factories to cities and ports. Keep enough troops to hold your borders while shifting the economy toward gold for expensive buildings.')+tactic('heavytransport','Build an alliance that helps','Right-click a nation for a pact or alliance. Allies share protection and can exchange aid. Send gold to fund a recovery, or troops to support a pressured front; protect gifts that travel by sea.')+tactic('sam','Layer your defenses','SAMs intercept missiles. Shields absorb the hits that get through. Shore guns punish landings, while fighters stop bombers. No single defense answers every threat.')+tactic('bomber','Create an opening, then use it','Scout, suppress defenses with bombardment or bombs, then commit troops. A damaged coast is useful only if your force reaches it before the defender recovers.')+tactic('truck','Delegate the routine work','Engineering command repairs connected territory. Troop command helps reinforce Garrisons areas. Missile command and flight operations automate attacks; check their sidebar toggles and your reserves.')+`<h3>Sound, saves & score</h3><div class="sf-columns">${note('Choose your soundtrack','The Sound panel has separate music and effects controls. Use the music toggle to mute music. The authored soundtrack follows the situation; Radio lets you choose what plays.')}${note('Keep your campaign','Sign in on the site for account saves and replays. Use Games & replays to resume or watch a match. Leaderboards separate different modes and starting conditions.')}</div>${reference(tab)}`;
 if(tab==='garrisons')content=`<div class="sf-columns">${note('Standard · one army pool','Your nation draws from a shared troop total. Holdings across water use the same national army.')}${note('Garrisons · local armies','Each connected area draws from its own troops. Seas, rivers and lost corridors can leave an area isolated.')}</div><h3>Reinforce a beachhead</h3>${steps([['Choose the destination','Right-click your own area and choose <b>Reinforce this area from an area you click</b>.'],['Choose the source','Click the area that can spare troops. The order sends the slider’s share of that area’s garrison, not your entire national army.'],['Protect the journey','If the areas do not border, troops travel by transport. Scout the route, escort the convoy and keep a reserve at home.']])}${tactic('city','Grow where it matters','Land growth is distributed by area. A city’s completion bonus goes to its own area, so a new city can strengthen an isolated foothold.')}${tactic('heavytransport','The sea is a supply line','A Port II serving the source area unlocks heavy transports. Armor helps, but escorts and a cleared landing still matter. Troop command can automate reinforcement logistics.')}<h3>Connections change the balance</h3><p>Join two areas by capturing a continuous land route and their garrisons merge. Lose a corridor and they split. A river crossing needs a transport unless you can capture a land route around the water.</p><p>Attacks draw from the bordering area; surviving troops return there. Bombardment and missile losses come from the area that was hit. Use the sidebar’s area list and map counts to find weak borders.</p>${reference(tab)}`;
 if(tab==='modes')content=`<h3>Pick an opening</h3><p>Quick start, Risky start and End game are mutually exclusive. Leave all three off for a standard start.</p>${steps([['Quick start · get to the fronts','Start with a larger connected holding, 4× troops and 5× gold. Choose this when you want to reach building and naval decisions sooner.'],['Risky start · draft your footholds','Take turns choosing neutral countries before the war. Cluster your picks for a connected base, or spread them to open several fronts.'],['End game · the map is already divided','No neutrals: everyone begins with 45,000 troops and 15,000 gold. Expect immediate border pressure and big investment decisions.']])}<h3>Add a different challenge</h3><div class="sf-columns">${note('Fog of war','Scout before committing. Ownership stays visible, but enemy troops and assets outside your vision are hidden. Radar, spy planes and satellites become valuable.')}${note('Garrisons','Manage local armies and supply routes. A strong home country does not automatically protect distant land.')}${note('Teams','Split nations into two, three or four permanent teams. Shared vision, protection and aid help the team reach a combined 72% of land.')}${note('Billionaire','You alone start with one billion troops and gold. Try expensive forces immediately; gold and troop gifts to allies support amounts up to one billion.')}${note('Instant build','Skip most construction and shipyard timers. Shields and level II upgrades keep their timers, and repairs still take time.')}${note('Paused orders','Plan and issue orders on a stopped clock. This advantage gets its own leaderboard class.')}</div><h3>Choose the opposition</h3><p>Difficulty changes both bot behavior and its resource advantages.</p>${Object.values(DIFFS).map(d=>details(esc(d.label||d.name),`<p>${esc(d.desc)}</p>`)).join('')}<h3>Make it your match</h3><p>Adjust starting troops and gold, remove the troop cap or restrict available buildings and weapons. Restrictions apply to everyone. Reuse a map seed to retry the same opening.</p>`;
 if(tab==='about')content=`<div class="sf-facts"><div><strong>12 maps</strong><span>Generated and real-world settings</span></div><div><strong>Land · Sea · Air</strong><span>One connected campaign</span></div></div>${tactic('battleship','A world worth zooming into','Detailed terrain, buildings, ships and aircraft make the battlefield easier to read up close. Zoom out to plan the campaign, then in to follow a landing or inspect a strongpoint.')}${tactic('radar','Choose how you fight','Play a standard land grab, draft your starting countries, face an established world or add fog, Garrisons and teams. Difficulty changes how your opponents respond.')}
 <section class="sf-release" data-release="${esc(GAME_VERSION)}"><span class="sf-kicker">What’s new · ${esc(GAME_VERSION)}</span><h3>${esc(HELP_RELEASE.title)}</h3><ul>${HELP_RELEASE.changes.map(c=>`<li>${esc(c)}</li>`).join('')}</ul></section><h3>Your matches, your story</h3><p>Sign in on the website to keep account saves, revisit replays and build a profile across matches. Finished campaigns can become shareable credits with your highlights and dedication. Browser-local records belong to that browser; account features require a site connection.</p><h3>Sound with a purpose</h3><p>An authored soundtrack, distinct unit effects and alerts help tell the story of the battle. Adjust music and effects separately in the Sound panel, or mute them when you want a quieter campaign.</p>${details('Credits & audio attribution','<p>Designed and built by That Company. Map data: Natural Earth (public domain).</p><p>Tank sound excerpts derive from <a href="https://freesound.org/people/Department64/sounds/608126/">FXTankMix-a.wav by Department64</a>, used under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Excerpts were filtered, level-adjusted and mixed. No endorsement is implied. Additional audio source credits accompany the game assets.</p>')}<p class="sf-meta" style="margin-top:18px">Game ${esc(GAME_VERSION)} · Build ${esc(GAME_BUILD)}</p>`;
 return `<style>${HELP_GUIDE_CSS}</style><div class="sf-guide" data-guide="${tab}">${nav}<header class="sf-lead"><div><span class="sf-kicker">${data[0]}</span><h2>${data[1]}</h2><p>${data[2]}</p></div><figure>${art(data[3],data[0])}</figure></header>${content}</div>`;
}
