// Exported from locked review decisions; rerun tools/export-approved-audio.py.
export const SOUND_ASSETS = {
  "attack-start": {url:new URL("./assets/attack-start.ogg", import.meta.url).href, seconds:1.07},
  "attack-progress": {url:new URL("./assets/attack-progress.ogg", import.meta.url).href, seconds:11.5},
  "attack-stalled": {url:new URL("./assets/attack-stalled.ogg", import.meta.url).href, seconds:1.25},
  "attack-failed": {url:new URL("./assets/attack-failed.ogg", import.meta.url).href, seconds:2.3},
  "capture-neutral": {url:new URL("./assets/capture-neutral.ogg", import.meta.url).href, seconds:2.05},
  "capture-enemy": {url:new URL("./assets/capture-enemy.ogg", import.meta.url).href, seconds:2.55},
  "enemy-eliminated": {url:new URL("./assets/enemy-eliminated.ogg", import.meta.url).href, seconds:7.3},
  "construction-start": {url:new URL("./assets/construction-start.ogg", import.meta.url).href, seconds:3.2},
  "construction-city": {url:new URL("./assets/construction-city.ogg", import.meta.url).href, seconds:2.9},
  "construction-factory": {url:new URL("./assets/construction-factory.ogg", import.meta.url).href, seconds:2.15},
  "construction-port": {url:new URL("./assets/construction-port.ogg", import.meta.url).href, seconds:1.45},
  "construction-fort": {url:new URL("./assets/construction-fort.ogg", import.meta.url).href, seconds:2.26},
  "construction-sam": {url:new URL("./assets/construction-sam.ogg", import.meta.url).href, seconds:1.23},
  "construction-silo": {url:new URL("./assets/construction-silo.ogg", import.meta.url).href, seconds:2.2},
  "construction-command": {url:new URL("./assets/construction-command.ogg", import.meta.url).href, seconds:2.0},
  "construction-shield": {url:new URL("./assets/construction-shield.ogg", import.meta.url).href, seconds:2.6},
  "construction-battery": {url:new URL("./assets/construction-battery.ogg", import.meta.url).href, seconds:4.0},
  "construction-shore": {url:new URL("./assets/construction-shore.ogg", import.meta.url).href, seconds:1.4},
  "construction-bertha": {url:new URL("./assets/construction-bertha.ogg", import.meta.url).href, seconds:2.98},
  "construction-airfield": {url:new URL("./assets/construction-airfield.ogg", import.meta.url).href, seconds:3.6},
  "construction-flightops": {url:new URL("./assets/construction-flightops.ogg", import.meta.url).href, seconds:2.51},
  "construction-subbase": {url:new URL("./assets/construction-subbase.ogg", import.meta.url).href, seconds:3.5},
  "construction-engcmd": {url:new URL("./assets/construction-engcmd.ogg", import.meta.url).href, seconds:1.28},
  "construction-troopcmd": {url:new URL("./assets/construction-troopcmd.ogg", import.meta.url).href, seconds:2.9},
  "construction-radar": {url:new URL("./assets/construction-radar.ogg", import.meta.url).href, seconds:1.35},
  "construction-lradar": {url:new URL("./assets/construction-lradar.ogg", import.meta.url).href, seconds:1.85},
  "construction-jammer": {url:new URL("./assets/construction-jammer.ogg", import.meta.url).href, seconds:2.05},
  "construction-satellite": {url:new URL("./assets/construction-satellite.ogg", import.meta.url).href, seconds:1.08},
  "missile-launch": {url:new URL("./assets/missile-launch.ogg", import.meta.url).href, seconds:5.04},
  "sam-launch": {url:new URL("./assets/sam-launch.ogg", import.meta.url).href, seconds:1.48},
  "sam-intercept": {url:new URL("./assets/sam-intercept.ogg", import.meta.url).href, seconds:2.75},
  "nuclear-detonation": {url:new URL("./assets/nuclear-detonation.ogg", import.meta.url).href, seconds:7.05},
  "incoming-warning": {url:new URL("./assets/incoming-warning.ogg", import.meta.url).href, seconds:3.8},
  "artillery": {url:new URL("./assets/artillery.ogg", import.meta.url).href, seconds:3.36},
  "shell-impact": {url:new URL("./assets/shell-impact.ogg", import.meta.url).href, seconds:2.09},
  "ship-sinking": {url:new URL("./assets/ship-sinking.ogg", import.meta.url).href, seconds:5.08},
  "layer-machineguns": {url:new URL("./assets/layer-machineguns.ogg", import.meta.url).href, seconds:1.5981666666666667},
  "layer-tracks": {url:new URL("./assets/layer-tracks.ogg", import.meta.url).href, seconds:11.3},
  "layer-artillery": {url:new URL("./assets/layer-artillery.ogg", import.meta.url).href, seconds:2.78},
};
export const SCORE_TRACKS = [
  {"id": "1325bd141e85", "title": "Ashes of Victory", "roles": ["victory"], "seconds": 139.03, "url": "/wp-content/uploads/statefall/audio/65232d55-Ashes-of-Victory.mp3?v=1788906794"},
  {"id": "9f284475d72f", "title": "Drift and Divide", "roles": ["building"], "seconds": 204.72, "url": "/wp-content/uploads/statefall/audio/42a54b5f-Drift-and-Divide.mp3?v=1788906813"},
  {"id": "aa6c0f925c88", "title": "Fallen Banners", "roles": ["building", "defeat"], "seconds": 240.48, "url": "/wp-content/uploads/statefall/audio/c1bfaf04-Fallen-Banners.mp3?v=1788906749"},
  {"id": "55c5ac4f5cfb", "title": "Fallen Field", "roles": ["building", "defeat"], "seconds": 119.69, "url": "/wp-content/uploads/statefall/audio/abbdbdec-Fallen-Field.mp3?v=1788906927"},
  {"id": "ae48f45e837e", "title": "Iron Banner March", "roles": ["battle", "victory"], "seconds": 158.4, "url": "/wp-content/uploads/statefall/audio/02447876-Iron-Banner-March.mp3?v=1788906713"},
  {"id": "105db81895da", "title": "Iron Coast", "roles": ["building", "defeat"], "seconds": 193.13, "url": "/wp-content/uploads/statefall/audio/1a64ff8f-Iron-Coast.mp3?v=1788907012"},
  {"id": "a31ac2d4f53c", "title": "Iron Horizon", "roles": ["building", "victory"], "seconds": 179.35, "url": "/wp-content/uploads/statefall/audio/f6d91ae9-Iron-Horizon.mp3?v=1788907052"},
  {"id": "9c6aaa97b352", "title": "Iron March", "roles": ["menu", "building", "victory"], "seconds": 180.77, "url": "/wp-content/uploads/statefall/audio/b488cdf5-Iron-March.mp3?v=1788906678"},
  {"id": "55d932c0cc04", "title": "Last Banner Falls", "roles": ["building", "defeat"], "seconds": 183.72, "url": "/wp-content/uploads/statefall/audio/c3603fc7-Last-Banner-Falls.mp3?v=1788906777"},
  {"id": "342198cf7330", "title": "Last Honor Call", "roles": ["building", "defeat"], "seconds": 199.44, "url": "/wp-content/uploads/statefall/audio/0434532c-Last-Honor-Call.mp3?v=1788906966"},
  {"id": "8cdcf5e0a530", "title": "Salvo", "roles": ["battle"], "seconds": 196.13, "url": "/wp-content/uploads/statefall/audio/63370d50-Salvo.mp3?v=1788906694"},
  {"id": "9eabe6d66db1", "title": "Seventy-Two Percent", "roles": ["building", "battle"], "seconds": 203.83, "url": "/wp-content/uploads/statefall/audio/c504875f-Seventy-Two-Percent.mp3?v=1788906910"},
  {"id": "fcfb2fd761fb", "title": "Siege Heartbeat (1)", "roles": ["building", "defeat"], "seconds": 213.96, "url": "/wp-content/uploads/statefall/audio/2fa4ea9d-Siege-Heartbeat-1.mp3?v=1788906854"},
  {"id": "3a7a9d789b4f", "title": "Siege Heartbeat", "roles": ["building", "battle"], "seconds": 169.13, "url": "/wp-content/uploads/statefall/audio/db6d886b-Siege-Heartbeat.mp3?v=1788906888"},
  {"id": "3d4bb220eb9f", "title": "Siege Map Drift", "roles": ["building"], "seconds": 183.36, "url": "/wp-content/uploads/statefall/audio/e72d488f-Siege-Map-Drift.mp3?v=1788906837"},
  {"id": "626ab7e39343", "title": "Statefall", "roles": ["menu", "victory"], "seconds": 154.75, "url": "/wp-content/uploads/statefall/audio/ec1ec3b3-Statefall.mp3?v=1788906658"},
];
