import {createClassicMotionPainter} from '../../game/src/rendering/classic-motion-effects.mjs';
const paintMotion=createClassicMotionPainter();
import {createClassicBattlefield} from '../../game/src/rendering/classic-battlefield.mjs';
import {STRUCT,SHIPS,UPGRADE} from '../../game/src/sim/rules.mjs';
const details={city:'Warm occupied windows. Action: lights spread across the three wings.',factory:'Slow exhaust; a small production light.',port:'Dock lights and gentle water ripples.',sam:'Readiness indicator. Action: angled rocket, motor flame and smoke trail.',silo:'Readiness indicator. Action: vertical rocket launch and broad exhaust.',fort:'Quiet perimeter lights. Action: a defensive perimeter pulse.',command:'Mast status beacon. Action: three short uplink pulses from the dish.',shield:'Soft core pulse. Action: shield impact ripple.',battery:'Action: muzzle flash and fading smoke.',shore:'Action: alternating barrel bursts and muzzle smoke.',bertha:'Action: heavy muzzle flash and lingering smoke.',airfield:'Quiet runway lights. Action: a bright departure-light sequence.',flightops:'Control-tower window glow. Action: a sweep across the glass.',subbase:'Dock ripples and a small service light.',engcmd:'Workshop lights. Action: repair sparks.',troopcmd:'Mast beacon. Action: a short radio transmission from the antenna.',radar:'Status light. Action: expanding scan cue.',lradar:'Slow status pulse. Action: wider scan cue.',jammer:'Alternating equipment lights. Action: interference rings.',satellite:'Tracking light. Action: rising launch plume.',sub:'Faint propulsion bubbles. Action: torpedo bubbles.',hunter:'Faint propulsion bubbles. Action: sonar cue and torpedo bubbles.',rship:'Radar indicator and fine wake. Action: scan cue.',privateer:'Engine exhaust and wake. Action: boarding line.',scout:'Narrow wake. Action: quick muzzle flash.',warship:'Stern turbulence and exhaust. Action: gun flash.',cruiser:'Slow wake. Action: staggered launch exhaust.',battleship:'Broad wake. Action: heavy gun flash.',transport:'Stern wake. Action: landing activity.',heavytransport:'Broad wake and exhaust. Action: defensive gun flash.',merchant:'Exhaust and steady wake. Action: cargo activity.',fighter:'Bright red and green wingtip lights.',bomber:'Wingtip lights. Action: short bomb-release sequence.',carrier:'Wingtip lights. Action: parachute drop.',spy:'Wingtip lights. Action: reconnaissance cue.',truck:'Quiet exhaust. Action: welding sparks.'};
const specs=[...Object.entries(STRUCT).map(([key,v])=>({key,title:v.label,group:'Buildings',level:1})),...Object.entries(SHIPS).map(([key,v])=>({key,title:v.label,group:'Units'})),...[['transport','Transport ship'],['heavytransport','Heavy transport'],['merchant','Merchant ship'],['fighter','Stealth fighter'],['bomber','Stealth bomber'],['carrier','Troop transport aircraft'],['spy','Spy plane'],['truck','Repair truck']].map(([key,title])=>({key,title,group:'Units'})),...Object.entries(UPGRADE).flatMap(([key,v])=>Array.from({length:(v.max||2)-1},(_,i)=>({key,title:STRUCT[key].label+' '+['II','III'][i],group:'Upgrades',level:i+2})))];
const sea=new Set([...Object.keys(SHIPS),'transport','heavytransport','merchant']);
const air=new Set(['fighter','bomber','carrier','spy']);
const art=await createClassicBattlefield(),cards=[];
const observer=new IntersectionObserver(entries=>{for(const entry of entries){const card=cards.find(c=>c.element===entry.target);if(card)card.visible=entry.isIntersecting;}},{rootMargin:'80px'});
for(const spec of specs){const {key,title,group,level}=spec;const element=document.createElement('article');element.innerHTML=`<canvas aria-label="${title} animation preview"></canvas><section><small>${group}</small><h2>${title}</h2><p>${details[key]}${group==='Upgrades'?(key==='port'?' Action: added defensive gun.':key==='airfield'?' Action: local shield impact.':' Extra perimeter lights.') : ''}</p><button class="try-action">Preview action</button></section>`;document.querySelector('#grid').append(element);const canvas=element.querySelector('canvas');canvas.width=720;canvas.height=440;const base=document.createElement('canvas');base.width=720;base.height=440;const c=base.getContext('2d');c.scale(2,2);let painted;if(sea.has(key))painted=art.paintShip(c,key,180,116,0,57,'#62a5d6');else if(air.has(key))painted=art.paintAircraft(c,{type:key,x:0,y:0,heading:0,color:'#62a5d6'},{x:180,y:116,scale:28});else if(key==='truck')painted=art.paintTruck(c,{x:0,y:0,heading:0,color:'#62a5d6'},{x:180,y:128,scale:28});else painted=art.paintStructure(c,key,180,166,62,'#62a5d6',level);if(!painted)throw Error('Missing roster art: '+key);const card={...spec,canvas,base,element,visible:true,actionAt:-100};element.querySelector('button').onclick=()=>{card.actionAt=time;};cards.push(card);observer.observe(element);}
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches,still=false,time=0,last=0,actionAt=-100,intensity=.8,scale=1,frames=0,cost=0;
const pause=document.querySelector('#pause');pause.textContent=paused?'Resume':'Pause';pause.onclick=()=>{paused=!paused;pause.textContent=paused?'Resume':'Pause';};
document.querySelector('#action').onclick=()=>{actionAt=time;};
document.querySelector('#filter').onchange=e=>{for(const card of cards)card.element.hidden=e.target.value!=='All'&&card.group!==e.target.value;};document.querySelector('#compare').onclick=e=>{still=!still;e.target.textContent=still?'Show animations':'Show still artwork';};document.querySelector('#intensity').oninput=e=>intensity=+e.target.value;document.querySelector('#scale').onchange=e=>scale=+e.target.value;
function paint(card,index){const c=card.canvas.getContext('2d'),k=card.key,t=time+index*.71,age=time-Math.max(actionAt,card.actionAt),active=age>=0&&age<2.5; c.setTransform(2,0,0,2,0,0);const water=sea.has(k);c.fillStyle=water?'#193748':'#283632';c.fillRect(0,0,360,220);c.strokeStyle='#ffffff06';c.lineWidth=1;for(let x=0;x<360;x+=24){c.beginPath();c.moveTo(x,0);c.lineTo(x,220);c.stroke();}c.save();c.translate(180,120);c.scale(scale,scale);c.translate(-180,-120);
 if(!still&&water){for(let j=0;j<7;j++){const f=(t*.35+j/7)%1;c.strokeStyle=`rgba(163,207,213,${(1-f)*.16*intensity})`;c.beginPath();c.ellipse(110-f*27,119,3+f*8,2+f*7,0,0,Math.PI*2);c.stroke();}}
 c.drawImage(card.base,0,0,360,220);
 if(!still)paintMotion(c,{key:k,level:card.level,time:t,age,scale,strength:intensity});c.restore();}

function frame(now){if(!paused&&!document.hidden)time+=Math.min((now-last)/1000||0,.05);last=now;const start=performance.now();if(!document.hidden)cards.forEach((card,i)=>{if(card.visible&&!card.element.hidden)paint(card,i);});cost+=performance.now()-start;frames++;if(frames%30===0){document.querySelector('#status').textContent=`${cards.length} previews · ${(cost/frames).toFixed(2)} ms average draw · ${paused?'Paused':still?'Still artwork':'Animating'}`;}requestAnimationFrame(frame);}requestAnimationFrame(frame);document.body.dataset.ready='true';
