import {paintSam,samSequence,loadSamArt} from './sam-sequence.mjs';
import {siloSequence} from '../../game/src/rendering/classic-silo-sequence.mjs';
import {createClassicBattlefield} from '../../game/src/rendering/classic-battlefield.mjs';
import {paintLaunch,paintMushroomCloud} from '../../game/src/rendering/classic-combat-effects.mjs';
const art=await createClassicBattlefield();await loadSamArt();let effect="sam",target=-Math.PI/4;let age=0,last=null,paused=true,scale=1;
const reduced=document.querySelector('#reduce');reduced.checked=matchMedia('(prefers-reduced-motion: reduce)').matches;paused=true;
const canvases=[...document.querySelectorAll('canvas')];for(const c of canvases){c.width=840;c.height=720;}
function paint(){for(const cv of canvases){if(cv.id!==effect)continue;const c=cv.getContext('2d');c.setTransform(2,0,0,2,0,0);c.fillStyle='#24342f';c.fillRect(0,0,420,360);c.strokeStyle='#ffffff07';c.lineWidth=1;for(let j=0;j<420;j+=24){c.beginPath();c.moveTo(j,0);c.lineTo(j,360);c.stroke();}c.save();c.translate(210,270);c.scale(scale,scale);c.translate(-180,-166);if(cv.id==='sam'){c.save();c.strokeStyle='#89becb88';c.lineWidth=1;const tx=180+Math.cos(target)*95*Math.cos(.78),ty=153+Math.sin(target)*95*Math.cos(.78)*.55-(27+95*Math.sin(.78))*.9;c.beginPath();c.arc(tx,ty,5,0,Math.PI*2);c.moveTo(tx-9,ty);c.lineTo(tx+9,ty);c.moveTo(tx,ty-9);c.lineTo(tx,ty+9);c.stroke();c.restore();paintSam(c,{age,target,reducedMotion:reduced.checked});}else if(cv.id==='nuke')paintMushroomCloud(c,{x:180,y:166,radius:110,age,reducedMotion:reduced.checked});else{art.paintStructure(c,cv.id,180,166,62,'#62a5d6',1);if(!reduced.checked)paintLaunch(c,{kind:cv.id,age});}c.restore();}document.querySelector('#seek').value=age;document.querySelector('#status').textContent=age.toFixed(2)+' s · '+(effect==='sam'?samSequence(age,target).phase:siloSequence(age).phase);document.querySelector('#pause').textContent=paused?'Resume':'Pause';}
document.querySelector('#replay').onclick=()=>{age=0;paused=reduced.checked;paint();};document.querySelector('#pause').onclick=()=>paused=!paused;document.querySelector('#seek').oninput=e=>{age=+e.target.value;paused=true;paint();};document.querySelector('#scale').onchange=e=>{scale=+e.target.value;paint();};reduced.onchange=()=>{paused=true;paint();};
function frame(now){if(last!==null&&!paused&&!document.hidden)age=Math.min(9,age+Math.min(.05,(now-last)/1000));last=now;paint();requestAnimationFrame(frame);}requestAnimationFrame(frame);document.body.dataset.ready='true';

document.querySelector('#bearing').onchange=e=>{target=+e.target.value*Math.PI/180;age=0;paused=true;paint();};document.querySelector('#effect').onchange=e=>{effect=e.target.value;for(const cv of canvases)cv.closest('article').hidden=cv.id!==effect;document.querySelector('#bearing-label').hidden=effect!=='sam';age=0;paused=true;paint();};
