const fs=require('node:fs'),path=require('node:path'),{spawnSync,spawn}=require('node:child_process'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'docs/evidence/comprehensive');
const maps=['random','land','islands_l','islands_m','islands_s','atoll','world','europe','americas','africa','asia','mideast'];
const difficulties=['supereasy','easy','normal','hard','superhard','impossible'];
const modes={standard:{},quick:{quick:true},risky:{risky:true},endgame:{endgame:true},fog:{fog:true},garrisons:{garrison:true},fogGarrisons:{fog:true,garrison:true},instant:{instant:true},billionaire:{billionaire:true},equalBots:{bots:true},noCap:{noCap:true},pausedOrders:{pauseBuild:true},teams2:{teams:2},teams3:{teams:3},teams4:{teams:4},combined:{endgame:true,fog:true,garrison:true,instant:true,billionaire:true,bots:true,noCap:true,pauseBuild:true,teams:3}};
const cases=[];for(const map of maps)for(const diff of difficulties)for(const [mode,settings]of Object.entries(modes))cases.push({id:[map,diff,mode].join('-'),map,diff,mode,settings});
if(process.argv.includes('--worker')){
 const c=JSON.parse(fs.readFileSync(0,'utf8')),boot=require('../harness.js'),{recordScenario,replayScenario}=require('../parity-corpus-driver.js');
 const durations=[],observed={maxStructures:0,maxWarships:0,maxTransports:0,maxAircraft:0,maxAttacks:0},started=performance.now();
 const guarded=options=>{const game=boot(options),tick=game.tick;game.tick=(n=1)=>{for(let i=0;i<n;i++){const before=game.S.tickN,t0=performance.now();tick();durations.push(performance.now()-t0);assert.ok(game.S.tickN>before||game.S.draft||game.S.START.risky&&before===0,'simulation stopped advancing');if(game.S.tickN%100===0){assert.deepEqual(game.engine.checkInvariants(),[]);for(const [key,list]of Object.entries({maxStructures:game.S.structures,maxWarships:game.S.warships,maxTransports:game.S.transports,maxAircraft:game.S.aircraft,maxAttacks:game.S.attacks}))observed[key]=Math.max(observed[key],list.length);}}};return game;};
 const scenario={name:c.id,seed:'QA'+c.map.toUpperCase().replace(/_/g,'')+'01',grid:{width:720,height:414},settings:{map:c.map,diff:c.diff,country:0,troops:120,gold:100,teams:0,...c.settings},controls:{},coverage:['advanced'],ticks:c.ticks||300};
 let fixture;
 try{fixture=recordScenario(scenario,guarded);const replay=replayScenario(fixture,guarded);assert.deepEqual(replay.errors,[]);durations.sort((a,b)=>a-b);process.stdout.write(JSON.stringify({id:c.id,ok:true,ticks:scenario.ticks,commands:fixture.cmds.length,digest:replay.final.canonical.sha256,elapsedMs:performance.now()-started,p95TickMs:durations[Math.floor(durations.length*.95)],maxTickMs:durations.at(-1),observed}));}
 catch(e){if(fixture)fs.writeFileSync(path.join(out,c.id+'-failure-replay.json'),JSON.stringify(fixture));process.stdout.write(JSON.stringify({id:c.id,ok:false,error:e.stack,elapsedMs:performance.now()-started}));process.exitCode=1;}
}else{
 fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'catalog.json'),JSON.stringify({maps,difficulties,modes,cases:cases.length,grid:{width:720,height:414},scope:'Named modes Cartesian matrix; does not claim exhaustive binary option combinations'},null,2));
 const filter=process.argv.find(s=>s.startsWith('--filter='))?.slice(9),limit=Number(process.argv.find(s=>s.startsWith('--limit='))?.slice(8)||Infinity),ticks=Number(process.argv.find(s=>s.startsWith('--ticks='))?.slice(8)||300),jobs=Number(process.argv.find(s=>s.startsWith('--jobs='))?.slice(7)||2),resume=process.argv.includes('--resume'),report=path.join(out,'matrix-'+ticks+'.jsonl');
 const hash=require('node:crypto').createHash('sha256');function walk(dir){for(const name of fs.readdirSync(dir).sort()){const file=path.join(dir,name);if(fs.statSync(file).isDirectory())walk(file);else if(/\.(mjs|js)$/.test(file))hash.update(fs.readFileSync(file));}}walk(path.join(root,'game/src/sim'));const fingerprint=hash.digest('hex');
 const passed=new Set(resume&&fs.existsSync(report)?fs.readFileSync(report,'utf8').trim().split('\n').filter(Boolean).map(s=>JSON.parse(s)).filter(r=>r.ok&&r.fingerprint===fingerprint).map(r=>r.id):[]);
 if(!resume)fs.writeFileSync(report,'');const selected=cases.filter(c=>!filter||c.id.includes(filter)).filter(c=>!passed.has(c.id)).slice(0,limit);let cursor=0,total=0,failures=0;
 const run=c=>new Promise(resolve=>{const child=spawn(process.execPath,[__filename,'--worker'],{cwd:root,windowsHide:true}),stdout=[],stderr=[];let timedOut=false;const timeout=setTimeout(()=>{timedOut=true;child.kill();},180000);child.stdout.on('data',v=>stdout.push(v));child.stderr.on('data',v=>stderr.push(v));child.on('close',code=>{clearTimeout(timeout);let result;try{result=JSON.parse(Buffer.concat(stdout).toString());}catch{result={id:c.id,ok:false,error:timedOut?'watchdog timeout':Buffer.concat(stderr).toString(),exit:code};}resolve({...result,fingerprint});});child.stdin.end(JSON.stringify({...c,ticks}));});
 (async()=>{await Promise.all(Array.from({length:jobs},async()=>{while(cursor<selected.length){const c=selected[cursor++],result=await run(c);fs.appendFileSync(report,JSON.stringify(result)+'\n');total++;if(!result.ok)failures++;const summary={planned:selected.length,completed:total,failures,fingerprint,report,updated:new Date().toISOString()};fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify({case:result.id,ok:result.ok,completed:total,failures,ms:Math.round(result.elapsedMs||0),error:result.ok?undefined:result.error?.slice(0,220)}));}}));console.log(JSON.stringify({total,failures,report}));process.exitCode=failures?1:0;})().catch(e=>{console.error(e);process.exitCode=1;});

}
