<?php
if (!defined('ABSPATH')) exit;

/** Admin → Players: find a player and edit anything about them — nation, win credits, bot record, scores, quotes, saves, ban. */
function statefall_admin_players() {
    global $wpdb; $t = statefall_table();
    $uid = isset($_GET['uid']) ? (int) $_GET['uid'] : 0; $q = isset($_GET['q']) ? sanitize_text_field(wp_unslash($_GET['q'])) : '';
    // ---- actions
    if (!empty($_POST['sf_pl']) && check_admin_referer('statefall_players')) {
        $uid = (int) $_POST['uid']; $act = sanitize_key($_POST['sf_pl']); $msg = '';
        switch ($act) {
            case 'nation': { $nm = mb_substr(sanitize_text_field(wp_unslash($_POST['nation'])), 0, 20); if ($nm === '') delete_user_meta($uid, 'statefall_nation'); else update_user_meta($uid, 'statefall_nation', $nm);
                $fj = trim(wp_unslash($_POST['flag'] ?? '')); if ($fj === '') delete_user_meta($uid, 'statefall_flag'); else { $f = json_decode($fj, true); $v = is_array($f) ? statefall_validate_flag($f) : false; if ($v) update_user_meta($uid, 'statefall_flag', $v); else $msg = 'Flag JSON was not valid; flag unchanged. '; }
                update_user_meta($uid, 'statefall_win_credit', (int) $_POST['wincredit']); statefall_pool_refresh($uid); $msg .= 'Nation saved.'; break; }
            case 'botrec': { $r = ['matches' => (int) $_POST['b_matches'], 'wins' => (int) $_POST['b_wins'], 'survived' => (int) $_POST['b_survived'], 'kills' => (int) $_POST['b_kills'], 'killedPlayers' => (int) $_POST['b_killedPlayers'], 'landSum' => (float) $_POST['b_landSum'], 'killers' => []]; $old = get_user_meta($uid, 'statefall_botrec', true); if (is_array($old) && isset($old['killers'])) $r['killers'] = $old['killers']; update_user_meta($uid, 'statefall_botrec', $r); $msg = 'Bot record saved.'; break; }
            case 'ban': update_user_meta($uid, 'statefall_banned', 1); $msg = 'Banned from posting scores.'; break;
            case 'unban': delete_user_meta($uid, 'statefall_banned'); $msg = 'Unbanned.'; break;
            case 'note': update_user_meta($uid, 'statefall_admin_note', sanitize_textarea_field(wp_unslash($_POST['note']))); $msg = 'Note saved.'; break;
            case 'score': { $id = (int) $_POST['id']; $row = $wpdb->get_row($wpdb->prepare("SELECT * FROM $t WHERE id=%d AND user_id=%d", $id, $uid), ARRAY_A); if ($row) { $f = ['result' => mb_substr(sanitize_text_field(wp_unslash($_POST['result'])), 0, 30), 'country' => mb_substr(sanitize_text_field(wp_unslash($_POST['country'])), 0, 40), 'diff' => sanitize_key($_POST['diff']), 'cls' => mb_substr(sanitize_text_field(wp_unslash($_POST['cls'])), 0, 80), 'land' => max(0, min(100, (float) $_POST['land'])), 'minutes' => max(0, (float) $_POST['minutes']), 'kills' => max(0, (int) $_POST['kills'])]; $merged = array_merge($row, $f); $f['score'] = !empty($_POST['recompute']) ? statefall_score($merged) : (int) $_POST['score']; $wpdb->update($t, $f, ['id' => $id]); $msg = 'Score #' . $id . ' saved' . (!empty($_POST['recompute']) ? ' (score recomputed: ' . $f['score'] . ')' : '') . '.'; } break; }
            case 'delscore': $wpdb->delete($t, ['id' => (int) $_POST['id'], 'user_id' => $uid]); $msg = 'Score deleted.'; break;
            case 'delquote': $wpdb->update($t, ['custom' => null], ['id' => (int) $_POST['id']]); $msg = 'Quote removed.'; break;
            case 'delsave': if (function_exists('statefall_saves_table')) $wpdb->delete(statefall_saves_table(), ['id' => (int) $_POST['id'], 'user_id' => $uid]); $msg = 'Save deleted.'; break;
        }
        statefall_log_action('Player edit (' . $act . ') on user #' . $uid); echo '<div class="updated"><p>' . esc_html($msg) . '</p></div>';
    }
    echo '<div class="wrap"><h1>Statefall — players</h1>';
    echo '<form method="get" style="margin:10px 0 18px"><input type="hidden" name="page" value="statefall-players"><input type="search" name="q" value="' . esc_attr($q) . '" placeholder="name, login or email" class="regular-text"> <button class="button">Find</button></form>';
    if ($q && !$uid) { $users = get_users(['search' => '*' . $q . '*', 'search_columns' => ['user_login', 'user_email', 'display_name', 'user_nicename'], 'number' => 30]); if (!$users) echo '<p>No players match.</p>'; else { echo '<table class="widefat striped" style="max-width:700px"><tbody>'; foreach ($users as $u) { $s = statefall_user_summary($u->ID); echo '<tr><td><a href="' . esc_url(admin_url('admin.php?page=statefall-players&uid=' . $u->ID)) . '">' . esc_html($u->display_name) . '</a> <span style="color:#888">#' . (int) $u->ID . '</span></td><td>' . (int) $s['matches'] . ' matches · ' . (int) $s['wins'] . ' wins</td></tr>'; } echo '</tbody></table>'; } }
    if (!$uid) { echo '</div>'; return; }
    $u = get_userdata($uid); if (!$u) { echo '<p>No such user.</p></div>'; return; }
    $n = statefall_nation_of($uid); $b = statefall_bot_record($uid); $s = statefall_user_summary($uid); $banned = get_user_meta($uid, 'statefall_banned', true); $credit = (int) get_user_meta($uid, 'statefall_win_credit', true); $note = get_user_meta($uid, 'statefall_admin_note', true);
    $nonce = wp_nonce_field('statefall_players', '_wpnonce', true, false); $hid = '<input type="hidden" name="uid" value="' . $uid . '">';
    echo '<h2>' . esc_html($u->display_name) . ' <span style="color:#888;font-weight:400">#' . $uid . ' · ' . esc_html($u->user_email) . ' · <a href="' . esc_url(statefall_player_url($uid)) . '" target="_blank">public page</a></span></h2>';
    echo '<p>' . (int) $s['matches'] . ' matches · ' . (int) $s['wins'] . ' wins · ' . (int) $n['wins'] . ' qualifying wins (incl. ' . $credit . ' credit) · tier ' . (int) $n['tier'] . ($banned ? ' · <b style="color:#b00">BANNED</b>' : '') . '</p>';
    echo '<form method="post" style="display:inline">' . $nonce . $hid . '<button class="button" name="sf_pl" value="' . ($banned ? 'unban' : 'ban') . '">' . ($banned ? 'Unban' : 'Ban from posting scores') . '</button></form>';
    // ---- nation
    echo '<h2>Nation</h2><script src="' . esc_url(statefall_flags_url()) . '"></script>' . ($n['flag'] ? '<p><span data-sf-flag="' . esc_attr(wp_json_encode($n['flag'])) . '" data-w="90" data-h="60"></span></p>' : '<p style="color:#888">No flag.</p>');
    echo '<form method="post">' . $nonce . $hid . '<table class="form-table"><tr><th>Nation name</th><td><input name="nation" value="' . esc_attr($n['name']) . '" maxlength="20" class="regular-text"></td></tr><tr><th>Win credit</th><td><input name="wincredit" type="number" value="' . $credit . '" style="width:90px"> <span class="description">added to (or subtracted from) qualifying wins — use to settle disputes or grant a tier</span></td></tr><tr><th>Flag JSON</th><td><textarea name="flag" rows="4" class="large-text" style="font-family:monospace">' . esc_textarea($n['flag'] ? wp_json_encode($n['flag']) : '') . '</textarea><p class="description">Blank to remove the flag. Validated on save (palette colours and known layer types only).</p></td></tr></table><button class="button button-primary" name="sf_pl" value="nation">Save nation</button></form>';
    // ---- bot record
    echo '<h2>Bot record</h2><form method="post">' . $nonce . $hid . '<table class="form-table"><tr><th>Matches</th><td><input name="b_matches" type="number" value="' . (int) $b['matches'] . '" style="width:90px"> Wins <input name="b_wins" type="number" value="' . (int) $b['wins'] . '" style="width:90px"> Survived <input name="b_survived" type="number" value="' . (int) $b['survived'] . '" style="width:90px"></td></tr><tr><th>Eliminations</th><td>Nations <input name="b_kills" type="number" value="' . (int) $b['kills'] . '" style="width:90px"> Players <input name="b_killedPlayers" type="number" value="' . (int) $b['killedPlayers'] . '" style="width:90px"> Land sum <input name="b_landSum" type="number" step="0.1" value="' . (float) $b['landSum'] . '" style="width:110px"></td></tr></table><button class="button" name="sf_pl" value="botrec">Save bot record</button></form>';
    // ---- note
    echo '<h2>Admin note</h2><form method="post">' . $nonce . $hid . '<textarea name="note" rows="3" class="large-text">' . esc_textarea($note) . '</textarea><p><button class="button" name="sf_pl" value="note">Save note</button></p></form>';
    // ---- scores
    $rows = $wpdb->get_results($wpdb->prepare("SELECT * FROM $t WHERE user_id=%d ORDER BY id DESC LIMIT 200", $uid), ARRAY_A);
    echo '<h2>Scores (' . count($rows) . ')</h2><p class="description">Edit any field and Save; tick Recompute to derive the score from the fields. Deleting removes the match from every board.</p>';
    $diffs = array_keys(statefall_enums()['diff']);
    foreach ($rows as $r) { $c = $r['custom'] ? json_decode($r['custom'], true) : null;
        echo '<form method="post" style="background:#fff;border:1px solid #ccd;padding:8px 12px;margin:0 0 8px;display:flex;flex-wrap:wrap;gap:8px;align-items:center">' . $nonce . $hid . '<input type="hidden" name="id" value="' . (int) $r['id'] . '"><b style="width:60px">#' . (int) $r['id'] . '</b><span style="color:#888;width:130px">' . esc_html($r['created_at']) . '</span>'
            . '<label>Result <input name="result" value="' . esc_attr($r['result']) . '" style="width:110px"></label><label>Country <input name="country" value="' . esc_attr($r['country']) . '" style="width:130px"></label><label>Diff <select name="diff">' . implode('', array_map(function ($d) use ($r) { return '<option value="' . esc_attr($d) . '"' . ($d === $r['diff'] ? ' selected' : '') . '>' . esc_html(statefall_diff_name($d)) . '</option>'; }, $diffs)) . '</select></label><label>Class <input name="cls" value="' . esc_attr($r['cls']) . '" style="width:170px"></label><label>Land <input name="land" type="number" step="0.1" value="' . (float) $r['land'] . '" style="width:70px"></label><label>Min <input name="minutes" type="number" step="0.1" value="' . (float) $r['minutes'] . '" style="width:70px"></label><label>Kills <input name="kills" type="number" value="' . (int) $r['kills'] . '" style="width:60px"></label><label>Score <input name="score" type="number" value="' . (int) $r['score'] . '" style="width:80px"></label><label><input type="checkbox" name="recompute" value="1"> Recompute</label>'
            . '<button class="button button-small" name="sf_pl" value="score">Save</button><button class="button button-small" name="sf_pl" value="delscore" onclick="return confirm(\'Delete score #' . (int) $r['id'] . '?\')">Delete</button>' . ($c && (!empty($c['quote']) || !empty($c['dedication'])) ? '<span style="flex-basis:100%;color:#555">Quote: “' . esc_html($c['quote'] ?? '') . '” ' . esc_html($c['dedication'] ?? '') . ' <button class="button button-small" name="sf_pl" value="delquote">Delete quote</button></span>' : '') . '</form>'; }
    // ---- saves
    if (function_exists('statefall_saves_table')) { $st = statefall_saves_table(); $saves = $wpdb->get_results($wpdb->prepare("SELECT id,kind,slot,seed,tick,updated_at FROM $st WHERE user_id=%d ORDER BY updated_at DESC", $uid), ARRAY_A);
        echo '<h2>Saves and replays (' . count($saves) . ')</h2><table class="widefat striped" style="max-width:900px"><tbody>'; foreach ($saves as $sv) echo '<tr><td>#' . (int) $sv['id'] . '</td><td>' . esc_html($sv['kind']) . '</td><td>' . esc_html($sv['slot']) . '</td><td>' . esc_html($sv['seed']) . '</td><td>' . esc_html(round($sv['tick'] / 600, 1)) . ' min</td><td>' . esc_html($sv['updated_at']) . '</td><td><a class="button button-small" href="' . esc_url(wp_nonce_url(admin_url('admin.php?page=statefall-saves&sf_save_dl=' . (int) $sv['id']), 'statefall_save_dl')) . '">Download</a> <form method="post" style="display:inline">' . $nonce . $hid . '<input type="hidden" name="id" value="' . (int) $sv['id'] . '"><button class="button button-small" name="sf_pl" value="delsave" onclick="return confirm(\'Delete this save?\')">Delete</button></form></td></tr>'; if (!$saves) echo '<tr><td>None.</td></tr>'; echo '</tbody></table>'; }
    echo '</div>';
}
