import {helpRoster} from '../../game/src/help-roster.mjs';
import {HELP_ART} from '../../game/src/help-art.mjs';
const $=id=>document.getElementById(id);
const chapters=[['The command table','Learn to read the interface, stop time and move around the map.',[]],['A foothold','Build a linked economy, keep a reserve and defend a choke.',['city','factory','fort']],['Across the water','Build trade, scout a coast and escort a landing.',['port','merchant','scout','warship','transport','shore','battery','port-level2','heavytransport']],['A fleet with a purpose','Combine bombardment, escorts, submarine detection and trade raiding.',['cruiser','battleship','subbase','sub','hunter','privateer']],['Own the sky','Patrol, intercept, bomb, recall, paradrop and try automation.',['airfield','fighter','bomber','airfield-level2','carrier','flightops']],['Seeing through the fog','Compare radar, direct sight, jamming and temporary reconnaissance.',['radar','lradar','rship','jammer','spy','satellite']],['Break the strongpoint','Read missile defenses, suppress positions, repair damage and extend coverage.',['sam','shield','silo','command','bertha','engcmd','truck','fort-level2','fort-level3']],['Keep the front supplied','Learn local troop pools, escorted reinforcement, logistics and aid.',['troopcmd']],['First command','Win a compact campaign. No new units; guidance fades as you take command.',[]]];
const roster=['build','ships','air'].flatMap(helpRoster),assigned=new Map(chapters.flatMap((c,i)=>c[2].map(k=>[k,i+1])));
if(roster.length!==40||assigned.size!==40||roster.some(r=>!assigned.has(r.key)))throw Error('Campaign must cover all forty roster entries.');
const steps=[
 ['homeland','This is your homeland.','The blue country is yours. The clock is stopped. Nothing can attack while you read. First, learn to see the battlefield.'],
 ['pause','Time is in your hands.','Resume this safe preview once, then pause again. Space also works. In the game, pausing freezes troops, income and weapons.','pause'],
 ['map','First, zoom out.','Scroll down over the map to see more of the island. You can also use the minus button. The battle stays paused.','out'],
 ['map','Now pan the map.','Drag the island sideways to change your view. Arrow keys also work when the map has focus.','pan'],
 ['map','Move closer again.','Zoom in to read a border before committing troops. Scroll up or use the plus button.','in'],
 ['troops','Your army, and its limit.','You have 600 troops and capacity for 900. Troops attack and defend. Growth slows as the army fills its capacity.'],
 ['gold','Gold is your building budget.','You have 700 gold to spend. Buildings and units cost gold; income tells you how quickly more arrives.'],
 ['income','Read the rate, not just the total.','Income is what you gain each second while time runs. A working factory increases gold income.'],
 ['economy','Fund your next move.','Move toward gold until its share reaches at least 65%. In a real match, balance construction against troop growth.','economy'],
 ['attack','Keep troops in reserve.','This controls the share committed by your next order. Set it between 30% and 40%; the rest stay behind.','attack'],
 ['land','Keep the larger goal in view.','A normal match is won at 72% of the land. Training starts with smaller tasks so you can learn one decision at a time.'],
 ['diplomacy','Know who is on your side.','Agreements appear here; field reports record events. Later lessons teach pacts, alliances and aid.'],
 ['map','Open construction.','Right-click your homeland. Keyboard: focus the map and press Shift+F10. This schematic accepts the whole map as a practice target.','menu'],
 ['build','Choose a factory.','A factory turns gold into ongoing income. It costs 110 gold and normally takes 15 seconds. Choose Factory to prepare placement.','choose'],
 ['buildSite','Place it on your land.','Click the marked site, or press Enter on the map. The real campaign will check ownership, spacing and links; this preview accepts a map click.','place'],
 ['map','Purchased is not yet working.','Time must run for construction. Press Run preview. This illustration compresses the normal 15-second build into two seconds.','build'],
 ['income','See what changed.','The factory is working. Base gold income rose by 2.2 per second. Next come supply links, careful attacks and a defended border.'],
 ['map','Your first command is the beginning.','Explore the nine chapters and forty-unit guide. Each unit gets a role, a practical drill and a visible outcome. Campaign integration is the next stage.']
];
let step=0,done=false,scale=1.2,x=0,y=0,baseScale=scale,base=[0,0],running=false,wasRunning=false,placing=false,timer,active=true;
function complete(text){if(done)return;done=true;$('feedback').textContent=text;$('next').disabled=false;$('next').textContent='Continue →';}
function camera(){ $('world').style.transform=`translate(${x}px,${y}px) scale(${scale})`;$('scale').textContent=Math.round(scale*100)+'%';const task=steps[step][3];if(task==='out'&&scale<=baseScale*.75)complete('You can see more of the island.');if(task==='in'&&scale>=baseScale*1.2)complete('Close enough to inspect details.');if(task==='pan'&&Math.hypot(x-base[0],y-base[1])>=45)complete('The view moved while time stayed stopped.');}
function zoom(d){scale=Math.min(2,Math.max(.4,scale+d));camera();}
function arrow(){if(!active)return;const r=$(steps[step][0]).getBoundingClientRect(),c=$('coach').getBoundingClientRect();let tx=r.left-8,ty=r.top+r.height/2;if(steps[step][0]==='map'){tx=r.left+r.width*.64;ty=r.top+r.height*.28;}$('line').setAttribute('d',tx>0&&ty>0&&ty<innerHeight?`M${c.right-10} ${c.top+24} Q${c.right+40} ${ty} ${tx} ${ty}`:'');}
function show(){document.querySelectorAll('.spotlight').forEach(e=>e.classList.remove('spotlight'));const s=steps[step];done=!s[3];baseScale=scale;base=[x,y];wasRunning=running=false;$('pause').textContent='▶ Resume';$('phase').textContent=$('status').textContent='PAUSED · '+(s[3]?'TRY':'LOOK');$('heading').textContent=s[1];$('copy').textContent=s[2];$('count').textContent=`${step+1} / ${steps.length}`;$('feedback').textContent=s[3]?'Try the highlighted action.':'The battlefield waits while you read.';$('next').disabled=!!s[3]&&s[3]!=='build';$('next').textContent=s[3]==='build'?'Run preview':s[3]?'Complete the action':'Continue →';$('back').disabled=step===0;$('skip').hidden=!s[3];$('build').hidden=s[0]!=='build';$(s[0]).classList.add('spotlight');const targetRect=$(s[0]).getBoundingClientRect();if(targetRect.top<0||targetRect.top>innerHeight-200)$(s[0]).scrollIntoView({block:'center',behavior:'instant'});arrow();$('heading').focus({preventScroll:true});}
function exit(){active=false;clearTimeout(timer);$('coach').hidden=$('arrow').hidden=true;$('build').hidden=true;document.querySelectorAll('.spotlight').forEach(e=>e.classList.remove('spotlight'));}
function reset(){clearTimeout(timer);active=true;step=0;scale=1.2;x=y=0;placing=false;$('factory').setAttribute('visibility','hidden');$('goldValue').textContent='700';$('incomeValue').textContent='+5 troops/s · +1.4 gold/s';$('econ').value=$('ratio').value='50';$('econText').textContent='50% troops · 50% gold';$('attackText').textContent='50%';$('coach').hidden=$('arrow').hidden=false;camera();show();}
$('next').onclick=()=>{if(steps[step][3]==='build'&&!done){$('status').textContent=$('phase').textContent='RUNNING · OBSERVE';$('next').disabled=true;timer=setTimeout(()=>{$('factory').style.opacity='1';$('incomeValue').textContent='+5 troops/s · +3.6 gold/s';$('status').textContent=$('phase').textContent='PAUSED · RESULT';complete('Construction complete. Income increased.');},2000);return;}if(step<steps.length-1){step++;show();}else exit();};$('back').onclick=()=>{clearTimeout(timer);if(step){step--;show();}};$('exit').onclick=exit;$('skip').onclick=()=>complete('Skipped in this design preview.');$('hint').onclick=()=>{$('feedback').textContent=({out:'Use the − button twice.',in:'Use the + button twice.',pan:'Drag the map about 50 pixels.',pause:'Press Resume, then Pause.',economy:'Move Economy to the right.',attack:'Move Send into attack to 35%.',menu:'Right-click the map or press Shift+F10.',choose:'Choose Factory in the menu.',place:'Click the map or press Enter while it is focused.',build:'Press Run preview.'})[steps[step][3]]||'Continue when you are ready.';};
$('pause').onclick=()=>{if(steps[step][3]!=='pause'){if(active)$('feedback').textContent='The coach holds the pause during this explanation.';return;}running=!running;$('pause').textContent=running?'Ⅱ Pause':'▶ Resume';$('status').textContent=running?'RUNNING · SAFE PREVIEW':'PAUSED · TRY';if(running)wasRunning=true;else if(wasRunning)complete('Paused again. Camera controls remain available.');};
$('minus').onclick=()=>zoom(-.2);$('plus').onclick=()=>zoom(.2);$('center').onclick=()=>{x=y=0;camera();};$('map').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?-.12:.12);},{passive:false});let drag,moved=false;$('map').onpointerdown=e=>{if(e.button!==0||e.target.closest('button'))return;drag=[e.clientX,e.clientY,x,y];moved=false;$('map').setPointerCapture(e.pointerId);};$('map').onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag[0],dy=e.clientY-drag[1];if(Math.hypot(dx,dy)>5)moved=true;x=drag[2]+dx;y=drag[3]+dy;camera();};$('map').onpointerup=()=>{drag=null;};
function menu(){if(steps[step][3]==='menu'){$('build').hidden=false;complete('Construction menu opened.');}}function place(){if(steps[step][3]!=='place'||!placing)return;placing=false;$('factory').setAttribute('visibility','visible');$('factory').style.opacity='.4';$('goldValue').textContent='590';complete('110 gold spent. Construction waits for time to run.');}
$('map').oncontextmenu=e=>{e.preventDefault();menu();};$('buy').onclick=()=>{placing=true;complete('Selected. Gold is spent when you place it.');};$('map').onclick=e=>{if(!moved&&!e.target.closest('button'))place();};$('map').onkeydown=e=>{if(e.key==='+'||e.key==='='){e.preventDefault();zoom(.2);}else if(e.key==='-'){e.preventDefault();zoom(-.2);}else if(e.shiftKey&&e.key==='F10'){e.preventDefault();menu();}else if(e.key==='Enter')place();else if(e.key.startsWith('Arrow')){e.preventDefault();if(e.key==='ArrowLeft')x-=30;if(e.key==='ArrowRight')x+=30;if(e.key==='ArrowUp')y-=30;if(e.key==='ArrowDown')y+=30;camera();}};document.onkeydown=e=>{if(e.code==='Space'&&!e.target.matches('input,button')&&!$('roster').open){e.preventDefault();$('pause').click();}};
$('econ').oninput=e=>{let n=+e.target.value;$('econText').textContent=`${100-n}% troops · ${n}% gold`;if(steps[step][3]==='economy'&&n>=65)complete('More growth goes toward gold.');};$('ratio').oninput=e=>{let n=+e.target.value;$('attackText').textContent=n+'%';if(steps[step][3]==='attack'&&n>=30&&n<=40)complete(`${100-n}% stays in reserve.`);};
function select(i){[...$('chapters').children].forEach((b,n)=>b.classList.toggle('active',i===n));$('chapter').textContent=`${String(i+1).padStart(2,'0')} / ${chapters[i][0].toUpperCase()}`;$('title').textContent=i?chapters[i][0]:'The battlefield can wait.';$('description').textContent=chapters[i][1];$('details').hidden=!i;$('units').replaceChildren();for(const key of chapters[i][2]){const u=roster.find(r=>r.key===key),b=document.createElement('button');b.textContent=u.name;b.onclick=()=>guide(u.name);$('units').append(b);}if(i)exit();}
chapters.forEach((c,i)=>{const b=document.createElement('button');b.textContent=`${i+1}. ${c[0]}`;b.onclick=()=>{select(i);if(!i)reset();};$('chapters').append(b);});$('restart').onclick=()=>{select(0);reset();};
function render(){const q=$('search').value.toLowerCase();$('cards').replaceChildren();for(const u of roster.filter(r=>(r.name+' '+r.description+' '+r.use).toLowerCase().includes(q))){const a=document.createElement('article');a.className='unit';const img=document.createElement('img');img.src=HELP_ART[u.key];img.alt=u.name;img.loading='lazy';a.append(img);for(const [tag,cls,text] of [['h3','',u.name],['div','stats',u.stats],['p','',u.description],['p','',u.use],['div','lesson',`CHAPTER ${assigned.get(u.key)} · PRACTICAL DRILL`]]){const e=document.createElement(tag);e.className=cls;e.textContent=text;a.append(e);}$('cards').append(a);}}
function guide(q=''){$('search').value=q;render();$('roster').showModal();$('search').focus();}$('guide').onclick=()=>guide();$('close').onclick=()=>$('roster').close();$('search').oninput=render;addEventListener('resize',arrow);addEventListener('scroll',arrow,{passive:true});select(0);camera();show();
