const {test,expect}=require('@playwright/test');
for(const closeControl of ['#helpClose','#trainingHelpReturn']) test('real lesson and guide return via '+closeControl,async({page})=>{
 const artResponses=[];page.on('response',r=>{if(r.url().includes('/classic-assets/')&&r.url().endsWith('.png'))artResponses.push({url:r.url(),ok:r.ok()});});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/?browserTest=1');await expect(page.locator('#trainingTitle')).toHaveText('Your actual starting country',{timeout:30000});
 await expect(page).toHaveURL(/art=classic/);expect(artResponses.some(r=>r.url.includes('structures-complete.png')&&r.ok)).toBe(true);expect(artResponses.every(r=>r.ok)).toBe(true);
 const status=()=>page.evaluate(()=>window.__STATEFALL_TEST__.status());const next=async()=>{await expect(page.locator('#trainingNext'),await page.locator('#trainingTitle').innerText()).toBeEnabled();await page.locator('#trainingNext').click();};
 await page.locator('#trainingGuide').click();await expect(page.locator('#help')).toBeVisible();await page.locator(closeControl).click();await expect(page.locator('#trainingTitle')).toHaveText('Your actual starting country');
 const before=await status();await page.waitForTimeout(300);expect((await status()).tick).toBe(before.tick);await next();
 const box=await page.locator('#map').boundingBox();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.35);await page.mouse.wheel(0,500);await page.mouse.wheel(0,500);await page.mouse.wheel(0,500);await next();
 await page.mouse.move(box.x+box.width*.6,box.y+box.height*.35);await page.mouse.down();await page.mouse.move(box.x+box.width*.6+100,box.y+box.height*.35+50,{steps:8});await page.mouse.up();await next();
 await page.mouse.move(box.x+box.width*.6,box.y+box.height*.35);await page.mouse.wheel(0,-500);await page.mouse.wheel(0,-500);await page.mouse.wheel(0,-500);await next();await next();await next();await next();await page.locator('#focus').press('Home');await next();await page.locator('#ratio').press('Home');for(let n=0;n<30;n++)await page.locator('#ratio').press('ArrowRight');await next();
 await page.locator('#pauseBtn').click();await expect.poll(async()=>(await status()).paused).toBe(false);await page.waitForTimeout(300);await page.locator('#pauseBtn').click();await next();
 const target=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('buildable',6));await page.locator('#map').click({position:{x:target.x,y:target.y},button:'right'});await next();
 const gold=await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().player.gold);await page.locator('#ctx [data-type="city"]').click();await next();expect(await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().player.gold)).toBeCloseTo(gold-120,4);
 await page.keyboard.press('f');await next();const site=await page.evaluate(()=>window.__STATEFALL_TEST__.focusTarget('buildable',6));await page.locator('#map').click({position:{x:site.x,y:site.y}});await next();
 expect(await page.evaluate(()=>window.__STATEFALL_TEST__.snapshot().player.gold)).toBeCloseTo(gold-230,4);const startTick=(await status()).tick;await page.locator('#trainingNext').click();await expect(page.locator('#trainingFeedback')).toContainText('real simulation ticks',{timeout:25000});expect((await status()).tick-startTick).toBeGreaterThanOrEqual(150);expect((await status()).paused).toBe(true);expect(await page.evaluate(()=>window.__STATEFALL_TEST__.structurePresentation().some(s=>s.type==='factory'&&!s.building))).toBe(true);
 await page.locator('#trainingGuide').click();await expect(page.locator('#help')).toBeVisible();expect((await status()).paused).toBe(true);await page.locator('#trainingHelpReturn').click();await expect(page.locator('#training')).toBeVisible();await next();await next();await expect(page.locator('#trainingTitle')).toHaveText('Explore every unit');await expect(page.locator('#trainingNext')).toBeDisabled();await page.locator('#helpBtn2').click();await expect(page.locator('#help')).toBeVisible();await page.locator(closeControl).click();await expect(page.locator('#trainingTitle')).toHaveText('Opening lesson complete');expect((await status()).paused).toBe(true);await expect(page.locator('#trainingNext')).toBeHidden();await page.locator('#trainingGuide').click();await page.locator(closeControl).click();await expect(page.locator('#trainingTitle')).toHaveText('Opening lesson complete');expect(errors).toEqual([]);
});
