import {STRUCT,BUILD_TICKS} from '/src/sim/rules.mjs';
// Local prototype only: the server injects this module; production never imports it.
const $=id=>document.getElementById(id);
while(!window.__STATEFALL_TEST__||$('bootStatus'))await new Promise(r=>setTimeout(r,80));
const game=window.__STATEFALL_TEST__;
game.prepareControlledStart();
for(const [id,value] of Object.entries({seedIn:'FIRSTCOMMAND',diffSel:'supereasy',stTroops:'1200',stGold:'3000'})){ $(id).value=value;$(id).dispatchEvent(new Event('change',{bubbles:true})); }
$('stPauseBuild').checked=true;
$('countrySel').value=[...$('countrySel').options].find(o=>o.text==='Hungary').value;
$('countrySel').dispatchEvent(new Event('change',{bubbles:true}));
$('startBtn').click();
while(!game.status().ready)await new Promise(r=>setTimeout(r,80));
$('pauseBtn').click(); // Establish the native user-pause state after controlled startup.
let target=game.focusTarget('buildable',6),step=0,completed=false,baseCamera,seenRunning=false,baseStructures=0,factoryTile=null,active=true,observing=false,lastSnapshot=null,guideOpened=false;
document.body.insertAdjacentHTML('beforeend',`<div id="trainingBadge">LOCAL TUTORIAL PREVIEW · REAL STATEFALL ENGINE</div><div id="trainingRing"></div><svg id="trainingArrow" aria-hidden="true"><defs><marker id="trainingHead" markerWidth="9" markerHeight="9" refX="7" refY="3" orient="auto"><polygon points="0,0 0,6 8,3" fill="#f2c778"/></marker></defs><path marker-end="url(#trainingHead)"/></svg><section id="training" aria-labelledby="trainingTitle"><small id="trainingPhase"></small><h2 id="trainingTitle"></h2><p id="trainingCopy"></p><p id="trainingFeedback" role="status"></p><div class="actions"><button id="trainingNext">Continue</button><button id="trainingLocate">Show target</button><button id="trainingGuide">Unit guide</button><button id="trainingReset">Restart lesson</button><button id="trainingExit">Free practice</button></div></section><button id="trainingHelpReturn" hidden>Return to lesson</button>`);
const steps=[
 ['world','Your actual starting country','This is the real game: its terrain, flags, troops and camera. Time is stopped. The marker identifies a valid owned tile, not a substitute map.'],
 ['map','Zoom out','Scroll down over the battlefield until you can see more of the surrounding countries. The clock stays paused.','out'],
 ['map','Pan the battlefield','Drag the real map to look around. Move it about 60 pixels. This changes your view without changing the world.','pan'],
 ['world','Zoom back in','Scroll up to inspect terrain and borders. Use Show target if your homeland is offscreen.','in'],
 ['troops','Read your available troops','The current army and its capacity are shown here. These are live engine values, not sample numbers.'],
 ['gold','Read your construction budget','Gold pays for buildings and units. Watch this number change when you place a city and factory.'],
 ['income','Read your income','These rates come from the engine. Construction, supply links and your economy setting affect them.'],
 ['focus','Balance the economy','Move the Economy slider until at least 65% goes to gold. Read the actual label above it.','economy'],
 ['ratio','Keep a reserve','Set Send into attack between 30% and 40%. The remaining troops stay behind.','ratio'],
 ['pauseBtn','Practice pausing','Use the actual Pause button or Space to resume, then pause again. Only this exercise and construction observation allow time to run.','pause'],
 ['world','Open the real build menu','Right-click the marked owned tile. The native menu will show the buildings, prices and any placement restrictions.','menu'],
 ['cityButton','Build a city',`Choose City in the native menu. It costs ${STRUCT.city.cost} gold and adds troops immediately. The game validates the location and charges the actual price.`,'city'],
 ['world','Prepare a factory',`Press F to enter the game’s factory placement mode. A factory costs ${STRUCT.factory.cost} gold and takes ${BUILD_TICKS.factory/10} simulation seconds. Move the preview over your land.`,'prepare'],
 ['world','Place the factory','Left-click the marked valid area. The actual game checks ownership and spacing. A successful order creates a real construction site and deducts gold.','factory'],
 ['factory','Let construction finish','Press Run construction. The real world runs at normal speed; the lesson pauses as soon as your factory is operational. No shortened timer or fabricated income.','observe'],
 ['factory','Inspect your finished factory','This is the game’s actual factory artwork at its actual map location. Pan and zoom to inspect it. Compare the Income readout and any supply connection.'],
 ['helpBtn2','Explore every unit','Open Unit guide to explore the illustrated Buildings, Ships and Air tabs. Close Help or choose Return to lesson when you are ready.','guide'],
 ['helpBtn2','Opening lesson complete','You have practiced the camera, interface, pause controls and real construction. This is the end of the current demo. The remaining campaign chapters are still in development. Choose Free practice to keep playing, or Restart lesson to try again.']
];
function ownStructures(){return game.structurePresentation().filter(s=>s.color===game.me.color);}
function finish(text){if(completed)return;completed=true;$('trainingFeedback').textContent=text;$('trainingNext').disabled=false;$('trainingNext').textContent='Continue';}
function show(){observing=false;game.pause();completed=!steps[step][3];seenRunning=false;baseCamera=game.snapshot().camera;baseStructures=ownStructures().length;if(['menu','prepare'].includes(steps[step][3]))target=game.focusTarget('buildable',6);$('trainingTitle').textContent=steps[step][1];$('trainingCopy').textContent=steps[step][2];$('trainingPhase').textContent=`${step+1} / ${steps.length} · PAUSED · ${completed?'LOOK':'TRY'}`;$('trainingFeedback').textContent=completed?'Take your time. The simulation is paused.':'Complete the action in the game.';$('trainingNext').textContent=steps[step][3]==='observe'?'Run construction':'Continue';$('trainingNext').disabled=!completed&&steps[step][3]!=='observe';draw();}
function worldRect(tile){const s=lastSnapshot||game.snapshot(),r=$('map').getBoundingClientRect(),c=s.camera,w=720;return {left:r.left+c.x+(tile%w+.5)*c.scale-12,top:r.top+c.y+(Math.floor(tile/w)+.5)*c.scale-12,width:24,height:24};}
function anchor(){const kind=steps[step][0];if(kind==='world')return worldRect(target.tile);if(kind==='factory'){const st=game.structurePresentation().find(s=>s.tile===factoryTile);const r=$('map').getBoundingClientRect();return st?{left:r.left+st.x-18,top:r.top+st.y-22,width:36,height:40}:null;}if(kind==='cityButton')return document.querySelector('#ctx [data-type="city"]')?.getBoundingClientRect();if(kind==='map'){const r=$('map').getBoundingClientRect();return {left:r.left+r.width*.6,top:r.top+r.height*.35,width:40,height:40};}return $(kind)?.getBoundingClientRect();}
function setCueHidden(hidden){for(const id of ['trainingRing','trainingArrow'])$(id).toggleAttribute('hidden',hidden);}
function draw(){if(!active)return;const help=getComputedStyle($('help')).display!=='none';$('training').hidden=help;setCueHidden(help);$('trainingHelpReturn').hidden=!help;if(help)return;if(['out','pan'].includes(steps[step][3])){setCueHidden(true);return;}const r=anchor(),card=$('training'),c=card.getBoundingClientRect(),ring=$('trainingRing');if(!r||r.left<0||r.top<0||r.left+r.width>innerWidth||r.top+r.height>innerHeight){setCueHidden(true);return;}setCueHidden(false);Object.assign(ring.style,{left:(r.left-4)+'px',top:(r.top-4)+'px',width:(r.width+8)+'px',height:(r.height+8)+'px'});if(r.left<c.right&&r.top+r.height>c.top&&r.top<c.bottom){card.style.left=Math.max(12,Math.min(innerWidth-card.offsetWidth-12,$('map').clientWidth-card.offsetWidth-16))+'px';}else if(r.left>c.right+40)card.style.left='18px';const box=card.getBoundingClientRect();$('trainingArrow').querySelector('path').setAttribute('d',`M${box.right-10} ${box.top+24} Q${box.right+20} ${r.top+r.height/2} ${r.left-7} ${r.top+r.height/2}`);}
// Keep the native build menu open when advancing its explanation.
$('training').addEventListener('mousedown',e=>e.stopPropagation());
// Observe both native Help and the coach shortcut, including either close control.
new MutationObserver(()=>{
 if(!active||steps[step][3]!=='guide')return;
 if(getComputedStyle($('help')).display!=='none')guideOpened=true;
 else if(guideOpened){step++;show();$('trainingPhase').textContent='COMPLETE · PAUSED';$('trainingNext').hidden=true;$('trainingLocate').hidden=true;$('trainingFeedback').textContent='The opening lesson is complete. The game will stay paused until you choose free practice.';}
 draw();
}).observe($('help'),{attributes:true,attributeFilter:['style']});
$('trainingNext').onclick=()=>{if(steps[step][3]==='observe'&&!completed){observing=true;$('trainingPhase').textContent='RUNNING · OBSERVE REAL CONSTRUCTION';if(game.status().paused)$('pauseBtn').click();return;}if(step<steps.length-1){step++;show();}else free();};
$('trainingLocate').onclick=()=>{if(steps[step][0]==='factory'&&factoryTile!=null){const r=$('map').getBoundingClientRect();game.setCameraOrigin(r.width/2-(factoryTile%720+.5)*8,r.height/2-(Math.floor(factoryTile/720)+.5)*8,8);}else if(['world','map','cityButton'].includes(steps[step][0])){target=game.focusTarget('buildable',6);}else $(steps[step][0])?.scrollIntoView({block:'center'});draw();};
$('trainingGuide').onclick=()=>$('helpBtn2').click();$('trainingHelpReturn').onclick=()=>$('helpClose').click();$('trainingReset').onclick=()=>location.reload();function free(){active=false;game.pause();setCueHidden(true);for(const id of ['training','trainingArrow','trainingRing','trainingHelpReturn'])$(id).hidden=true;$('trainingBadge').textContent='LOCAL REAL-ENGINE PRACTICE · PAUSED · SPACE TO RESUME';} $('trainingExit').onclick=free;
// Prevent accidental unpause while reading, without changing the game's pause implementation.
document.addEventListener('keydown',e=>{if(active&&steps[step][3]!=='pause'&&!observing&&e.code==='Space'&&!e.target.closest('#help')){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('click',e=>{if(active&&steps[step][3]!=='pause'&&!observing&&e.target.closest('#pauseBtn,#pmResume')){e.preventDefault();e.stopImmediatePropagation();}},true);
setInterval(()=>{if(!active)return;const status=game.status(),task=steps[step][3];lastSnapshot=game.snapshot();if(task!=='pause'&&!observing&&!status.paused)game.pause();if(!completed){const c=lastSnapshot.camera;if(task==='out'&&c.scale<baseCamera.scale*.8)finish('Zoomed out with the real camera.');if(task==='pan'&&Math.hypot(c.x-baseCamera.x,c.y-baseCamera.y)>60)finish('Map panned. Simulation remains paused.');if(task==='in'&&c.scale>baseCamera.scale*1.2)finish('Zoomed in on the real battlefield.');if(task==='economy'&&+$('focus').value<=35)finish('Gold share is at least 65%.');if(task==='ratio'&&+$('ratio').value>=30&&+$('ratio').value<=40)finish('A reserve remains at home.');if(task==='pause'){if(!status.paused)seenRunning=true;else if(seenRunning)finish('The actual clock is paused again.');}if(task==='menu'&&getComputedStyle($('ctx')).display!=='none'&&document.querySelector('#ctx [data-type="city"]'))finish('Owned-land construction menu opened.');if(task==='city'&&ownStructures().some(s=>s.type==='city')&&ownStructures().length>baseStructures)finish('City built by the engine. Troops and gold updated.');if(task==='prepare'&&$('hint').textContent.startsWith('Factory mode'))finish('Native factory placement mode active.');if(task==='factory'){const f=ownStructures().filter(s=>s.type==='factory').at(-1);if(f&&ownStructures().length>baseStructures){factoryTile=f.tile;finish('Real factory construction started.');}}if(task==='observe'&&observing){const f=ownStructures().find(s=>s.tile===factoryTile);if(f&&!f.building){observing=false;game.pause();$('trainingPhase').textContent='PAUSED · FACTORY OPERATIONAL';finish('Construction finished through real simulation ticks.');}}}draw();},180);
show();
