const noop=()=>{};
const N8=[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]];

export function createNavalSystem({
  W,H,engineState,settings,allowed,random,rnd,pick,getMe,
  ships,definitions,guns,armor,heavy,cruise,shipBuild,constants,
  landCombat,structures:structureOps,missiles,fog,diplomacy,mechanics,ai,effects={}
}){
  const clock=engineState.clock,map=engineState.map;
  const {land,owner,region,shelled}=map;
  const {players,attacks,missiles:missileActors,structures,transports,warships,shells,traders}=engineState.actors;
  const idx=(x,y)=>y*W+x,inb=(x,y)=>x>=0&&y>=0&&x<W&&y<H;
  const fail=effects.fail||noop,log=effects.log||noop,sound=effects.sound||noop,incrementStat=effects.incrementStat||noop;
  const flash=effects.flash||noop,puff=effects.puff||noop,tracer=effects.tracer||noop,wreck=effects.wreck||noop;
  const cashFloat=effects.cashFloat||noop,barrageResolved=effects.barrageResolved||noop,cleanupSelection=effects.cleanupSelection||noop;
  const onScreen=effects.onScreen||(()=>false),invasion=effects.invasion||noop;

  function waterNeighbor(t){ const x=t%W,y=(t-x)/W; for(const [dx,dy] of N8){ if(inb(x+dx,y+dy)&&!land[idx(x+dx,y+dy)]) return idx(x+dx,y+dy); } return -1; }
  function nearestCoast(p,t){ let best=-1,bd=1e12; const tx=t%W,ty=(t-tx)/W; for(let c=0;c<W*H;c++){ if(owner[c]!==p.id) continue; const x=c%W,y=(c-x)/W,d=(x-tx)**2+(y-ty)**2; if(d<bd&&landCombat.isCoast(c)){bd=d;best=c;} } return best; }
  function nearestPort(p,t){ let best=null,bd=1e12; const tx=t%W,ty=(t-tx)/W; for(const st of structures){ if(st.type!=='port'||st.building||st.owner!==p.id) continue; const x=st.t%W,y=(st.t-x)/W,d=(x-tx)**2+(y-ty)**2; if(d<bd){bd=d;best=st;} } return best; }
  function waterPath(a,b){ if(a<0||b<0) return null; const par=new Int32Array(W*H).fill(-1),q=new Int32Array(W*H); let h=0,tl=0; q[tl++]=a; par[a]=a; while(h<tl){ const c=q[h++]; if(c===b) break; const x=c%W,y=(c-x)/W; for(const [dx,dy] of N8){ const nx=x+dx,ny=y+dy; if(!inb(nx,ny)) continue; const n=idx(nx,ny); if(land[n]||par[n]>=0) continue; par[n]=c; q[tl++]=n; } } if(par[b]<0) return null; const path=[]; for(let c=b;c!==a;c=par[c]) path.push(c); path.push(a); return path.reverse(); }
  function shipXY(sh){ const i=Math.min(sh.path.length-1,Math.floor(sh.pos)),t=sh.path[i]; return [t%W+.5,(t-t%W)/W+.5]; }
  function nearestCoastOf(id,t,reg){ let best=-1,bd=1e12; const tx=t%W,ty=(t-tx)/W; for(let c=0;c<W*H;c++){ if(owner[c]!==id||(reg>=0&&region[c]!==reg)) continue; const x=c%W,y=(c-x)/W,d=(x-tx)**2+(y-ty)**2; if(d<bd&&landCombat.isCoast(c)){bd=d;best=c;} } return best; }
  function heavyFrom(p,fromTile,origin){ if(landCombat.gOn(p)&&origin) return structures.some(st=>st.type==='port'&&(st.level||1)>=2&&!st.building&&st.owner===p.id&&engineState.garrison.areaOf&&engineState.garrison.areaOf[st.t]===origin.id); return structures.some(st=>st.type==='port'&&(st.level||1)>=2&&!st.building&&st.owner===p.id); }
  function launchTransport(p,target,troops,seed,origin){ let from=nearestCoast(p,seed); if(origin&&landCombat.gOn(p)){ let best=-1,bd=1e12; const sx=seed%W,sy=(seed-sx)/W; for(let c=0;c<W*H;c++){ if(owner[c]!==p.id||engineState.garrison.areaOf[c]!==origin.id||!landCombat.isCoast(c)) continue; const d=(c%W-sx)**2+((c-c%W)/W-sy)**2; if(d<bd){bd=d;best=c;} } if(best<0){ if(p===getMe()) fail('That area has no coastline to embark from.'); return false; } from=best; } if(from<0){ if(p===getMe()) log('You need some coastline to embark from.',true); return false; }
    if(!landCombat.isCoast(seed)||owner[seed]!==target){ const near=nearestCoastOf(target,from,region[seed]); if(near>=0) seed=near; } const path=waterPath(waterNeighbor(from),waterNeighbor(seed)); if(!path){ if(p===getMe()) log('No sea route from your coast to that spot.',true); return false; }
    troops=landCombat.takeTroopsFrom(p,origin,troops); if(p===getMe()) sound('foghorn'); const isHeavy=heavyFrom(p,from,origin&&landCombat.gOn(p)?origin:landCombat.areaAt(from)); transports.push({owner:p.id,target,troops,seed,path,pos:0,hdg:0,wake:[],origin:origin?origin.id:null,heavy:isHeavy,hp:isHeavy?heavy.hp:1}); return true; }
  function moveShip(w,t){ if(land[t]) return false; const cur=idx(Math.floor(w.x),Math.floor(w.y)),from=!land[cur]?cur:waterNeighbor(cur),path=waterPath(from,t); if(!path) return false; w.path=path; w.pos=0; w.dest=t; return true; }
  function moveShips(t,group){ let n=0; const active=group.filter(w=>warships.includes(w)&&w.hp>0); active.forEach((w,i)=>{ let tt=t; if(active.length>1){ const ang=i/active.length*Math.PI*2,r=4+Math.floor(active.length/3),x=Math.floor(t%W+Math.cos(ang)*r),y=Math.floor((t-t%W)/W+Math.sin(ang)*r); if(inb(x,y)&&!land[idx(x,y)]) tt=idx(x,y); } if(moveShip(w,tt)) n++; }); return n; }
  function nearestSubBase(p,t){ let best=null,bd=1e12; const tx=t%W,ty=(t-tx)/W; for(const st of structures){ if(st.type!=='subbase'||st.building||st.owner!==p.id) continue; const d=(st.t%W-tx)**2+((st.t-st.t%W)/W-ty)**2; if(d<bd){bd=d;best=st;} } return best; }
  function launchQueuedShip(st,job,p,path){ warships.push({id:engineState.nextUid(),owner:p.id,cls:job.cls,path,pos:0,dest:job.dest,hp:ships[job.cls].hp,cool:0,ang:random()*6.28,hdg:0,wake:[],barCool:0}); }
  function orderWarship(p,t,cls='warship'){ if(mechanics.pausedBlock(p)) return false; if(p.kind==='bot'){ if(p.nextBuildAt>clock.simMs) return false; p.nextBuildAt=clock.simMs+ai.botBuildDelay(p); } const S=ships[cls]; if(land[t]||!allowed.has(cls)) return false; const port=S.sub?nearestSubBase(p,t):nearestPort(p,t); if(!port){ if(p===getMe()&&S.sub) fail('Subs are built at a submarine base.'); return false; } const cost=Math.round(S.cost*(port.linked?1-constants.linkShipDiscount:1)); if(p.gold<cost) return false; const path=waterPath(waterNeighbor(port.t),t); if(!path) return false; p.gold-=cost; let ticks=settings.instant?0:(shipBuild[cls]||0); if(ticks&&port.linked) ticks=Math.round(ticks*0.75); if(ticks<=0){ launchQueuedShip(port,{cls,dest:t},p,path); return true; } const queueLength=structureOps.enqueue(port,{cls,dest:t,total:ticks}); if(p===getMe()) log(`${S.label} laid down at ${S.sub?'the pens':'the yard'}${queueLength>1?' (queued)':''} — ${Math.ceil(ticks/10)} s.`,true); return true; }
  function enemyOf(w,o){ if(o<0||o===w.owner||diplomacy.atPeace(w.owner,o)) return false; const q=players[o]; if(!q.alive) return false; if(q.kind==='neutral') return !!(q.grudge&&q.grudge[w.owner]!=null&&clock.tickN-q.grudge[w.owner]<constants.provokeTicks); return true; }
  function steer(sh,nx,ny){ if(sh.x!=null){ const dx=nx-sh.x,dy=ny-sh.y; if(dx*dx+dy*dy>1e-4){ const want=Math.atan2(dy,dx); let d=want-sh.hdg; d=Math.atan2(Math.sin(d),Math.cos(d)); sh.hdg+=d*0.35; } } sh.x=nx; sh.y=ny; sh.wake.push([nx,ny]); if(sh.wake.length>14) sh.wake.shift(); }
  function shipPiracy(w){ const P=ships[w.cls].pirate; if(!P) return; if(w.boarding){ const tr=w.boarding; if(tr.done||tr.owner===w.owner){ w.boarding=null; return; } tr.held=clock.tickN+3; const dx=tr.x-w.x,dy=tr.y-w.y,dd=Math.hypot(dx,dy); if(dd>1.2){ const sp=ships[w.cls].speed; steer(w,w.x+dx/dd*Math.min(sp,dd-1),w.y+dy/dd*Math.min(sp,dd-1)); return; } if(--w.boardT>0) return; const port=nearestPort(players[w.owner],idx(Math.floor(tr.x),Math.floor(tr.y))); w.boarding=null; w.pirateCool=clock.tickN+P.cd; diplomacy.markHostile(w.owner,tr.owner); if(!port){ if(w.owner===getMe().id) log('Privateer boarded a merchant but you have no port to bring it to.',true); return; } const cur=idx(Math.floor(tr.x),Math.floor(tr.y)),from=!land[cur]?cur:waterNeighbor(cur),path=waterPath(from,waterNeighbor(port.t)); if(!path) return; const victim=players[tr.owner]; tr.from.busy=false; tr.owner=w.owner; tr.to=port; tr.from=port; tr.path=path; tr.pos=0; tr.prize=true; tr.held=0; { const cur2=idx(Math.floor(w.x),Math.floor(w.y)),back=waterPath(!land[cur2]?cur2:waterNeighbor(cur2),w.dest); if(back){ w.path=back; w.pos=0; } } if(w.owner===getMe().id) incrementStat('merchantsCaptured'); log(`${players[w.owner].name}'s privateer captured a ${victim.name} merchant.`,w.owner===getMe().id||victim===getMe()); if(w.owner===getMe().id) sound('cash'); flash({x:tr.x,y:tr.y,r:2,age:0,col:'#ffd27a'}); return; } if(w.pirateCool>clock.tickN) return; let best=null,bd=P.range*P.range; for(const tr of traders){ if(tr.done||tr.x==null||tr.owner===w.owner||tr.prize||diplomacy.atPeace(w.owner,tr.owner)) continue; const d=(tr.x-w.x)**2+(tr.y-w.y)**2; if(d<bd){bd=d;best=tr;} } if(best){ w.boarding=best; w.boardT=P.board; if(w.owner===getMe().id) log('Privateer boarding a merchant…',true); } }
  function seededTierOrder(candidates,tier,rng=random){ return candidates.map((value,index)=>({value,index,key:rng()})).sort((a,b)=>tier(a.value)-tier(b.value)||a.key-b.key||a.value.t-b.value.t||a.value.owner-b.value.owner||a.index-b.index).map(x=>x.value); }
  function cruiseTargets(candidates,rng=random){ const tier=t=>t.type==='shield'?0:t.type==='sam'?1:2; return seededTierOrder(candidates,tier,rng).slice(0,cruise.count); }
  function cruiseTargetsForPresentation(candidates){ const tier=t=>t.type==='shield'?0:t.type==='sam'?1:2; return candidates.map((value,index)=>({value,index})).sort((a,b)=>tier(a.value)-tier(b.value)||a.value.t-b.value.t||a.value.owner-b.value.owner||a.index-b.index).slice(0,cruise.count).map(item=>item.value); }
  function shipCruise(w){ if(!w.cruise||w.cruiseCool>clock.tickN) return; const R=cruise.range,cx=w.x,cy=w.y,foes=structures.filter(st=>!st.building&&enemyOf(w,st.owner)&&((st.t%W+.5-cx)**2+((st.t-st.t%W)/W+.5-cy)**2)<=R*R&&!fog.targetHidden(players[w.owner],st.t)); if(!foes.length) return; w.cruiseCool=clock.tickN+cruise.cd; const picks=cruiseTargets(foes); for(const st of picks){ const dist=Math.hypot(st.t%W+.5-cx,(st.t-st.t%W)/W+.5-cy); missileActors.push({owner:w.owner,t:st.t,from:idx(Math.floor(cx),Math.floor(cy)),age:0,flight:Math.max(40,Math.round(dist/cruise.speed)),cruise:true}); } diplomacy.markHostile(w.owner,picks[0].owner); if(w.owner===getMe().id||picks.some(q=>q.owner===getMe().id)){ sound('missile'); log(`${players[w.owner].name}'s battleship launched cruise missiles at ${players[picks[0].owner].name}'s ${definitions[picks[0].type].label.toLowerCase()}${picks.length>1?' and more':''}.`,true); } }
  function shipBarrage(w){ const B=ships[w.cls].barrage; if(!B||w.barCool>clock.tickN) return; const R=B.range,cx=Math.round(w.x),cy=Math.round(w.y),targets=[],sams=[]; for(const st of structures){ const sx=st.t%W,sy=(st.t-sx)/W; if((sx-cx)**2+(sy-cy)**2<=R*R&&enemyOf(w,st.owner)){ ((st.type==='sam'||st.type==='battery'||st.type==='shore'||st.type==='shield'||(st.type==='port'&&(st.level||1)>=2))?sams:targets).push(st.t); if(st.type==='shield') sams.push(st.t,st.t); } } if(sams.length){ targets.length=0; for(const t of sams) targets.push(t,t); } if(targets.length<B.count){ for(let k=0;k<60&&targets.length<B.count*3;k++){ const x=cx+Math.round(rnd(-R,R)),y=cy+Math.round(rnd(-R,R)); if(!inb(x,y)||(x-cx)**2+(y-cy)**2>R*R) continue; const t=idx(x,y); if(land[t]&&enemyOf(w,owner[t])) targets.push(t); } } if(!targets.length) return; w.barCool=clock.tickN+B.cd; const volley={cas:0,left:B.count,owner:w.owner,victim:owner[targets[0]],cls:w.cls}; for(let i=0;i<B.count;i++){ const t=pick(targets),ang=(w.hdg||0)+Math.PI/2+(i/(B.count-1)-0.5)*1.2,ox=w.x,oy=w.y; shells.push({owner:w.owner,x:w.x+Math.cos(ang)*1.5,y:w.y+Math.sin(ang)*1.5,kind:'land',tx:t%W+.5,ty:(t-t%W)/W+.5,radius:B.radius,trail:[],delay:i,volley,arc:true,missile:true,speed:3.2,rise:14+i*3,ox,oy}); } flash({x:w.x,y:w.y,r:1.5,age:0,col:'#ffd27a'}); if(w.owner===getMe().id||targets.some(t=>owner[t]===getMe().id)) sound('shell'); if(w.owner===getMe().id) log(`${ships[w.cls].label} opened a barrage.`,true); }
  function gunTarget(st){ return (guns[st.type]&&st.type!=='bertha')||(st.type==='port'&&(st.level||1)>=2&&(st.gunHp||0)>0); }
  function stepGuns(){ for(const st of structures){ const G=guns[st.type]||(st.type==='port'&&(st.level||1)>=2?guns.shore:null); if(!G||st.building||shelled[st.t]>clock.tickN||st.cool>clock.tickN) continue; const gx=st.t%W+.5,gy=(st.t-st.t%W)/W+.5,R2=G.range*G.range,own=st.owner; if(st.type==='bertha'){ let best=null,bs=1e12; for(const q of structures){ if(q.owner===own||q.building||diplomacy.atPeace(own,q.owner)||!diplomacy.inConflict(own,q.owner)&&players[q.owner].kind!=='neutral') continue; if(players[q.owner].kind==='neutral'&&!(players[q.owner].grudge&&players[q.owner].grudge[own]!=null)) continue; const d=(q.t%W+.5-gx)**2+((q.t-q.t%W)/W+.5-gy)**2; if(d>R2) continue; const pri=(q.type==='sam'||q.type==='fort'||q.type==='battery'||q.type==='shore')?0.5:1; if(d*pri<bs){bs=d*pri;best=q;} } if(!best) continue; st.cool=clock.tickN+G.cd; const tx=best.t%W+.5,ty=(best.t-best.t%W)/W+.5; shells.push({owner:own,x:gx,y:gy,kind:'land',tx,ty,radius:G.radius,trail:[],delay:0,speed:3,arc:true,volley:{cas:0,left:1,owner:own,victim:best.owner,cls:'bertha'},ox:gx,oy:gy}); if(own===getMe().id||best.owner===getMe().id) sound('bertha',gx,gy); continue; }
      let tgt=null,bd=R2,kind=null; for(const tr of transports){ if(tr.done||tr.x==null||tr.owner===own||diplomacy.atPeace(own,tr.owner)) continue; const d=(tr.x-gx)**2+(tr.y-gy)**2; if(d<bd){bd=d;tgt=tr;kind='transport';} } if(!tgt){ bd=R2; for(const w of warships){ if(w.owner===own||w.hp<=0||w.x==null||ships[w.cls].sub||diplomacy.atPeace(own,w.owner)||!diplomacy.inConflict(own,w.owner)&&!(w.cls==='cruiser'||w.cls==='battleship')) continue; const d=(w.x-gx)**2+(w.y-gy)**2; if(d<bd){bd=d;tgt=w;kind='warship';} } } if(!tgt) continue; st.cool=clock.tickN+G.cd; const dmg=(st.type==='shore'||st.type==='port')&&kind==='warship'?G.dmg/(armor[tgt.cls]||1):G.dmg; st.lastShotAt=tgt.owner; shells.push({owner:own,cls:st.type==='port'?'shore':st.type,x:gx,y:gy,target:tgt,kind,trail:[],dmg,speed:(st.type==='shore'||st.type==='port')?7:4,from:st}); if(own===getMe().id||tgt.owner===getMe().id) sound((st.type==='shore'||st.type==='port')?'shoreguns':'battery',gx,gy); } }
  function seaRisk(p,origin,dest){ const pickCoast=(area,nearT)=>{ let best=-1,bd=1e12; const nx=nearT%W,ny=(nearT-nx)/W; for(let c=0;c<W*H;c++){ if(owner[c]!==p.id||engineState.garrison.areaOf[c]!==area.id||!landCombat.isCoast(c)) continue; const d=(c%W-nx)**2+((c-c%W)/W-ny)**2; if(d<bd){bd=d;best=c;} } return best; }; const dT=idx(Math.round(dest.cx),Math.round(dest.cy)),to=pickCoast(dest,dT); if(to<0) return 99; const from=pickCoast(origin,to); if(from<0) return 99; const path=waterPath(waterNeighbor(from),waterNeighbor(to)); if(!path) return 99; let risk=0; const pts=[]; for(let i=0;i<path.length;i+=6) pts.push(path[i]); pts.push(path[path.length-1]); for(const t of pts){ const x=t%W,y=(t-x)/W; for(const w of warships){ if(w.owner===p.id||w.hp<=0||w.x==null||diplomacy.atPeace(p.id,w.owner)) continue; if(!(diplomacy.inConflict(p.id,w.owner)||ships[w.cls].sub)) continue; if(ships[w.cls].sub&&!subSeenBy(w,p.id)) continue; if((w.x-x)**2+(w.y-y)**2<=(t===path[path.length-1]?900:400)) risk+=ships[w.cls].sub?1:2; } } const tx=to%W,ty=(to-tx)/W; for(const st of structures){ if(st.building||st.owner===p.id||diplomacy.atPeace(p.id,st.owner)||!diplomacy.inConflict(p.id,st.owner)) continue; if(!(gunTarget(st)||st.type==='bertha')) continue; const R=st.type==='port'?14:(guns[st.type]||{range:14}).range; if((st.t%W-tx)**2+((st.t-st.t%W)/W-ty)**2<=(R+4)**2) risk+=2; } return risk; }
  function reinforceArea(p,dest,origin,troops){ if(mechanics.pausedBlock(p)||!landCombat.gOn(p)||!dest||!origin||dest===origin) return false; troops=Math.min(troops,origin.troops); if(troops<5){ if(p===getMe()) fail('Not enough troops in that area.'); return false; } const pickCoast=(area,nearT)=>{ let best=-1,bd=1e12,nx=nearT%W,ny=(nearT-nx)/W; for(let c=0;c<W*H;c++){ if(owner[c]!==p.id||engineState.garrison.areaOf[c]!==area.id||!landCombat.isCoast(c)) continue; const d=(c%W-nx)**2+((c-c%W)/W-ny)**2; if(d<bd){bd=d;best=c;} } return best; }; const dT=idx(Math.round(dest.cx),Math.round(dest.cy)),to=pickCoast(dest,dT); if(to<0){ if(p===getMe()) fail('That area has no coastline to land on.'); return false; } const from=pickCoast(origin,to); if(from<0){ if(p===getMe()) fail('The origin area has no coastline to embark from.'); return false; } const path=waterPath(waterNeighbor(from),waterNeighbor(to)); if(!path){ if(p===getMe()) fail('No sea route between those areas.'); return false; } landCombat.takeTroopsFrom(p,origin,troops); const isHeavy=heavyFrom(p,from,origin); transports.push({owner:p.id,target:p.id,troops,seed:to,path,pos:0,hdg:0,wake:[],origin:origin.id,heavy:isHeavy,hp:isHeavy?heavy.hp:1}); if(p===getMe()){ log(`${Math.round(troops)} troops embarking from ${mechanics.areaName(p,origin)} to reinforce ${mechanics.areaName(p,dest)}.`,true); sound('foghorn'); } return true; }
  function stepTrade(){ if(clock.tickN%20===0){ const ports=structures.filter(st=>st.type==='port'&&!st.building&&players[st.owner].kind!=='neutral'&&players[st.owner].alive); for(const pt of ports){ if(pt.nextTrade==null) pt.nextTrade=clock.tickN+rnd(30,constants.tradeInterval); if(pt.nextTrade>clock.tickN||pt.busy) continue; const dests=ports.filter(q=>q.owner!==pt.owner&&!diplomacy.inConflict(pt.owner,q.owner)); if(!dests.length){ pt.nextTrade=clock.tickN+60; continue; } const allies=dests.filter(q=>diplomacy.relation(players[pt.owner],players[q.owner])?.type==='ally'),to=allies.length&&random()<0.6?pick(allies):pick(dests),path=waterPath(waterNeighbor(pt.t),waterNeighbor(to.t)); pt.nextTrade=clock.tickN+constants.tradeInterval; if(!path||path.length<8) continue; pt.busy=true; traders.push({owner:pt.owner,from:pt,to,path,pos:0,hdg:0,wake:[],x:null,y:null}); } } for(const tr of traders){ if(tr.held&&tr.held>clock.tickN) continue; tr.pos+=constants.tradeSpeed; const [x,y]=shipXY(tr); steer(tr,x,y); if(tr.pos<tr.path.length-1) continue; tr.done=true; tr.from.busy=false; const a=players[tr.owner],b=players[tr.to.owner]; if(!b.alive||tr.to.owner!==b.id||!structures.includes(tr.to)) continue; if(tr.prize){ const g=Math.round((constants.tradeGold+tr.path.length*constants.tradePerTile)*2); a.gold+=g; a.tradeIncome=(a.tradeIncome||0)+g; if(a===getMe()){ cashFloat(tr.to.t%W,(tr.to.t-tr.to.t%W)/W,g); sound('cash'); log(`Prize cargo landed: +${g} gold.`,true); } continue; } const g=Math.round(constants.tradeGold+tr.path.length*constants.tradePerTile); a.gold+=g; b.gold+=g; a.tradeIncome=(a.tradeIncome||0)+g; b.tradeIncome=(b.tradeIncome||0)+g; if(a===getMe()||b===getMe()){ effects.floater?.({x:tr.to.t%W,y:(tr.to.t-tr.to.t%W)/W,txt:'+$'+g,age:0,col:'#ffd27a'}); sound('coin'); } } engineState.retainActors('traders',t=>{ if(t.done||!players[t.owner].alive){ t.from.busy=false; return false; } return true; }); }
  function subSeenBy(w,viewer){ if(!ships[w.cls].sub) return true; if(w.owner===viewer||diplomacy.atPeace(w.owner,viewer)&&diplomacy.relation(players[w.owner],players[viewer])?.type==='ally') return true; for(const e of warships){ if(e.owner!==viewer&&!(diplomacy.relation(players[e.owner],players[viewer])?.type==='ally')) continue; if(!(e.cls==='warship'||e.cls==='hunter'||e.cls==='rship')||e.x==null) continue; const R=e.cls==='hunter'?20:8; if((e.x-w.x)**2+(e.y-w.y)**2<=R*R) return true; } return false; }
  function stepNaval(){
    for(const tr of transports){ tr.pos+=constants.shipSpeed*(tr.heavy?heavy.speedMul:1); const [tx,ty]=shipXY(tr); steer(tr,tx,ty); if(tr.pos<tr.path.length-1) continue; tr.done=true; const p=players[tr.owner]; if(!p.alive) continue; const o=owner[tr.seed];
      if(tr.gift){ const ally=players[tr.target]; if(ally.alive&&o===ally.id){ if(landCombat.gOn(ally)) landCombat.addTroopsAt(ally,tr.seed,tr.troops); else ally.troops+=tr.troops; log(`${tr.troops|0} ${p.name} troops reinforced ${ally.name}.`,p===getMe()||ally===getMe()); if(ally===getMe()) sound('foghorn'); } else p.troops+=tr.troops; continue; }
      if(p===getMe()&&!tr.gift) incrementStat('landings'); if(o===p.id){ landCombat.addTroopsAt(p,tr.seed,tr.troops); continue; }
      attacks.push({owner:p.id,target:o,troops:tr.troops,front:new Set([tr.seed]),naval:true,age:0,origin:null,landAt:tr.seed,startTiles:o>=0?players[o].tiles:0}); if(o===getMe().id) invasion(p,tr.seed,true); if(o>=0) mechanics.noteThreat(o,tr.seed,'landing',p.id); if(p===getMe()){ log(`Landing force ashore on ${o>=0?players[o].name:'unclaimed coast'}.`,true); sound('foghorn'); }
    }
    engineState.retainActors('transports',t=>!t.done);
    for(const tr of transports){ if(!tr.heavy||tr.done||!tr.attacker||tr.x==null) continue; if(clock.tickN-(tr.attackedAt||0)>100||tr.cool>clock.tickN) continue; const a=tr.attacker,ax=a.t!=null?a.t%W+.5:a.x,ay=a.t!=null?(a.t-a.t%W)/W+.5:a.y; if(ax==null||(a.t==null&&(a.hp<=0||a.done||(a.cls&&ships[a.cls]&&ships[a.cls].sub)))||(a.t!=null&&!structures.includes(a))){ tr.attacker=null; continue; } if((ax-tr.x)**2+(ay-tr.y)**2>heavy.gun*heavy.gun) continue; tr.cool=clock.tickN+heavy.cd; if(a.t!=null) shells.push({owner:tr.owner,cls:'warship',x:tr.x,y:tr.y,kind:'gun',target:a,tx:ax,ty:ay,trail:[],dmg:heavy.dmg,speed:7}); else shells.push({owner:tr.owner,cls:'warship',x:tr.x,y:tr.y,target:a,kind:'warship',trail:[],dmg:heavy.dmg,speed:7}); if(tr.owner===getMe().id) sound('shell',tr.x,tr.y); }
    for(const w of warships){
      if(w.refit){} else if(w.boarding){} else if(w.pos<w.path.length-1){ w.pos+=ships[w.cls].speed; const [nx,ny]=shipXY(w); steer(w,nx,ny); } else if(!w.boarding){ w.ang+=0.025; const dx=w.dest%W+.5,dy=(w.dest-w.dest%W)/W+.5; let placed=false; for(const rad of [5,3,1.5]){ const nx=dx+Math.cos(w.ang)*rad,ny=dy+Math.sin(w.ang)*rad,tx=Math.floor(nx),ty=Math.floor(ny); if(inb(tx,ty)&&!land[idx(tx,ty)]){ steer(w,nx,ny); placed=true; break; } } if(!placed) steer(w,dx,dy); }
      if(w.refit&&w.refit<=clock.tickN){ w.refit=0; w.cruise=true; w.cruiseCool=0; if(w.owner===getMe().id) log('Battleship refit complete: cruise missiles online.',true); }
      if(!w.refit) shipCruise(w); shipBarrage(w); shipPiracy(w);
      if(ships[w.cls].torpedo){ const T=ships[w.cls].torpedo; if(w.cool>0){ w.cool--; continue; } const R2=T.range*T.range; let tg=null,td=R2,kind=null;
        if(ships[w.cls].hunter){ for(const e of warships){ if(e===w||e.owner===w.owner||e.hp<=0||!ships[e.cls].sub||diplomacy.atPeace(w.owner,e.owner)||!diplomacy.inConflict(w.owner,e.owner)&&!e.subHostile) continue; const d=(e.x-w.x)**2+(e.y-w.y)**2; if(d<=400&&d<td){td=d;tg=e;kind='warship';} } }
        else { for(const tr of transports){ if(tr.done||tr.x==null||tr.owner===w.owner||diplomacy.atPeace(w.owner,tr.owner)||!(tr.target===w.owner||diplomacy.inConflict(w.owner,tr.owner))) continue; const d=(tr.x-w.x)**2+(tr.y-w.y)**2; if(d<td){td=d;tg=tr;kind='transport';} } if(!tg) for(const e of warships){ if(e===w||e.owner===w.owner||e.hp<=0||ships[e.cls].sub||diplomacy.atPeace(w.owner,e.owner)||!diplomacy.inConflict(w.owner,e.owner)&&!(e.cls==='cruiser'||e.cls==='battleship')) continue; const d=(e.x-w.x)**2+(e.y-w.y)**2; if(d<td){td=d;tg=e;kind='warship';} } }
        if(tg){ w.cool=T.cd; w.subHostile=true; shells.push({owner:w.owner,cls:w.cls,x:w.x,y:w.y,target:tg,kind,trail:[],dmg:T.dmg,speed:3,torpedo:true,from:w}); if(w.owner===getMe().id||tg.owner===getMe().id) sound('torpedo',w.x,w.y); } continue;
      }
      if(!ships[w.cls].gun) continue; if(w.cool>0){ w.cool--; continue; } const R2=ships[w.cls].gun**2; let hit=null,hd=R2;
      for(const tr of traders){ if(tr.done||tr.owner===w.owner||!diplomacy.inConflict(w.owner,tr.owner)||tr.x==null) continue; const d=(tr.x-w.x)**2+(tr.y-w.y)**2; if(d<hd){hd=d;hit=tr;} }
      if(hit){ shells.push({owner:w.owner,cls:w.cls,x:w.x,y:w.y,target:hit,kind:'trader',trail:[],dmg:1}); w.cool=6; if(w.owner===getMe().id||hit.owner===getMe().id) sound('shell',w.x,w.y); continue; }
      hit=null; hd=R2; for(const tr of transports){ if(tr.done||tr.owner===w.owner||diplomacy.atPeace(w.owner,tr.owner)) continue; const [x,y]=shipXY(tr),d=(x-w.x)**2+(y-w.y)**2; if(d<hd){hd=d;hit=tr;} }
      if(hit){ w.fireAt=clock.tickN; w.fireAng=Math.atan2(hit.y-w.y,hit.x-w.x); shells.push({owner:w.owner,cls:w.cls,x:w.x,y:w.y,target:hit,kind:'transport',trail:[],dmg:ships[w.cls].dmg,from:w}); w.cool=6; if(w.owner===getMe().id||hit.owner===getMe().id) sound('shell',w.x,w.y); continue; }
      { let g=null,gd=R2; for(const st of structures){ if(!gunTarget(st)||st.building||st.owner===w.owner||diplomacy.atPeace(w.owner,st.owner)) continue; if(!(diplomacy.inConflict(w.owner,st.owner)||st.lastShotAt===w.owner)) continue; const sx=st.t%W+.5,sy=(st.t-st.t%W)/W+.5,d=(sx-w.x)**2+(sy-w.y)**2; if(d<gd){gd=d;g=st;} } if(g){ shells.push({owner:w.owner,cls:w.cls,x:w.x,y:w.y,kind:'gun',target:g,tx:g.t%W+.5,ty:(g.t-g.t%W)/W+.5,trail:[],dmg:ships[w.cls].dmg}); w.cool=10; if(w.owner===getMe().id||g.owner===getMe().id) sound('shell',w.x,w.y); continue; } }
      hd=R2; let tgt=null; for(const e of warships){ if(e===w||e.owner===w.owner||e.hp<=0||diplomacy.atPeace(w.owner,e.owner)) continue; if(ships[e.cls].sub&&!subSeenBy(e,w.owner)) continue; const d=(e.x-w.x)**2+(e.y-w.y)**2; if(d<hd){hd=d;tgt=e;} } if(tgt){ w.fireAt=clock.tickN; w.fireAng=Math.atan2(tgt.y-w.y,tgt.x-w.x); shells.push({owner:w.owner,cls:w.cls,x:w.x,y:w.y,target:tgt,kind:'warship',trail:[],dmg:ships[w.cls].dmg*(w.cls==='warship'&&tgt.cls==='cruiser'?2:1)}); w.cool=10; if(w.owner===getMe().id||tgt.owner===getMe().id) sound('shell',w.x,w.y); }
    }
    for(const sh of shells){
      if(sh.delay>0){ sh.delay--; continue; } const spd=sh.speed||constants.shellSpeed;
      if(sh.kind==='aam'){ const tg=sh.target,tx=tg.x,ty=tg.y,dx=tx-sh.x,dy=ty-sh.y,d=Math.hypot(dx,dy); sh.trail.push([sh.x,sh.y]); if(sh.trail.length>8) sh.trail.shift(); if(d<=spd||tg.dead){ sh.done=true; flash({x:tx,y:ty,r:1.2,age:0,col:'#ffd27a'}); continue; } sh.x+=dx/d*spd; sh.y+=dy/d*spd; continue; }
      if(sh.kind==='gun'){ const g=sh.target; if(!structures.includes(g)){ sh.done=true; continue; } const dx=sh.tx-sh.x,dy=sh.ty-sh.y,d=Math.hypot(dx,dy); sh.trail.push([sh.x,sh.y]); if(sh.trail.length>6) sh.trail.shift(); if(d<=spd){ sh.done=true; flash({x:sh.tx,y:sh.ty,r:1.5,age:0,col:'#ffd27a'}); diplomacy.markHostile(sh.owner,g.owner); if(sh.owner===getMe().id||g.owner===getMe().id) sound('shellhit',sh.tx,sh.ty); if(g.type==='port'){ g.gunHp=(g.gunHp||0)-sh.dmg; if(g.gunHp<=0){ g.level=1; g.gunHp=0; log(`${players[sh.owner].name} shot out the guns of ${players[g.owner].name}'s port — it is level I again.`,sh.owner===getMe().id||g.owner===getMe().id); } continue; } g.hp-=sh.dmg; if(g.hp<=0){ const own=players[g.owner]; structureOps.destroyStructure(g.t); structureOps.structCounts(own); flash({x:sh.tx,y:sh.ty,r:3,age:0,col:'#ffb347'}); log(`${players[sh.owner].name}'s ${ships[sh.cls].label.toLowerCase()} destroyed ${own.name}'s ${definitions[g.type].label.toLowerCase()}.`,sh.owner===getMe().id||own===getMe()); } continue; } sh.x+=dx/d*spd; sh.y+=dy/d*spd; continue; }
      if(sh.kind==='land'){ const dx=sh.tx-sh.x,dy=sh.ty-sh.y,d=Math.hypot(dx,dy); { const tot=sh.tot||(sh.tot=Math.max(1,d)),k=1-Math.min(1,d/tot); sh.trail.push([sh.x,sh.y,Math.sin(k*Math.PI)*(sh.rise||14)*0.6]); } if(sh.trail.length>(sh.missile?10:6)) sh.trail.shift(); if(d<=spd){ sh.done=true; tracer(sh.ox??sh.trail[0]?.[0]??sh.x,sh.oy??sh.trail[0]?.[1]??sh.y,sh.tx,sh.ty); puff(sh.tx-.5,sh.ty-.5,3,'110,100,90'); const c=missiles.crater(Math.floor(sh.tx),Math.floor(sh.ty),sh.radius,sh.owner),v=sh.volley; if(v){ v.cas+=c; if(--v.left<=0&&(v.owner===getMe().id||v.victim===getMe().id)&&v.victim>=0) barrageResolved(v); } continue; } sh.x+=dx/d*spd; sh.y+=dy/d*spd; continue; }
      const tg=sh.target; if(tg.done||tg.hp<=0){ sh.done=true; continue; } const dx=tg.x-sh.x,dy=tg.y-sh.y,d=Math.hypot(dx,dy); sh.trail.push([sh.x,sh.y]); if(sh.trail.length>(sh.torpedo?22:6)) sh.trail.shift();
      if(d<=spd){ sh.done=true; const mine=sh.owner===getMe().id||tg.owner===getMe().id; diplomacy.markHostile(sh.owner,tg.owner);
        if(sh.kind==='trader'){ tg.done=true; tg.from.busy=false; mechanics.noteThreat(tg.owner,idx(Math.floor(tg.x),Math.floor(tg.y)),'blockade',sh.owner); flash({x:tg.x,y:tg.y,r:2.5,age:0,col:'#ffb347'}); wreck('ship',tg.x,tg.y,tg.hdg,players[tg.owner].color,'trader'); players[sh.owner].gold+=60; if(mine) sound('sunk',tg.x,tg.y); if(sh.owner===getMe().id){ if(onScreen(tg.x,tg.y)) sound('coin',tg.x,tg.y); cashFloat(tg.x,tg.y,60); } log(`${players[sh.owner].name} sank a ${players[tg.owner].name} merchant ship (+60 gold).`,mine); continue; }
        if(sh.kind==='transport'&&tg.heavy){ tg.hp-=sh.dmg||1; tg.attacker=sh.from||null; tg.attackedAt=clock.tickN; flash({x:tg.x,y:tg.y,r:1.5,age:0,col:'#ffd27a'}); if(mine) sound('shellhit',tg.x,tg.y); if(tg.hp>0) continue; }
        if(sh.kind==='transport'){ tg.done=true; flash({x:tg.x,y:tg.y,r:3,age:0,col:'#ffb347'}); wreck('ship',tg.x,tg.y,tg.hdg,players[tg.owner].color,'transport'); if(mine) sound('sunk',tg.x,tg.y); const bounty=Math.max(20,Math.round(tg.troops*constants.sinkBounty)); players[sh.owner].gold+=bounty; if(sh.owner===getMe().id){ if(onScreen(tg.x,tg.y)) sound('coin',tg.x,tg.y); cashFloat(tg.x,tg.y,bounty); } log(`${players[sh.owner].name}'s ${(ships[sh.cls]||definitions[sh.cls]||ships.warship).label.toLowerCase()} sank a transport carrying ${Math.round(tg.troops)} ${players[tg.owner].name} troops${sh.owner===getMe().id?` (+${bounty} gold salvage)`:''}.`,mine); }
        else { tg.hp-=sh.dmg||1; flash({x:tg.x,y:tg.y,r:1.5,age:0,col:'#ffd27a'}); if(mine) sound('shellhit',tg.x,tg.y); if(tg.hp<=0){ if(sh.owner===getMe().id) incrementStat('shipsSunk'); if(tg.owner===getMe().id) incrementStat('shipsLost'); flash({x:tg.x,y:tg.y,r:4,age:0,col:'#ffb347'}); wreck('ship',tg.x,tg.y,tg.hdg,players[tg.owner].color,tg.cls); if(sh.torpedo){ players[tg.owner].subLoss=(players[tg.owner].subLoss||0)+1; mechanics.noteThreat(tg.owner,idx(Math.floor(tg.x),Math.floor(tg.y)),'torpedo',sh.owner); } puff(tg.x-.5,tg.y-.5,5,'60,60,60'); if(mine) sound('sunk',tg.x,tg.y); log(`${players[sh.owner].name}'s ${(ships[sh.cls]||definitions[sh.cls]||ships.warship).label.toLowerCase()} sank a ${players[tg.owner].name} ${ships[tg.cls]?ships[tg.cls].label.toLowerCase():'ship'}.`,mine); } } continue;
      }
      sh.x+=dx/d*spd; sh.y+=dy/d*spd;
    }
    engineState.retainActors('shells',sh=>!sh.done); engineState.retainActors('transports',t=>!t.done); engineState.retainActors('warships',w=>w.hp>0&&players[w.owner].alive); cleanupSelection(warships);
  }

  return Object.freeze({waterNeighbor,nearestCoast,nearestPort,waterPath,shipXY,nearestCoastOf,heavyFrom,launchTransport,moveShip,moveShips,nearestSubBase,launchQueuedShip,orderWarship,enemyOf,seededTierOrder,cruiseTargets,cruiseTargetsForPresentation,gunTarget,stepGuns,seaRisk,reinforceArea,stepTrade,subSeenBy,stepNaval});
}
